### ISSUE TITLE
Option to disable chat

### ISSUE THREAD

**Issue by Kyllingene** [yvt/openspades#1006]
A lot of the community is nice, but especially with unregulated servers (a good thing imo, but it does have it's downsides), sometimes it can be a bit toxic. The ability to disable the chatbox would be much appreciated.

**Comment by DryByte** [comment]
In most part of servers you can use **/deaf**, also you can just do **/cg_chatHeight 0**

**Comment by Thelucri** [comment]
@Kyllingene @yvt I think you can close this issue, draybyte have responded to this question
