### ISSUE TITLE
game only crashes when using the opengl renderer

### ISSUE THREAD

**Issue by unmellow** [yvt/openspades#1024]
OS: Manjaro Linux x86_64
motherboard:   Gigabyte Technology GA-A320M-S2H
CPU: AMD Ryzen 5 1600X (12) @ 3.600GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 2870MiB / 16005MiB
Kernel: 5.16.18-1-MANJARO
WM: sway

This all provided by the linux command [neofetch](https://github.com/dylanaraps/neofetch)
pretty sure my gpu is a 580

game version 0.1.3

this is the what it spits into my terminal
[spades.error.txt](https://gist.github.com/unmellow/b8999e98d8fe6b8f8f54e765bb4669af)
and this is the error screen thing idk what to call it
![2022-06-04T04:00:06,234152129-04:00](https://user-images.githubusercontent.com/30985587/171990806-3f0fa7cd-27b7-494d-b422-98fd85a8e0a3.png)

incase it is relevant this is the install script i used 
https://aur.archlinux.org/packages/openspades

link to PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openspades

link to .install
https://aur.archlinux.org/cgit/aur.git/tree/openspades.install?h=openspades

link to .SRCINFO
https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=openspades

and at the very least I know i can run minecraft and many other video games that I can only assume use opengl
so I would be surprised if my mesa is the issue

**Comment by unmellow** [comment]
figured out where the system messages .lof file was
https://gist.github.com/unmellow/222683d22d38287a6ba31c56f304e93f

**Comment by devnexen** [comment]
Just curious, I wonder whether if you have installed this version of GLEW https://software.manjaro.org/package/glew1.10 or this one https://software.manjaro.org/package/glew

**Comment by unmellow** [comment]
apparently both are installed

**Comment by devnexen** [comment]
[openspades-0.1.3.zip](https://github.com/yvt/openspades/files/8839747/openspades-0.1.3.zip)
Would you be able to build from source from this slightly modified version ? No guaranteeing it will fix your issue but at least to see if the error message would change.

**Comment by unmellow** [comment]
ok tested it it got the same crash graphic and the logs look similar but I haven't been thorough

**Comment by unmellow** [comment]
actually i installed https://aur.archlinux.org/packages/glew-wayland
which required that I uninstalled  glew and openspades then tried 
running the custom binary and it worked

Apparently this is wayland weirdness i doubt you can actually effect in anyway
so feel free to close unless you have greater insight

**Comment by unmellow** [comment]
I modified the package build og glew-wayland to contain 
```sh
provides=(glew)
```
which let me reinstall the package of openspades and that also worked so doubly not something wrong with openspades itself

**Comment by devnexen** [comment]
that s good news.

**Comment by unmellow** [comment]
I forgot I had SDL_VIDEODRIVER set to wayland
so another possibly simpler trick that I haven't tested is to unset SDL_VIDEODRIVER

**Comment by hardBSDk** [comment]
Maybe the same thing happens to me with GNOME on Wayland.

Any quick workaround without the need to disable Wayland? maybe changing SDL driver?

**Comment by unmellow** [comment]
This should only happen if you have the environment variable `SDL_VIDEODDRIVER=Wayland` set somewhere.
So the fixes are to unset or set this to x11, install glew compiled for Wayland support, or don't use Wayland. Hope this helps

**Comment by unmellow** [comment]
I feel like this can reasonably be closed and I know the devs can un close it if they feel their is something that still needs to be discussed.
