### ISSUE TITLE
 Hope your dirty and cheap throats get slit, silly yvt.

### ISSUE THREAD

**Issue by ghost** [yvt/openspades#1060]
@yvt  Death to you yvt, you cheap loser daft slave. Death to you for boasting about garbage trash in your ugly avatar description. Death to you for using that disgusting 3/6-letter clownish word .

 Death to every loser donkey who uses that disgusting & racist 6 letter donkey word. 

Death to every loser shill who praises the garbage of society, AKA "universities" [DUMPSTERversities]. Death to you for being such stupid mainstream shills and praising yourself. And "computer science" is a garbage and laughable kiddie subject. You're all nothing but super childish & daft shills. Your projects are nothing but utter trash, and you have no potential, and are a complete and utter laughable failure, yvt. Open Spades is an utter joke and trashware made by a complete loser. Death to every idiot who uses the stupid 6-letter "prefixes" when mentioning first names. Death to "universities" [DUMPSTERversities]. Death to your brain-dead opensource toxic filthy mind. Have a sad life and painful death, yvt.

Hope your dirty and cheap throats get slit, silly yvt.

@yvt-IsTheLoser

**Comment by dakrk** [comment]
sir do you need mental help

**Comment by f46n** [comment]
Honestly quite incredible.

**Comment by xtreme8000** [comment]
@yvt you can also delete these issues, there's a button on the bottom right
