### ISSUE TITLE
Some dependencies don't allow to install the build

### ISSUE THREAD

**Issue by RaphLeSel** [yvt/openspades#1072]
When I tried to install the software with the dependencies from the doc, I found that libcurl3-openssl-dev and libsdl2-image-dev prevented the installation of the build but I could not find any solutions to this.

**Comment by devnexen** [comment]
If you want any help you might need to give a more detailed description of your issue.
Beyond that, I would suggest libcurl4-openssl-dev, if you have it, instead.

**Comment by RaphLeSel** [comment]
I realised that my issue was kinda bad so I reformulate it.

I was downloading the game on an Ubuntu 22.04 and the package "libcurl3-openssl-dev" don't allowed me to completed it. So I tried with what you suggest and it works.

So even if it's not a big problem, it can be great to update it on the documentation for the newcomers and people that just want to download the game from the github.
