### ISSUE TITLE
I can't see any text!

### ISSUE THREAD

**Issue by Exoshyft** [yvt/openspades#113]
When I enter the game I can't see who's on the game, the teams, the guns, health, ammo, the chat box, and all the other text you should see, I don't see.

**Comment by chryp** [comment]
![bandicam 2014-04-06 12-11-34-268](https://cloud.githubusercontent.com/assets/12099848/7319560/c5635376-ea96-11e4-86fb-b1d0fc3aa355.jpg)
I've this problem

**Comment by feikname** [comment]
The main problem was solved already.
