### ISSUE TITLE
Graphics Issue with Post Filter "Low"

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#114]
![shot0384](https://f.cloud.github.com/assets/5253988/1827611/85a5cd2a-723a-11e3-9855-db550b4e42b2.png)

Uncountable dots on particles.

Confirmed on:
- OS X 10.9 Mavericks, 58a1e10d4ea0fe3dd8189356fabdebd1d103f4cb, Intel HD Graphics 4000, Post Filter "Low"

**Comment by pielover88888** [comment]
Issue still occurs on Win7 using Intel HD 4000

**Comment by yvt** [comment]
Confirmed on macOS 10.12.3 Beta using Intel HD Graphics 4000.
