### ISSUE TITLE
Not all characters viewable in default font

### ISSUE THREAD

**Issue by rakiru** [yvt/openspades#117]
The default font should be able to display all characters the official client can, which I'm assuming is the whole of CP437.
"|" (pipe) character, for example:
![Pipe character](https://dl.dropbox.com/u/7298729/ZScreen/2014-01/Screenshot-2014-01-05_20.04.59.png)

**Comment by yvt** [comment]
Closing this since 0.1.0 comes with `font-unifont.pak` (which contains all Unicode BMP characters) installed to `Resources` by default.
