### ISSUE TITLE
Shots trace on minimap

### ISSUE THREAD

**Issue by noway421** [yvt/openspades#139]
Shots trace is very important element of the game. It should be created in openspades too.

**Comment by Kurtoid** [comment]
Agreed

**Comment by feikname** [comment]
Well, they exist now. (#229)

**Comment by Kurtoid** [comment]
The issue you linked is not the same as this. This issue concerns the
rendering of tracers on the minimap.

**Comment by noway421** [comment]
yep, meant minimap, fixed title for clarification. i believe should be reopened

**Comment by feikname** [comment]
@noway421 Thanks for pointing out, I didn't realize. I think there was a commit to show them on minimap recently, I will check it later. 

Reopening in the meantime.
