### ISSUE TITLE
Player bodies not removed sometimes after round end in arena gamemode

### ISSUE THREAD

**Issue by noway** [yvt/openspades#145]
Not sure how it happens exactly, but sometimes bodies just lay around after new round is started. But all players respawned. Maybe it's disconnected players?

**Comment by feikname** [comment]
@yvt Can I add this to the 0.1.2 milestone?

**Comment by yvt** [comment]
@feikname Is there a way to detect the round end? Seeing a body (especially one with rag-doll physics) suddenly disappear at the timing of respawn is something I don't want to see.

Also, players already are already given an option to disable the rag-doll physics, hence disabling this intended behavior.

**Comment by feikname** [comment]
@yvt We could go on a per game mode basis.

For example, in servers with the gamemode `arena` and the map prefix `cs_` round end is the player respawn, I think. Can we use that approach?

**Comment by yvt** [comment]
@feikname Sounds like a plan! Except the part about the map prefix — that'll cause a false detection. I think there was a scaled version of a CS map in aloha.pk babel or somewhere...

**Comment by NotAFile** [comment]
We could also add a packet to piqueserver, but intial adoption would be low until more admins use it.
