### ISSUE TITLE
linux mint install error 

### ISSUE THREAD

**Issue by axaluss** [yvt/openspades#159]
When i install openspades as described like that: https://gist.github.com/axaluss/9353193
i get this error in the last step: 
https://gist.github.com/axaluss/9353176

Ubuntu / Linux Mint 
3.8.0-35-generic #50-Ubuntu SMP Tue Dec 3 01:24:59 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by VelocityRa** [comment]
Fixed (see more info in the issue above)
