### ISSUE TITLE
Building on Visual Studio Express

### ISSUE THREAD

**Issue by noway** [yvt/openspades#208]
While building on Visual Studio Express 2013 this error appears:

> error LINK2026: module unsafe for SAFESEH image (zlib.lib)

Google suggests to turn off SAFESEH for linker, but there is no such option in project properties in visual studio express.

Adding this lines CMakeLists.txt not working too, for some reason.

```
SET (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SAFESEH:NO")
SET (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO")
SET (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")
```

How to fix it, and link openspades successfully? Maybe maintainer update precompiled binaries? Or cmake options were missused in this case?

**Comment by Kurtoid** [comment]
I still have the error after turning it off.
