### ISSUE TITLE
Crash on "ctrl + v" and localhost link

### ISSUE THREAD

**Issue by iayf** [yvt/openspades#211]
Maybe this has also been reported in #209, however i have a completely unmodified client (no mods or changed png sights). Whenever i want to paste a server url into the 0.0.10 client, it crashes. SystemMessages.log doesn't show any error.
Beside this, it would be very great to have a localhost option in the server browser.
I'm using Windows 8 64-bit.

**Comment by VelocityRa** [comment]
This is very old, if the problem's still present tell me and I'll re-open it.
