### ISSUE TITLE
Next-gen Protocol (ngspades)

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#222]
Concepts: vehicle (simulated with physics engine), double weapon slots, deployable weapons, better movements, (maybe?) larger maps, more players, high-performance server, user authentication, and better networking. Take [public input](http://buildandshoot.com/viewtopic.php?f=57&t=7086).

Issues: how to create server? Derive from pyspades? Or create from full-scratch?

**Comment by Chameleonhider** [comment]
Anyways, this conversation is way too premature until the entire community gets on board with OS and dumps voxlap 0.75. That won't happen until OS runs on everyone's machine like 0.75 does now.

^ True. Besides, quite a part of original game's spirit is the "dirty" look of it's software renderer, compare to eyecandy that OS is...
