### ISSUE TITLE
0.76 support needs a drop-down menu

### ISSUE THREAD

**Issue by iamgreaser** [yvt/openspades#24]
0.76 is supported but it's tucked away in the Advanced Settings section (cg_protocolVersion). Perhaps a Version Selection dropdown would be good?

**Comment by feikname** [comment]
Currently, in 0.012b and the latest build of 0.1.0, there is a toggle for that, it works similiar to the dropdown suggestion. You can select for 0.75 only, 0.76 only, or both.
