### ISSUE TITLE
First person mode in spectator

### ISSUE THREAD

**Issue by noway421** [yvt/openspades#247]
Would be awesome to have this! This feature already was in Vanilla version. It was added only in Ace of Spades 0.76, and not many people know about it. 
Though it's very useful for watching after players.

**Comment by pandaro** [comment]
is possible to close this issues?
@ivt

**Comment by noway421** [comment]
Well, it's actually implemented now, so yes.

**Comment by pielover88888** [comment]
Based on the source it seems that it should be implemented and is activated with the default button for Jumping, but I'm unable to get it to work. I've done this with the seemingly-unrelated cg_thirdperson set to 0 and to 1, doesn't seem to affect it. Any idea on how to trigger it?

**Comment by Rootmars** [comment]
It works for me. Are you sure you're using the latest build?

**Comment by pielover88888** [comment]
I'm using the latest release, and also tested it in v0.0.11, it doesn't work on Windows at the moment. A friend of mine on Ubuntu and made a [demonstration of it working](https://streamable.com/04wf)
