### ISSUE TITLE
Blocks restocking works not properly in /god mode

### ISSUE THREAD

**Issue by noway** [yvt/openspades#254]
When placing single block it set your block count to 49 blocks.
When placing line of blocks, it set your block count to (50 - placed_blocks) blocks.
Though in vanilla it always set your block count straight to 50 blocks.

Pretty annoying when you trying to build something.

**Comment by feikname** [comment]
I almost sure this issue is still valid.

**Comment by VelocityRa** [comment]
How do you access "/god mode"?

**Comment by noway421** [comment]
some of the pyspades scripts, build.py may be

**Comment by feikname** [comment]
Some hallway servers have this script enabled for everyone too.

**Comment by yvt** [comment]
pyspades provides a built-in support for `/god`, but you need to log in as an admin before using it.

**Comment by feikname** [comment]
@yvt Use one of the default admin passwords, if its a untouched installation.

`adminpass1`, `adminpass2` or `adminpass3` are the default ones.
