### ISSUE TITLE
Fatal Error on Linux

### ISSUE THREAD

**Issue by phil568622** [yvt/openspades#259]
Im on Linux Mint 16, 64 bit
compiling and installing worked perfectly with the commands provided in the readme...
but when I want to start openspades, im getting this error

![bildschirmfoto vom 2014-04-23 13 39 52](https://cloud.githubusercontent.com/assets/7383517/2776927/82b1c04c-cadc-11e3-895c-5b54f4a8582d.png)

Please help

**Comment by NotAFile** [comment]
I have done the following:
  reinstalled libpng12-dev
  purged libpng12-dev
  recompiled SDL_image
  recompiled openspades

but the error persists (on debian jessie)

**Comment by phil568622** [comment]
Holy F..., last response to this Issue was 9 Months ago^^

**Comment by NotAFile** [comment]
yes, but I would rather do this than open a new issue

**Comment by NotAFile** [comment]
any more progress/solutions for this? It still persists and is an issue for many people.

**Comment by phil568622** [comment]
I dont think so

Answer pls @noway421

I moved away from Linux ~1 Year ago :/

**Comment by NickBurrill** [comment]
Try this: http://anthony-zhang.me/blog/build-openspades/

There is a pre compiled .deb that might work

**Comment by Uberi** [comment]
In particular, this part of the article:

> "SDL_Image" needs to be configured with the `--disable-png-shared option.

Is important; without it the PNG library won't work.

I also added a bash script to that blog post to download and install everything automatically. Simply download the script, run it, and it will do the rest!

**Comment by phil568622** [comment]
Thanks for that fix, I can finally close this Issue after 2 Years :p

**Comment by NotAFile** [comment]
@phil568622 We should update the README.md and the wiki to reflect the solution instead of just closing this. Will send PR unless somebody with write access can quickly put this in.

**Comment by NotAFile** [comment]
Also, adding --disable-png-shared has not solved my problem. Please Reopen.

Error message is also slightly different for me so I will upload that.
![openspadeserror](https://cloud.githubusercontent.com/assets/5447747/9824620/598cf412-58ce-11e5-96de-3d3ec21a1dca.png)

```
2015/09/11 21:49:27 [Strings.cpp:938] Fetching catalog file (locale='', domain='openspades')
2015/09/11 21:49:27 [Strings.cpp:944] Catalog file 'Locales//openspades.po' not loaded: File not found: Locales//openspades.po
at /home/notafile/build/OpenSpades/openspades/Sources/Core/FileManager.cpp:39
static spades::IStream* spades::FileManager::OpenForReading(const char*) at FileManager.cpp:32
static std::__cxx11::string spades::FileManager::ReadAllBytes(const char*) at FileManager.cpp:91
std::shared_ptr<spades::CatalogOfLanguage> spades::CatalogDomain::operator[](const string&) at Strings.cpp:932
std::shared_ptr<spades::CatalogOfLanguage> spades::GetCatalogOfLanguage(const string&) at Strings.cpp:1002
std::__cxx11::string spades::GetTextRaw(const string&, const string&, const string&, int) at Strings.cpp:1018

2015/09/11 21:49:27 [Main.cpp:637] [!] Terminating due to the fatal error: No bitmap codec could load file successfully: [stream]
SDL_image Image Reader:
IMG_Load_RW failed: JPEG loading error
at /home/notafile/build/OpenSpades/openspades/Sources/Core/SdlImageReader.cpp:124
virtual spades::Bitmap* spades::SdlImageReader::Load(spades::IStream*) at SdlImageReader.cpp:43
int main(int, char**) at Main.cpp:369


Quake 3 Derived Targa Importer:
LoadTGA: Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported
at /home/notafile/build/OpenSpades/openspades/Sources/Core/TargaReader.cpp:119
virtual spades::Bitmap* spades::TargaReader::Load(spades::IStream*) at TargaReader.cpp:60
int main(int, char**) at Main.cpp:369

at /home/notafile/build/OpenSpades/openspades/Sources/Core/Bitmap.cpp:116
int main(int, char**) at Main.cpp:369
```

**Comment by noway421** [comment]
`--disable-shared-png` workaround described here: https://github.com/yvt/openspades/issues/252 and in the [FAQ](https://github.com/yvt/openspades/wiki/Playing-FAQ)

What is the issue with locale?

**Comment by NotAFile** [comment]
no Idea, it seems this is not the issue anyway, as it is a standard error that pops up even if the game sucessfully runs on windows.
