### ISSUE TITLE
Small lag due to muzzel flash 0.0.11

### ISSUE THREAD

**Issue by EvanFireheart** [yvt/openspades#270]
System specs:
OpenGL-capable graphics accelerator is available.
Vendor: ATI Technologies Inc.
Name: AMD Radeon HD 7800 Series
Version: 4.3.12618 Compatibility Profile Context 13.251.0.0
GLSL Version: 4.30

Max Texture Size: 16384
Max 3D Texture Size: 2048
Max Combined Texture Image Units: 32
Max Vertex Texture Image Units: 32
Max Varying Components: 128

Your video card supports all required OpenGL extensions/features.

Problem:
Every time I shoot a gun I get a small frame drop to 0 fps and I believe it is due to muzzle flash but I can't be sure, no errors just frame drops. The SMG is unusable for me. I have tried lowering all settings but nothing works. Also have the same issues with my 2010 Mac All-in-one.

**Comment by yvt** [comment]
This is very old, open a new issue if the problem's still present.
