### ISSUE TITLE
Sometimes screen appearing with black rectangles

### ISSUE THREAD

**Issue by noway421** [yvt/openspades#273]
Due to some glitches sometimes this happens. Here is screenshot:
![shot0294](https://cloud.githubusercontent.com/assets/2031472/2914006/b1060dae-d694-11e3-8f41-9fa1ed6def10.png)
It's stay like this until spawn. After spawn everything is okay, though.

**Comment by VelocityRa** [comment]
This is very old and I've never seen this, open a new issue if the problem's still present.
