### ISSUE TITLE
failed to dlload libopenal.so

### ISSUE THREAD

**Issue by geekybedouin** [yvt/openspades#300]
after picking preferences. this shows up.. file is missing.. 

although I have libopenal1 installed with all dependencies.

**Comment by Tapmemer** [comment]
sudo apt-get libopenal-dev(dev package for linux)
or
sudo apt-get libopenal

**Comment by VelocityRa** [comment]
This is fixed by copying `libopenal1` to `libopenal` so that it's recognised by the game.

**Comment by yvt** [comment]
No longer required to copy `libopenal.so.1`to `libopenal.so` as of 785d62d1f858ca80d176a1536482819e281dd8d2.

**Comment by Tapmemer** [comment]
For some linux users (like me) libopenal.so.1 wasnt even present
