### ISSUE TITLE
visible players connections number on arrow on minimapp

### ISSUE THREAD

**Issue by pandaro** [yvt/openspades#303]
Assign a number to each player (as is openspades) and this number is written on the arrow on the player on the minimap, just like on the shirt of a football player.
When I look at the minimap immediately understand what my teammate occupies a certain position.
I think this is useful for example to be able to warn of danger, or to suggest a strategy. Or just to insult him a little, well, just for fun :)

**Comment by pandaro** [comment]
I went to look in the source code as is drawn to the minimap. I found inside "MapView.cpp" a part of interesting code.
It 's true, you can not write over Player.png the connection id.
But it would be possible to create something functional easily.

for (int i = 0; i <World-> GetNumPlayerSlots (); i ++) {
             Player * p = World-> GetPlayer (i);                
}
Through this we would have a connection id.
Saving 32 colorful icons in Gfx / Map / these could be linked to an id. So you might have a specific icon for each connected client.

**Comment by Chameleonhider** [comment]
yvt, vanilla client can shoot >135 blocks, while OS can 128. Why is that so then? Also they've got tracers on their minimap, we don't. We have dynamic lights, they don't. OS isn't really resembling vanilla, eh?

**Comment by pandaro** [comment]
i think this issues can be close
@ivt
i think have tracer on minimap is not impossible
@Chameleonhider
