### ISSUE TITLE
Suggestions for ngspades features

### ISSUE THREAD

**Issue by zouloum** [yvt/openspades#308]
Hi, I have a few suggestions for the ngspades protocol/server. I'm not sure if this is the right place to post this.

-Server based fog distance:
  Right now, the fog distance is very short and being able to modify it based on server/map would be nice.

-Server based loadouts:
  The server could decide how much ammo you can have. Or what weapons you can use on a particular match (map)

-Screenshot system:
 A system that would take screenshots periodically or on server demand to identify wall hacks. This info could be used when a player is suspected of cheating.

-Movement statistics:
  A system that would try to identify whether a player is using an aimbot by measuring the speed of acquisition of targets. In other words, if the cross-hair moves way too fast from a position X to the target, we could determine if an aimbot is used. By measuring this it could also be possible to determine if someone is using a no recoil hack.

-Networked lighting effects: Being able to spot enemies with their flashlights and be able to blind people with them.

**Comment by feikname** [comment]
Closing this because Next-gen protocol development is abandoned for now.
