### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by nuclearsubstation** [yvt/openspades#310]
I'm missing fonts for OpenSpades whenever I launch. I don't get any errors.. Just no text at all.
I really want to use this, but this bug makes it a pain to configure!
Arch x64

**Comment by yvt** [comment]
Does this issue still persist in the latest version?

**Comment by feikname** [comment]
@nuclearsubstation I will close this thread.

You can reopen it if you're still interested in running OpenSpades in arch and solving this problem.
