### ISSUE TITLE
Users can reload their weapon without pausing their fire

### ISSUE THREAD

**Issue by SK83RJOSH** [yvt/openspades#313]
To recreate this do the following:
- Start firing the SMG
- Reload 3/4 of the way through the clip
- Use the quick swap key to switch to another item and switch back again
- Continue firing
- Clip will replenish itself
- Repeat

**Comment by someoneigna** [comment]
Was able to cancel reload when swapping weapons. Now I need to find a way to cancel the reload sound.

**Comment by VelocityRa** [comment]
Main issue is fixed so this should close. Sound bug can be another Issue.
