### ISSUE TITLE
Users can't fire their weapons at all when sprint is held

### ISSUE THREAD

**Issue by SK83RJOSH** [yvt/openspades#314]
This doesn't quite make sense, the expected behavior (and the behavior in the official client) would be that you can fire so long as your character isn't actually sprinting. It's really confusing to not be able to fire despite the fact that my weapon is it's ready position. This is particularly problematic when you crouch and happen to be holding sprint for instance, because you make have crouched momentarily to take a shot.

**Comment by yvt** [comment]
Fixed by #384.
