### ISSUE TITLE
Could not connect to local pysnip server

### ISSUE THREAD

**Issue by evorios** [yvt/openspades#317]
I run pysnip server on my computer and try to connect to it using the following commands:

```
127.0.0.1:32887
openspades.exe aos://16777343:32887

192.168.1.3:32887
openspades.exe aos://50440384:32887
```

But it dont want to work.
Otherwise standart AoS client work perfectly:

```
client.exe -aos://16777343:32887
client.exe -aos://50440384:32887
```

**Comment by yvt** [comment]
Fixed in a7b9909b2e08eeea00c69071a02fbb89dac1e67a. `cg_lastQuickConnectHost` is no longer used to pass the command-line argument to the game client subsystem.
