### ISSUE TITLE
Random crash (Something went horribly wrong)

### ISSUE THREAD

**Issue by TawaterGO** [yvt/openspades#320]
So whenever I join a server I get to play around for a few seconds until I get an error message of the "Something went horribly wrong" type, followed by a dmp file.

https://drive.google.com/file/d/0B7fYXRKobfxQS2V1dnJTWHNLREU/view?usp=sharing

Pls help, thanks in advance! :)

**Comment by VelocityRa** [comment]
This is very old, open a new issue if the problem's still present.
