### ISSUE TITLE
Build issues in Visual Studio 2013

### ISSUE THREAD

**Issue by vvhatever** [yvt/openspades#322]
What did I do wrong? I tried building in Visual Studio Express 2013 with the unmodified master branch of OpenSpades and got these errors. I'm on Windows 8.1
![issues](https://cloud.githubusercontent.com/assets/5368480/4781750/2903dcf2-5cbc-11e4-94ea-7cb0fd1103da.png)

**Comment by nullifiedcat** [comment]
I'm getting these errors too.

**Comment by mzx987** [comment]
I know this seems a bit late, but I am getting errors similar to this. I have Visual Studio Express 2013 and I try to compile the unmodified code of OpenSpades, but to no avail.

**Comment by feikname** [comment]
Can anyone confirm if this issue is still valid?

**Comment by feikname** [comment]
@vvhatever @nullifiedcat @mzx987 The README file was updated with more building instructions, update to *Visual Studio 2015* and try again.

Please open a new issue if you still have poblems with building.
