### ISSUE TITLE
X Session Locks Up

### ISSUE THREAD

**Issue by 2mac** [yvt/openspades#325]
After finally getting the OpenSpades framebuffer to stay loaded for a comprehensible amount of time (#160), I joined a server, and it seems as though it's an amount of time, but it could be some action of mine, which causes my entire X11 session to freeze. I had to kill it from the console to regain control.

I checked `htop` first to discover that OpenSpades was maxing out one of my cores.

I built from 0.0.12 source on Debian Sid.

**Comment by yvt** [comment]
Does the issue still persist in the latest version?

**Comment by 2mac** [comment]
No idea, and it will probably be a while before I get the urge to test it. Honestly it might have been a settings issue on my end. Let's call it closed for now, and I'll reopen if the issue resurfaces.
