### ISSUE TITLE
Building on fedora - cmake can't find glew

### ISSUE THREAD

**Issue by mattwollf** [yvt/openspades#330]
I'm trying to build on fedora. I tried taking a stab in the dark with dependencies and did a yum install _glew_ but that still hasn't worked. CMake still says it can't find glew. is there more I have to do to add glew to the path in fedora? I'm not sure how to go about this.

I get this specifically: 

`CMake Error at CMakeLists.txt:31 (message):
  GLEW not found, please install it and make sure CMake can find it (add it
  to the PATH)`

glew-devel packages are already installed through yum.

[CMakeError.log](http://pastebin.com/Hq8h03bY)
[CmakeOutput.log](http://pastebin.com/NBXCeXnW)

**Comment by feikname** [comment]
I am closing this issue because it's old. Please open anew issue if you have any problems compiling the latest version.
