### ISSUE TITLE
Cannot launch game after setup, Failed to dlload 'libopenal.so'

### ISSUE THREAD

**Issue by Davidj361** [yvt/openspades#331]
Here's a log of my SystemMessages.log and I'm currently running ubuntu-gnome 14.10.
http://sprunge.us/PEYj

I compiled and installed as you instructed from your README.md at https://github.com/yvt/openspades.

I open openspades via terminal by 'openspades', the GUI shows for the setup. System Info doesn't show any errors. I start the game and I got a popup box saying:

```
A serious error caused OpenSpades to stop working:
Failed to dlload 'libopenal.so': /usr/local/games//libopenal.so: cannot open shared object file: No such file or directory

See SystemMessages.log for more details.
```

I have libopenal1 installed.

**Comment by Rootmars** [comment]
This didn't cut it for me. What I did is copy and rename it to libopenal.so.

sudo cp /usr/lib/x86_64-linux-gnu/libopenal.so.1 /usr/lib/x86_64-linux-gnu/libopenal.so

**Comment by Le0nX** [comment]
The same for me. Nothing of above worked

**Comment by yvt** [comment]
@Le0nX Is OpenAL installed on your computer?

**Comment by Le0nX** [comment]
Devel packet of OpenAL was the problem. Thx!
