### ISSUE TITLE
Installation on Linux - No rule to make target `install'

### ISSUE THREAD

**Issue by reggie-man** [yvt/openspades#332]
I was following the [Linux installation instructions](https://github.com/yvt/openspades#on-linux) when I got to

> 6. Install openspades:
> 
> `sudo make install`
> 
> **note:** `make install` broken in old releases

When I entered the command, the terminal outputted this:

> make: **\* No rule to make target `install'. Stop.

**Comment by LeonardKoenig** [comment]
Hm, I just yesterday could compile it. But I used the AUR for ArchLinux which allows me to build and install automatically. But the instructions the PKGBUILD has are 'make install'. I'm using latest Arch though.

What is your distribution? Have you cloned the latest git repo or are you using the latest release? (I'm using the git version).

Idk what
> note: make install broken in old releases

should mean: Which releases? Make or openspades?

**Comment by reggie-man** [comment]
My distribution is Xubuntu 14.04. I cloned the repo like it says to in the instructions. I don't really know what that note means.

**Comment by LeonardKoenig** [comment]
The last note was for the devs as I don't know which the "broken" does refer to ;-)

Do you have the complete devel packages for your distro?

**Comment by pandaro** [comment]
i compile openspades every days under kubuntu 14.04. never problem
If you compile in the local without errors "sudo make install" is not necessary.
you just open a terminal, navigate to the folder where you installed openspades
/openspades/openspades.mk/bin
then simply type:
./openspades
is all

**Comment by VelocityRa** [comment]
Is the problem still present? Does @pandaro's solution work?

**Comment by feikname** [comment]
Compilation is working fine on my Xubuntu 16.10, please open a new issue if you still have problems.
