### ISSUE TITLE
Strange behavior in Debian Sid amd64

### ISSUE THREAD

**Issue by 2mac** [yvt/openspades#333]
I have tried compiling from both Git and from version 0.0.12 successfully. I can run the game and join a server and play for as long as I like. That is, until I have to fight back.

As soon as I pull the trigger, I hear the sound of my shot, and then everything freezes. I was able to get around that by wiping my config.

Persisting is an issue where names don't show up in status messages. In chat, player names appear file, but if I were to kill or be killed, the status at the top shows all but the name, and same goes for status messages that appear in the chat area such as players joining and leaving the game. It's not game-breaking necessarily, but I'd like to be able to tell who got whose intel or get the current score.

**Comment by theunknownxy** [comment]
1. Sounds like you enabled the hit test debugging option.
2. Pull the latest changes from the git repo, this should be fixed.
