### ISSUE TITLE
Too many possibilities of customization - serious

### ISSUE THREAD

**Issue by Chameleonhider** [yvt/openspades#334]
Setting depthHack to other value than false results in asp.
Don't mention this in changelog. Delete this issue.

**Comment by Chameleonhider** [comment]
Let me specify it a lot better:
Go to "\OpenSpades-0.0.12b-Windows\Resources\Scripts\Skin\GUN\ThirdPerson.as" (open it)
Now copy this line:
"param.depthHack = true;"
Paste it before this line:
"renderer.AddModel(model, param);"

You have esp. How much publicity should this issue get before anyone decides to fix it?

**Comment by yvt** [comment]
Fixed.
