### ISSUE TITLE
Controls in setup

### ISSUE THREAD

**Issue by CakeFacee** [yvt/openspades#338]
Controls in setup went weird. I wanna restore controls to default but cant. Tried reinstalling. How to make controlls and all other setting default???

**Comment by pandaro** [comment]
win or apple orlinux?

**Comment by CakeFacee** [comment]
win

**Comment by CakeFacee** [comment]
I think you go and delete the files in roaming or somthing like that. Ima go do that now.

**Comment by CakeFacee** [comment]
Yes, it worked. %APPDATA% Into the search bar and found roaming files. Deleted open spades files and reinstalled.
