### ISSUE TITLE
Global Illumination is Super Slow

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#34]
Global Illumination (`r_radiosity`) works perfectly and fast on MacBook Air (Mid 2012, Intel HD Graphics 4000), but not on others.

Radiosity rendering is done as following:
1. Computation is done in background by CPU, for 512x512x64 grid points. 
2. The computation result is streamed into GPU using glTexSubImage3D (each call transfers 16x16x16 block)
3. Shader (Shadow/MapRadiosity.fs) samples this and calculates the final value for every visible solid pixels.

The problem is that the step 2 sometimes takes too much time. Even only one glTexSubImage3D call took 300ms on some computers. 

Using PBO had no effects.

**Comment by feikname** [comment]
@yvt can this be closed?
