### ISSUE TITLE
Outdated Server List

### ISSUE THREAD

**Issue by ghost** [yvt/openspades#345]
Hi,
I found out that sometimes when I try to connect to Arena server and there are 22/32 players already are playing I get message "Server full". This happens every time I guess when there is such match of players already playing on the server and it's full capacity. I don't know what it's related to, whether it's related to flawed counter function (and it somehow miscounts decades, it gets 22 for 32) or may be it shows wrong amount of players currently playing the game.
![cs_milita](https://cloud.githubusercontent.com/assets/10925582/6109641/562e7b2c-b08d-11e4-9605-33136a067795.png)
On attached screenshot you can see that I've tried to connect to cs_militia server and get the message

**Comment by AOSCracker** [comment]
Addition. I think the counter is hung up. Because when I connect to the server there are more people are playing. And it seems that message is legit. But information on the server list is outdated (wrong).

**Comment by Booboorocks998** [comment]
Does refreshing solve the problem?

If it does then I'm not sure that this is really an issue.  That's what the refresh button is for.

**Comment by AOSCracker** [comment]
No, Refresh doesn't solve it. But I get that this is not a problem with counter function or something. It's simply brings outdated server list (outdated information about all servers not just particular one). After pressing "Refresh" it still brings outdated server list (basicly all information is outdated concerning all servers). It solves itself after some time but for awhile information is kinda stuck on the server list. It's still stuck after restarting the game. Even if I repeatedly restart it a bunch of times. It's like floating problem. It doesn't occur every single time I run the game.

**Comment by feikname** [comment]
It was probably a problem with the master server list.
