### ISSUE TITLE
Not enough render distance

### ISSUE THREAD

**Issue by ghost** [yvt/openspades#347]
Hi !
The main issue I have with OpenSpade is that you can't set your own render distance value. The default value seems much closer to me than the classic one, making it very difficult compared to see from a distance and compete with the other players who can see you better. :(

**Comment by noway421** [comment]
Hm, as far as i know disabling some graphics effects actually could help this issue. Can't recall exact set of settings though.

**Comment by yvt** [comment]
"Volumetric Fog" (`r_fogShadow`) reduces the effective render distance. Furthermore, it interferes with water reflection effect, so I recommend to disable it.

**Comment by Phanthomphax** [comment]
I think it would be fair to see the same render distance for Openspades users, but it definitely sucks that the Ace of Spades get more render distance.

Because Ace of Spades is less laggy?

**Comment by yvt** [comment]
The equation used to compute the fog density has been updated in the commit 4047b61, and the rendering distance now should be the same as the original client. Please reopen the issue if the problem persists.
