### ISSUE TITLE
First person view in spectator mode lacks weapon sight

### ISSUE THREAD

**Issue by noway** [yvt/openspades#348]
It would be pretty nice to have weapon sight in spectator mode too. Right now you can't say for sure where player you are spectating on aiming. And rendered weapon sight on screen would be actually very convenient for determining that.

**Comment by Tapmemer** [comment]
Yvt could make a variable(or whatever its called) on serverside which recieves an aimpacket (client sending a packet that client aims)
So we could use this line to define if specced player is aiming or not:
if (idk)->IsAiming())
*Code to make spactator see aiming*

**Comment by 10se1ucgo** [comment]
That would require a server protocol change, which requires recompiling Cython modules and redistributing PySnip, and seeing as this community is basically dead that's never going to happen.

**Comment by feikname** [comment]
Yep, unless we somehow revive the community, creating a new protocol version is out of question.

**Comment by Rootmars** [comment]
Someone pulled it off not too long ago. Check this thread in Aloha: http://aloha.pk/index.php?topic=8558.0

**Comment by noway421** [comment]
Oh, that's interesting. So such packet which determines whether the player is aiming or not is being sent currently?

Must be that beta and OS are just discarding this packet.

**Comment by Rootmars** [comment]
Oh, I was editing my post while you responded.

**Comment by 10se1ucgo** [comment]
He didn't take it down, server had some kernel panic and I don't know if he has backups.

**Comment by Tapmemer** [comment]
aimDownState = 0.f;

Is this usefull?

**Comment by yvt** [comment]
Fixed by #675.
