### ISSUE TITLE
MOUSE LAGG!!!!!!GAME CRASHH!!!!!!!!!!

### ISSUE THREAD

**Issue by PigCop** [yvt/openspades#349]
I dont know why but the game crash almost every time :(. And when it doesnt crash, the mouse is so laggy that i cannot even play it properly. Is this a problem with my graphics or else?

**Comment by PigCop** [comment]
If my graphic is not good enough do i have to install DirectX and OpenGL?

**Comment by noway421** [comment]
Try to disable Hit Detection Debugger. #227

**Comment by Phanthomphax** [comment]
@PigCop is the problem fixed after trying noway421's solution? If not, you could specify your Computer's Specs.
