### ISSUE TITLE
Player shadow.

### ISSUE THREAD

**Issue by dany-on-demand** [yvt/openspades#35]
Would be nice to see a small circle gradient under your feet. Maybe two moving ones, like in True Combat: Elite.

**Comment by yvt** [comment]
Here's a picture of player shadows rendered by SSAO (available since 0.1.1):
![shot0310 copy](https://cloud.githubusercontent.com/assets/5253988/23105250/7640a6b2-f71f-11e6-819d-77a5a36354ec.jpg)
