### ISSUE TITLE
GAME CRASH!!

### ISSUE THREAD

**Issue by HentaiGami** [yvt/openspades#351]
![ass](https://cloud.githubusercontent.com/assets/11655859/6837799/63312040-d383-11e4-98cd-08cc33006654.png)
Every time i try to play this game, i get this crash shit thingy, help pls. also where do i send the fcking DMP File? hope someone helps me i really want to play this game

**Comment by motapc97** [comment]
Try to download and install the lastest version

[https://github.com/yvt/openspades/releases](https://github.com/yvt/openspades/releases)

**Comment by dankzegriefer** [comment]
You post it here.

**Comment by yvt** [comment]
Closing the issue because no response was provided.
