### ISSUE TITLE
On linux, mouse dont work with wine.

### ISSUE THREAD

**Issue by Chocapute** [yvt/openspades#352]
On linux, because my terminal dont recognize my password and when im passing through, the download dont work too, i used Wine. 

Works fine, no crash, just the mouse in-game dont work. Any issue or help for that ? 

Ps: Thank you for remastered Ace of Spades !

**Comment by Brottweiler** [comment]
Why are you using Wine?

**Comment by Chocapute** [comment]
Because i cant download/install the linux version. So i use the windows version with wine.

**Comment by Brottweiler** [comment]
Then it's probably a WIne issue... Why can't you use the Linux version? I use it fine...

**Comment by Chocapute** [comment]
http://image.noelshack.com/fichiers/2015/14/1427711691-capture-d-ecran-30032015-12-33-47.png

All the time, the terminal do that. All the freakin' time ... So i use wine.

**Comment by Brottweiler** [comment]
That has nothing to do with OpenSpades... it  has to do that your account isn't in the sudoers file so you can't use root only commands. Google the error message...

**Comment by Chocapute** [comment]
Ok, thanks.

**Comment by proxa** [comment]
This should probably be closed.
