### ISSUE TITLE
Can't Compile (error: 'isnan' was not declared in this scope)

### ISSUE THREAD

**Issue by R3B3LCAUSE** [yvt/openspades#354]
I am trying to compile OpenSpades on Win7 x64 Home Premium with the MinGW compiler in CodeBlocks. When I attempt to build OpenSpades I get `error: 'isnan' was not declared in this scope` on multiple lines in multiple source files.

**Comment by henriqueleng** [comment]
Got the same now, will look for a fix

**Comment by henriqueleng** [comment]
You should replace isnan() with std::isnan(), at least solved to me. Or fix the headers, <cmath> or <math.h>

**Comment by domenkozar** [comment]
For reference, fix in Nix https://github.com/NixOS/nixpkgs/commit/976657a71f96d9b7cdd09e96c8d1e844a74ce4d5
