### ISSUE TITLE
Game was terminated due to an unexpected error

### ISSUE THREAD

**Issue by joshtemplin3** [yvt/openspades#36]
![openspades](https://f.cloud.github.com/assets/2534161/1061937/fdb15f7c-1214-11e3-87b4-5bd201ae31a5.png)

SystemMessages.log: http://pastebin.com/j5Ec8iMR

**Comment by feikname** [comment]
This issue seems very old and is probably fixed in recent versions, so I am closing this.

Also, the pastebin link is not available anymore.
