### ISSUE TITLE
Make a way to easily reset advanced settings

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#360]
Operating System: Irrelevant
OpenSpades version: 0.0.12b

If someone messes with the advanced tab there's no obvious way to easily reset it. Even though you you can go to _%AppData%_(on Windows) and delete OpenSpades folder, not all users are aware of that possibility. Also, you would be able to mess with the options and easily reset them without the need of restarting the program.

**Comment by Yankwerks** [comment]
Agreed
