### ISSUE TITLE
Openshades Fatal Error

### ISSUE THREAD

**Issue by Mrtrader4** [yvt/openspades#361]
A serious error caused OpenSpades to stop working: Gl function glGenFramebuffers missing see systemmessages.log for more details

What is this and how can it be fixed.

**Comment by callmeStriking** [comment]
AFACT your graphics card cannot run OpenShades (it's missing the Framebuffer extension of OpenGL).

**Comment by NickBurrill** [comment]
Or try updating your graphics drivers.
