### ISSUE TITLE
Map will not load: File Truncated

### ISSUE THREAD

**Issue by TheLoneMilkMan** [yvt/openspades#362]
A specific map of mine does not seem to be loading. I'm not sure what could be causing it. It does not work on 0.0.12b or 0.0.11. I'm getting this

![image](https://cloud.githubusercontent.com/assets/12291289/7510050/33857d92-f466-11e4-9b2f-fc9de4726bb9.png)

**Comment by TheLoneMilkMan** [comment]
Well I found the source of the bug. This specific structure in the map seems to cause openspades to fail. It only happens when this structure is built in the h8 corner of the map and all of the conditions in this picture are met. This is as much info as I was able to gather.

![image](https://cloud.githubusercontent.com/assets/12291289/7528334/4c20bcde-f4f4-11e4-95a4-c534042455db.png)

**Comment by yvt** [comment]
Nice investigation! That'll help us debug the map loading code.

**Comment by yvt** [comment]
Fixed in #830.
