### ISSUE TITLE
No bitmap codec could load file successfully

### ISSUE THREAD

**Issue by allknowingfrog** [yvt/openspades#363]
I followed the Linux installation instructions (Ubuntu 14) and managed to compile openspades, but when I launched it, it threw an error and died. I launched it again through the terminal to grab the output. Any thoughts?

2015/05/16 13:08:51 [Main.cpp:637] [!] Terminating due to the fatal error: No bitmap codec could load file successfully: [stream]
SDL_image Image Reader:
IMG_Init failed: PNG images are not supported
at /home/jeremiah/openspades/Sources/Core/SdlImageReader.cpp:120
virtual spades::Bitmap *spades::SdlImageReader::Load(spades::IStream *) at SdlImageReader.cpp:43
int main(int, char **) at Main.cpp:369

Quake 3 Derived Targa Importer:
LoadTGA: Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported
at /home/jeremiah/openspades/Sources/Core/TargaReader.cpp:119
virtual spades::Bitmap *spades::TargaReader::Load(spades::IStream *) at TargaReader.cpp:60
int main(int, char **) at Main.cpp:369

at /home/jeremiah/openspades/Sources/Core/Bitmap.cpp:116
int main(int, char **) at Main.cpp:369

**Comment by thedansimonson** [comment]
Exact same error here on Xubuntu 14.

**Comment by theunknownxy** [comment]
If you have compiled SDL2_image manually, you may have to install the `libpng12-dev` package before compiling and installing SDL2_image.

**Comment by z24** [comment]
Same error here.

**Comment by NotAFile** [comment]
this is solved by adding --disable-shared-libpng when compiling sdl_image. I should really get on with it and send a PR

**Comment by trustable-code** [comment]
Issue should be closed. The fix works for me too.

**Comment by thedansimonson** [comment]
Ditto.
