### ISSUE TITLE
OpenSpades.h missing

### ISSUE THREAD

**Issue by orsobschm** [yvt/openspades#364]
Hello,

first of all let me express my thanks for this amazing project!

We are attempting the installation on MacOS X.10.3. 
We installed OpenSpades according to the instructions found here: https://github.com/yvt/openspades: downloaded OpenSpades build 0.0.12b, the source code and the needed SDL2 development and image libraries. By building it in Xcode 6.3.1 the build fails: missing OpenSpades.h file.
I would appreciate some help in creating this file as expected. 

thank you!
Orso

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by orsobschm** [comment]
Hello, I actually stopped trying, I don't really know if it it's fixed but
it was too complex for me. In the meantime I installed a new Mac OS,
perhaps it works now. I'll try as soon as possible.

Best regards,
Orso

**Comment by noway421** [comment]
Have you run cmake? OpenSpades.h is an autogenerated file

**Comment by yvt** [comment]
CMake is not used during the build process for the macOS version of OpenSpades. `OpenSpades.h` is [included in the source tree](https://github.com/yvt/openspades/blob/master/OpenSpades.h) for this purpose (it wasn't previously).

**Comment by yvt** [comment]
I guess it's okay to close this issue because `OpenSpades.h` now comes with the source code (for macOS build).
