### ISSUE TITLE
No file system is writable

### ISSUE THREAD

**Issue by Animakozak** [yvt/openspades#368]
![image](https://cloud.githubusercontent.com/assets/14003875/9529272/0333cfe6-4d02-11e5-8b4b-2264a1d6dc5f.png)
Set-ups, nick don't save. 
Version 0.0.12b.
System info:
OpenGL-capable graphics accelerator is available.
Vendor: Intel
Name: Intel(R) HD Graphics
Version: 4.0.0 - Build 10.18.10.4252
GLSL Version: 4.00 - Build 10.18.10.4252

Max Texture Size: 16384
Max 3D Texture Size: 2048
Max Combined Texture Image Units: 96
Max Vertex Texture Image Units: 16
Max Varying Components: 64

Your video card supports all required OpenGL extensions/features.

**Comment by Kurtoid** [comment]
Do you have permissions for the directory openspades is in?

**Comment by proxa** [comment]
Yeah, that error seems straightforward.  What directory is openspades running in and what permissions does your user have for that directory?

I'm not on Windows at the moment, but right clicking the openspades folder should yield a tab for permissions.

**Comment by feikname** [comment]
Is that russian version of Windows? if it's not a problem with permissions maybe it's some problem with charsets/encoding, but thats just a random guess.

**Comment by noway421** [comment]
It's ukrainian, but what is more important here is that it's windows 10. Was it even seen to be working on windows 10?
Also, cyrillic symbols in the user directory path indeed may be the issue.

**Comment by Animakozak** [comment]
I am considering such problem, as incompatibility with Windows 10. As for cyrilic, I moved to C drive,  launched as administrator and Windows 7 compability mode - nothing changes

**Comment by noway421** [comment]
Openspades creates directory in your account folder, it is in `Documents and Settings` in user directory or something. This behaviour is independent of installation directory.

**Comment by proxa** [comment]
I was running it on Windows 10 just fine

**Comment by AnaXor1** [comment]
Go to start, run, %appdata% then make a folder there called Openspades and inside that another called Resources

example:
C:\Users\YourUser\AppData\Roaming\Openspades\Resources

**Comment by Phanthomphax** [comment]
Is the game running in administrator mode? Or are you using a administrator account?
In case it is not, run it in administrator mode. In case you aren't using, use a administrator account.

Mostly, I get this error when multiple openspades processes are running, mostly.

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by noway421** [comment]
best guess is that it is non-ascii user name which screws up the %appdata% file path in your windows fs (ntfs or fat whatever it is).

**Comment by VelocityRa** [comment]
Might be, @Animakozak do you have non-ascii characters in your username? If you're not sure post it please.

**Comment by yvt** [comment]
Another instance of this problem was reported in aloha.pk forum.

http://aloha.pk/index.php?topic=9424.msg84817

This reporter has non-ASCII characters in his/her username.

**Comment by yvt** [comment]
Fixed in 0.1.1c.
