### ISSUE TITLE
Some text wont show - Ubuntu Linux

### ISSUE THREAD

**Issue by Kurtoid** [yvt/openspades#371]
Seemingly random text is missing, including scores,player names in large text kill notifications and in chat
![screenshot from 2015-10-20 16 28 57](https://cloud.githubusercontent.com/assets/2405137/10620874/74dfecec-774b-11e5-9a82-26bf8ed0cf12.png)
![screenshot from 2015-10-20 16 28 35](https://cloud.githubusercontent.com/assets/2405137/10620915/981dec72-774b-11e5-9cba-e6c759bed997.png)
![screenshot from 2015-10-20 16 28 41](https://cloud.githubusercontent.com/assets/2405137/10621007/0bc819e0-774c-11e5-8783-89639d989009.png)
![screenshot from 2015-10-20 16 29 36](https://cloud.githubusercontent.com/assets/2405137/10621013/11837ed8-774c-11e5-96d1-d13352480425.png)

**Comment by Kurtoid** [comment]
The respawn countdown timer is missing too. All I get is "You will respawn in:" with no number

**Comment by tmewett** [comment]
I'm getting this same issue, on 0.0.12 built with GCC 5.2.0, SDL 2.0.3, Mesa 11.0.5 (latest as of posting). It seems to be that all variable text is missing, like names/teams in events and also key prompts eg. for reloading.

**Comment by Kurtoid** [comment]
Do you think this is a driver issue or an openspades issue?

**Comment by tmewett** [comment]
I can't see it being a driver issue. There is no error with the visuals, just with the strings being printed. I wonder if all Linux users have this issue?

**Comment by tmewett** [comment]
I've heard that this bug has already been fixed in the repo. Try compiling from the latest revision.

**Comment by Kurtoid** [comment]
Latest code fixes it. 

As a side note, where did you here about that?

**Comment by tmewett** [comment]
From another Arch Linux user

**Comment by noway421** [comment]
The exact same issue already was present here and was fixed. Dunno why it is appearing for you again. The last time it was because of some bug in gcc, and the workaround was to compile it with clang. 

You could try to compile it with clang and see what would happen.

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by Kurtoid** [comment]
Problem Fixed.
