### ISSUE TITLE
Please enable framerate unlocking

### ISSUE THREAD

**Issue by jackson-c** [yvt/openspades#372]
Even with r_vsync set to 0 or -1, the game remains locked at 60 fps and this leads to a very irritating mouse input lag. Also, please make it so the animation when you aim down the sites can be set to be near-instantaneous because otherwise it gives a disadvantage against players using the old client.

**Comment by jackson-c** [comment]
Hm, playing jagex' aos, which is locked to 60 fps as well, and input lag is nowhere near as bad as in this program. Perhaps use "raw mouse input" like many games have a seeing for?

**Comment by theunknownxy** [comment]
Make sure you didn't force vsync in your graphic driver settings.

**Comment by jackson-c** [comment]
I'm not forcing vsync, although it kind of seems like when setting r_vsync to 0 there is still no screen tearing, so I don't know what's going on there. What I do know is that this game has very irritating input lag, which is not an issue in Jagex' AoS even with VSync ON. What a shame, it's so well made otherwise, but the input lag makes it unplayable for me.

**Comment by roboman2444** [comment]
It runs at unlimited framerate for me... Your driver or display server is limiting the framerate.
Try running with environment var vblank_mode=0

**Comment by jackson-c** [comment]
Not exactly sure what you meant by that but I tried running the program with that as a launch parameter and I tried setting an environment variable of the windows system "vblank_mode" to 0. Still capped at 60. I don't have this issue with other programs, so I highly doubt it's my system.

**Comment by noway421** [comment]
vblank_mode=0 is a DRI option (set with env vars), and works only on linux. For other systems, search for vblank or vsync in your gpu driver settings or anything similar.

**Comment by Rootmars** [comment]
If you're using an NVIDIA card, go to the NVIDIA Control Panel > Manage 3D Settings > Global Settings > Vertical Sync and set it to "off". Worked for me. Radeon Catalyst Control Center should have a similar option.

**Comment by HuskyGFX** [comment]
Well, my client runs at 988fps so I think this issue is being causes on your end. Therefore this ticket can be closed since OpenSpades does not limit frame rates.
