### ISSUE TITLE
Weapon clip is nof filled when ammo is replenished

### ISSUE THREAD

**Issue by someoneigna** [yvt/openspades#373]
Is kind of annoying when you go to home to get ammo and your gun is still empty.

**Comment by Chameleonhider** [comment]
This is not an issue.
This is normal behavior of default AoS 0.x client.
Server will send you correct ammo value anyway, so the change will be purely cosmetic.

If you don't care enough to actually test your "fixes", please go away.

**Comment by yvt** [comment]
As @Chameleonhider has said, this is the correct behavior of AoS client.  So I'm sorry but I have to revert your pull request. 

Anyway, thank you for taking your time to send an issue and pull request.
