### ISSUE TITLE
Recently Crashes 

### ISSUE THREAD

**Issue by StrykerPro** [yvt/openspades#377]
## Oops, we crashed...

Something went horribly wrong, please send the file 
C:\Users----NAME----\Desktop\OpenSpadesCrash20526468.dmp
## OK   

Image : 
![image](https://cloud.githubusercontent.com/assets/9895622/11785894/be3273ee-a2be-11e5-8082-7c9f22efdc3d.png)

**Comment by yvt** [comment]
Could you send the file for analysis?

**Comment by Yankwerks** [comment]
Happens to me aswell! Running on an i7 2630QM along a Nvidia Geforce 540M. It used to run the game like a charm but now it just crashes like that. Maybe this is related to windows 10...

[Crash Dumps.zip](https://github.com/yvt/openspades/files/199486/Crash.Dumps.zip)

**Comment by VelocityRa** [comment]
Since Windows 7 compatibility mode fixes this we can close this now.
