### ISSUE TITLE
Sometimes Third person weapon sounds are not played. (local server)

### ISSUE THREAD

**Issue by Chameleonhider** [yvt/openspades#378]
When this bug happens, you hear DryFire clicking instead of normal gunshot sounds.

Recreate:
Launch two clients on same server: one has audio on, other audio off (for convienience)
Select client without sound. Fire full clip within fog range of player, reload.
Walk away more than 128 blocks.
Fire full clip, reload.
Walk closer to player. While shooting/reloading, you cannot hear the sounds.
If you are close enough, you should hear DryFire sound instead.

**Comment by Chameleonhider** [comment]
It seems that for other players, reloading works for up to some distance. Probably fog range.
Beyond fog range it is possible that server doesn't send reloading players.

**Comment by Chameleonhider** [comment]
I'm figuring out how GitHub works.
Then I'll make http://buildandshoot.com/viewtopic.php?f=57&t=13393 opensource.
Then I'll commit some fixes.

**Comment by 10se1ucgo** [comment]
@yvt this guy is literally violating the license, you should probably do something about that.

**Comment by Kurtoid** [comment]
He's making a fork of it in a way, and he gives credit. What part is he
violating?

On Wed, Feb 3, 2016, 4:25 PM 10se1ucgo <notifications@github.com> wrote:

> @yvt <https://github.com/yvt> this guy is literally violating the
> license, you should probably do something about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yvt/openspades/issues/378#issuecomment-179477857>.
>
-- 

~Kurt

**Comment by Chameleonhider** [comment]
10se1ucgo,
I do not like the idea of releasing a literally unfair build. Currently it has like literally 50% spread reduction when stationary and this is wrong, so I am fixing it.
I don't want to make enemies, but it seems that any decision I do is wrong for ya..? Or maybe you literally missed the last two sentences?

**Comment by 10se1ucgo** [comment]
@Kurtoid, he has been releasing builds of this 'fork' for weeks without disclosing the source.

@Chameleonhider You are legally obligated to releasing the source code because of the GPLv3. I don't care what reason you have for not, you still HAVE to.

**Comment by Kurtoid** [comment]
Ah. Sorry I missed that.
