### ISSUE TITLE
Support for OBJ?

### ISSUE THREAD

**Issue by VinnyVicious** [yvt/openspades#382]
Does the renderer support normal 3D objects, or just voxel formats?

**Comment by Chameleonhider** [comment]
Currently supports only .kv6 and .vxl formats.
But since OpenGL draws those using triangles (I believe), it could support 3D objects.

**Comment by VelocityRa** [comment]
Why would it? This is OpenSpades...

**Comment by feikname** [comment]
Can we add the *denied* tag to this? @yvt @VelocityRa

**Comment by VelocityRa** [comment]
I just realized, this is even on the [NOTTODO](https://github.com/yvt/openspades/wiki/NotToDo#decision) list.
Closing this.

**Comment by feikname** [comment]
Nice, we're now down to 80 issues.

**Comment by VelocityRa** [comment]
Yeah I noticed that, yay!
