### ISSUE TITLE
Support for Microsoft Visual Studio 2015

### ISSUE THREAD

**Issue by VelocityRa** [yvt/openspades#385]
It seems peculiar that this project still uses VS 2013.
Pretty much everyone uses 2015, I don't want a 6.5GB download just to be able to build/contribute to the project.
How can I be the first person suggesting this?

**Comment by Chameleonhider** [comment]
It is compatible, but you need libraries compiled with VS 2015 version, 2013 version libraries won't work with VS 2015. I did try compiling and it was fine except issues with '13 libraries being incompatible with VS'15.

**Comment by VelocityRa** [comment]
Yeah, you do need to compile those for yourself apparently, I couldn't find any precompiled .lib files (IIRC it's SDLmain and libcurl that have the problem). I had some problems compiling the former as well. Also in order for it work I had to change a setting in the compiler's settings. 
Maybe I'll upload the libraries needed for VS 2015 and update the readme with instruction for it as well, could save other people using 2015 some time.

**Comment by VelocityRa** [comment]
I can't compile libcurl.lib for the life of me, I'm not gonna waste more time on this.
