### ISSUE TITLE
segfault on OpenBSD

### ISSUE THREAD

**Issue by henriqueleng** [yvt/openspades#387]
There is a while since I'm trying to build openspades on OpenBSD;
I tried the release and the current from git, on both I got this problem.
I built it with gcc 4.9.3

I would attach the build log, if it wasn't a mess.

Another question, do you build openspades on clang or gcc?

the gdb bt:

```
(gdb) run
Starting program: /home/henri/src/openspades/openspades.mk/bin/openspades
Program received signal SIGABRT, Aborted.
0x000018c5a65d589a in thrkill () at <stdin>:2
2       <stdin>: No such file or directory.
        in <stdin>
Current language:  auto; currently asm
(gdb) bt
#0  0x000018c5a65d589a in thrkill () at <stdin>:2
#1  0x000018c5a65d0f59 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x000018c5a3264ef5 in _Unwind_Resume (exc=0x18c62f0f5160) at unwind.inc:238
#3  0x000018c34c818a58 in spades::TargaReader::~TargaReader () from /home/henri/src/openspades/openspades.mk/bin/openspades
#4  0x0000000000000000 in ?? ()
(gdb)
```

**Comment by henriqueleng** [comment]
Maybe it was a path problem, installing the program solves

**Comment by henriqueleng** [comment]
I gotta reopen this, because I just saw that what really solved the problem was when I ran cmake with 
-DCMAKE_BUILD_TYPE=RelWithDebInfo whe I was trying to debug it. Any idea why cmake with -DCMAKE_BUILD_TYPE=Release doesn't works but with -DCMAKE_BUILD_TYPE=RelWithDebInfo do?

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by henriqueleng** [comment]
Ok to close it. The problen is solved. I just have to investigate to see what cmake does different  with each flag and what causes the problem. I open a pull if I see any problem.
