### ISSUE TITLE
Graphics problem

### ISSUE THREAD

**Issue by CaptainToon** [yvt/openspades#392]
Hello everyone! Like most of you here I was attracted to the beauty of OpenSpades after hearing about it. I have been playing AoS 0.75 for a while. When I downloaded OpenSpades 0.0.12b and played I checked the settings and found that my computer could support OpenGL properly, which I've known before. However, when I played I found this problem. 
![screenshot 2](https://cloud.githubusercontent.com/assets/18211965/14205514/485faefe-f83e-11e5-9f1e-587192fc8b4b.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/18211965/14205519/4d6b5b5a-f83e-11e5-8694-92a2312be33a.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/18211965/14205520/4fd292dc-f83e-11e5-829b-0d61b9ad0a7c.png)

The screen is off center when above 800x600 and windowed. I can't play in 1080p or fullscreen properly. Please help me! I really want to play OpenSpades at it's full (my computer) glory! Thank you in advance.

**Comment by pielover88888** [comment]
If you're using a modern version of Windows it may have enabled HiDPI scaling, find openspades.exe, right click, go to Properties, and somewhere in there you should be able to disable that. Hope this help!

**Comment by CaptainToon** [comment]
That certainly helped! Thank you so much!

**Comment by pielover88888** [comment]
Glad I could help! Don't forget to Close the issue :)

**Comment by gustavph** [comment]
until I helped, and it gets in compatibility configuration, on changing high DPI settings / pros BR ou UBGE não vou esquecer né, fica em compatibilidade a configuração, em alterar configurações de DPI alto
