### ISSUE TITLE
Can't reset settings

### ISSUE THREAD

**Issue by Worksr** [yvt/openspades#393]
Some months ago I discovered Open Spades, I played it until one day it crashed, then a few days ago I downloaded from here, and it finally worked! Except I can't switch to fullscreen because I clicked on "skip this screen next time" so, how can you make that screen show up again? I already tried enabled startup window, it  says to quit Open Spades and opening it again to make it show up, but it still doesn't work, any recommendations?

**Comment by Rootmars** [comment]
In the server screen, you should be able to go to "Setup" (on the bottom) > "Misc" > "Enable Startup Window" to re-enable the startup window.

**Comment by yvt** [comment]
Hitting the space bar as soon as the splash screen appears also re-enables the startup window, but only temporarily.

**Comment by Worksr** [comment]
Rootmars, thats the problem, I always start as  a Deuce, and it doesnt work :/ and the splash screen doesnt appear (I think) when I make the space bar thing.

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by VelocityRa** [comment]
> I always start as a Deuce
So settings aren't saved at all?

**Comment by feikname** [comment]
Are you on Windows? if so, please follow these steps 
 * Go to `%AppData%`
 * Right-click the `OpenSpades` folder
   * Click `Properties` 
 * Go to the `Security` tab
 * Post a screenshot of ** your** permissions (just click on your user on the list)

In case the OpenSpades folder wasn't even created, please do the same steps as above, but for the `%AppData%` folder

If you have any issues finding the permissions, please reply here.

**Comment by yvt** [comment]
@Worksr Any updates?

**Comment by feikname** [comment]
@Worksr this issue should be solved by using the new [Portable Mode](https://github.com/yvt/openspades/wiki/Directories#portable-mode-since-011c-windows-only) available since OpenSpades version 0.1.1c.

You just have to create a folder named `UserResources` in the same directory as `openspades.exe`.

Please re-open this issue if you still have problems after doing the workaround presented above.
