### ISSUE TITLE
linux mint 17.3 cinnamon rosa edition erorrs

### ISSUE THREAD

**Issue by Tapmemer** [yvt/openspades#395]
here:
User@Oldcomputer ~ $ openspades
2016/05/17 18:03:33 [Strings.cpp:938] Fetching catalog file (locale='', domain='openspades')
2016/05/17 18:03:33 [Strings.cpp:944] Catalog file 'Locales//openspades.po' not loaded: File not found: Locales//openspades.po
at /home/user/openspades/Sources/Core/FileManager.cpp:39
static spades::IStream *spades::FileManager::OpenForReading(const char *) at FileManager.cpp:32
static std::string spades::FileManager::ReadAllBytes(const char *) at FileManager.cpp:91
std::shared_ptr<CatalogOfLanguage> spades::CatalogDomain::operator[](const std::string &) at Strings.cpp:932
std::shared_ptr<CatalogOfLanguage> spades::GetCatalogOfLanguage(const std::string &) at Strings.cpp:1002
std::string spades::GetTextRaw(const std::string &, const std::string &, const std::string &, int) at Strings.cpp:1018

2016/05/17 18:03:33 [Main.cpp:640] [!] Terminating due to the fatal error: No bitmap codec could load file successfully: [stream]
SDL_image Image Reader:
IMG_Init failed: PNG images are not supported
at /home/user/openspades/Sources/Core/SdlImageReader.cpp:120
virtual spades::Bitmap _spades::SdlImageReader::Load(spades::IStream *) at SdlImageReader.cpp:43
int main(int, char *_) at Main.cpp:372

Quake 3 Derived Targa Importer:
LoadTGA: Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported
at /home/user/openspades/Sources/Core/TargaReader.cpp:119
virtual spades::Bitmap _spades::TargaReader::Load(spades::IStream *) at TargaReader.cpp:60
int main(int, char *_) at Main.cpp:372

at /home/user/openspades/Sources/Core/Bitmap.cpp:116
int main(int, char **) at Main.cpp:372

**Comment by godwhoa** [comment]
Same issue on Ubuntu 16.04 LTS.
```
➜  bin git:(master) ./openspades 
2016/08/08 03:24:24 [Strings.cpp:938] Fetching catalog file (locale='', domain='openspades')
2016/08/08 03:24:24 [Strings.cpp:944] Catalog file 'Locales//openspades.po' not loaded: File not found: Locales//openspades.po
at /home/pacninja/Desktop/Games/openspades/Sources/Core/FileManager.cpp:39
static spades::IStream* spades::FileManager::OpenForReading(const char*) at FileManager.cpp:32
static std::__cxx11::string spades::FileManager::ReadAllBytes(const char*) at FileManager.cpp:91
std::shared_ptr<spades::CatalogOfLanguage> spades::CatalogDomain::operator[](const string&) at Strings.cpp:932
std::shared_ptr<spades::CatalogOfLanguage> spades::GetCatalogOfLanguage(const string&) at Strings.cpp:1002
std::__cxx11::string spades::GetTextRaw(const string&, const string&, const string&, int) at Strings.cpp:1018

2016/08/08 03:24:24 [Main.cpp:640] [!] Terminating due to the fatal error: No bitmap codec could load file successfully: [stream]
SDL_image Image Reader:
IMG_Load_RW failed: JPEG loading error
at /home/pacninja/Desktop/Games/openspades/Sources/Core/SdlImageReader.cpp:124
virtual spades::Bitmap* spades::SdlImageReader::Load(spades::IStream*) at SdlImageReader.cpp:43
int main(int, char**) at Main.cpp:372


Quake 3 Derived Targa Importer:
LoadTGA: Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported
at /home/pacninja/Desktop/Games/openspades/Sources/Core/TargaReader.cpp:119
virtual spades::Bitmap* spades::TargaReader::Load(spades::IStream*) at TargaReader.cpp:60
int main(int, char**) at Main.cpp:372




at /home/pacninja/Desktop/Games/openspades/Sources/Core/Bitmap.cpp:116
int main(int, char**) at Main.cpp:372

➜  bin git:(master) 

```

**Comment by feikname** [comment]
I can confirm the same issue on my Ubuntu 16.04

**Comment by SawasHaxxer** [comment]
The bitmap and targa reader id fixed for me by completely recompiling sdl librarys,

Noe i get an failed to build at least one of the scripts on main.cpp at line 369.
This main.cpp isnt the same as normal openspades.the normal client works

(Client erroring is an optimized client)

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by noway421** [comment]
@godwhoa I believe it is different issue as because it is `IMG_Load_RW failed: JPEG loading error` and not `IMG_Init failed: PNG images are not supported`. Can you file it as another issue please? You can investigate fixing it by trying to recompile SDL_image with different versions of libjpeg. 

As for the topic error, please see #363. Installing `libpng12-dev` and compiling SDL_image with `--disable-shared-libpng` should fix it.

**Comment by godwhoa** [comment]
@noway421 Sorry moved on to Debian since then so can't really test that fix.

**Comment by feikname** [comment]
@Tapmemer can this be closed?

**Comment by Tapmemer** [comment]
the bitmap error is fixed
/closed
