### ISSUE TITLE
Ubuntu: libGLEW shared libraries not being found

### ISSUE THREAD

**Issue by Hephaestos** [yvt/openspades#403]
I'm running Ubuntu 16.04 and this problem started occuring when I updated. When I try to run I get this error

`openspades: error while loading shared libraries: libGLEW.so.1.10: cannot open shared object file: No such file or directory`

I've made sure all the dependencies are up to date and reinstalled libglew-dev.

**Comment by Kurtoid** [comment]
Latest update did this to me too.

**Comment by VelocityRa** [comment]
Is it fixed for you @Hephaestos? Can we close this?

**Comment by Hephaestos** [comment]
Yes, I recompiled and that worked
