### ISSUE TITLE
When is 0.0.13 being released?

### ISSUE THREAD

**Issue by 100best** [yvt/openspades#404]
There has been no release since Jun 23, 2014.

**Comment by yvt** [comment]
[Lots of bugs were fixed and some features were added since the last release](https://github.com/yvt/openspades/compare/v0.0.12...master). Maybe it’s about the time for the next release…

**Comment by feikname** [comment]
@yvt is the next version going to be 0.1.0 or 0.0.13?

**Comment by yvt** [comment]
The next version [is going to be 0.1.0](https://trello.com/c/3CHho5gi/21-upcoming-0-1-0). ETA is this year.

**Comment by YoSSUu** [comment]
Cmon, I have been waiting like since 7 AM :VV

**Comment by feikname** [comment]
@YoSSUu 24 of december was just an estimated guess, I think the release will be around day 30 instead. 

@yvt?

**Comment by YoSSUu** [comment]
Have faith, me.

**Comment by 100best** [comment]
Finally after 2 1/2 years v0.1.0 has been released. :1st_place_medal:

**Comment by yvt** [comment]
After 2 years of hiatus, I'm happy to announce that v0.1.0 has been finally released! Thank you so much for all your support and help for the new release, it couldn't happen without them.
