### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by OUTEASTsama** [yvt/openspades#405]
openspades-0.0.12/Sources/Draw/SWFeatureLevel.h:125:24:error: ‘sqrtf’ was not declared in this scope

**Comment by yvt** [comment]
What compiler are you using?

**Comment by yvt** [comment]
Does replacing `sqrtf` with `std::sqrtf` at [Sources/Draw/SWFeatureLevel.h:126](https://github.com/yvt/openspades/blob/master/Sources/Draw/SWFeatureLevel.h#L126) solve the issue?

**Comment by OUTEASTsama** [comment]
No, it didn't help
error: ‘sqrtf’ is not a member of ‘std’ return 1.f / std::sqrtf(b);

**Comment by yvt** [comment]
Then, does replacing it with `std::sqrt` work?

**Comment by OUTEASTsama** [comment]
Same error
error: ‘sqrt’ is not a member of ‘std’ return 1.f / std::sqrt(b);

**Comment by 10se1ucgo** [comment]
That's weird, `std::sqrt` is defined in the `<cmath>` header, which is already included.

**Comment by OUTEASTsama** [comment]
It wasn't. And openspades compiled after I included it. Thank you!

**Comment by 10se1ucgo** [comment]
Huh, that's odd. Git shows that it's there.
