### ISSUE TITLE
openspades error at scriptmanager

### ISSUE THREAD

**Issue by Tapmemer** [yvt/openspades#406]
Failed to load at least one of the scripts.
at home/username/openspades/Sources/ScriptBindings/ScriptManager.cpp:117
spades::ScriptManager::ScriptManager() at ScriptManager.cpp:78
int main(int, char**) at Main.cpp:369

sudo make install not runned due to lack of sudo

**Comment by 10se1ucgo** [comment]
You'll have to post the error log for the actual script, this is just the C++ error.

**Comment by SawasHaxxer** [comment]
Where is it located in linux?

**Comment by Rootmars** [comment]
It's in HOMEDIR/.local/share/openspades/Resources/SystemMessages.log by default.

**Comment by SawasHaxxer** [comment]
there is no systemmessages.log in there+this is systemmessages.log's message

**Comment by SawasHaxxer** [comment]
You mean the teminals log

**Comment by VelocityRa** [comment]
Can we close this? Is the problem still present?

**Comment by Tapmemer** [comment]
problem is still present but im unable to reach my computer since its broken and i dont have a new one(i am able to use the drives)

**Comment by feikname** [comment]
Just an observation. On a (Ubuntu GNU/Linux) clean build I was having problems to load some scripts at startup too, perhaps it was some cache issue, but after messing up a little with the files and restarting the computer, it worked just fine. Weird.

**Comment by noway421** [comment]
>sudo make install not runned due to lack of sudo

without proper full installation (i.e. `make install`) openspades won't run due to some path difficulties. Please do try it with `make install` by installing sudo for your distro or by using su. The only other way of fixing it is some symlinking voodoo, but that is far more complicated to perform than simply installing it.

**Comment by Tapmemer** [comment]
my terminal tells me there are no flags specified for install.

i have succesfullt builded a openspades build using only make and no sudo

**Comment by noway421** [comment]
Are you in the directory of your compilation? You should be in `openspades/openspades.mk` AFAIK

**Comment by feikname** [comment]
Looks like the build and dependency loading system needs to be investigated and updated in the Wiki. I might do it when I get some free time. Glad to see this repo active again

**Comment by feikname** [comment]
@Tapmemer Did you get it to work?

**Comment by Tapmemer** [comment]
No i still have the angelscript errors

**Comment by feikname** [comment]
What distro are you using?
