### ISSUE TITLE
Bug render kv6 "doubled size or HD" SMG InGame

### ISSUE THREAD

**Issue by Pachecuu** [yvt/openspades#407]
A fix is needed soon :( The gun is rendered bigger than it should in the game, and you can't enjoy the play.

**Comment by yvt** [comment]
If you’re using a gun skin script from older versions of openspades and using a gun model for newer versions at the same time, then you might see double-sized weapons.

**Comment by Pachecuu** [comment]
Can you give me the script download then, please?

**Comment by yvt** [comment]
You can find the latest version of gun skin scripts in `pak010-BaseSkin.pak` contained in [official binary release files](https://github.com/yvt/openspades/releases/tag/v0.0.12).

**Comment by Pachecuu** [comment]
That's the problem, I don't know what to do there to solve the problem

2016-07-11 17:41 GMT+01:00 Tomoaki Kawada <notifications@github.com>:

**Comment by SawasHaxxer** [comment]
Did you edit any main render or render files located in .pak?(main are the .cpp and .h files)

**Comment by Tapmemer** [comment]
It could be a nasty render bug which renders the nostock.kv6(or some) which is double size

**Comment by yvt** [comment]
@Pachecuu Does the issue still persist in the latest version?

**Comment by yvt** [comment]
Closing this since there's no response for two months. Please reopen the issue if the problem persists.
