### ISSUE TITLE
Volumetric fog: rescale the fog density function to match the original one

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#409]

**Comment by HuskyGFX** [comment]
I am curious: Ace Of Spades was never open-source so how do you find out details like this? Just hacking the original client somehow?

**Comment by 10se1ucgo** [comment]
mat^2 reverse engineered the 0.60 protocol a few years ago and created pyspades, the open source Ace of Spades server implementation. That's basically the only source for documentation for the protocol.

**Comment by noway421** [comment]
In one of the antihack scripts (written by Mat IIRC) there was fog distance (range of visibility) which was apparently found by an experiment. That still doesn't tell the the visibility relationship to distance, but it might be just linear given the simplicity of voxlap renderer.

**Comment by noway421** [comment]
>https://github.com/matpow2/pyspades-userscripts/blob/master/aimbot2.py#L86

if not linear then it is most probably quadratic

**Comment by yvt** [comment]
Volumetric Fog Level 2 introduced by #941 resolves this issue. The old implementation will be dropped at some point.
