### ISSUE TITLE
Allow spectators to be displayed on the scoreboard

### ISSUE THREAD

**Issue by 100best** [yvt/openspades#412]
I have noticed that openspades right now does not have something to show spectators like the classic game did.

**Comment by sanchez-k** [comment]
this add-on will be cool

**Comment by Tapmemer** [comment]
This is easily sorted out by showing all ids and name of team 2(specs used to be team 255)

**Comment by 100best** [comment]
What I mean is the classic game had a place to show all spectators.

**Comment by Tapmemer** [comment]
Exactly what i said

**Comment by feikname** [comment]
May I suggest to rename the issue to "Allow spectators to be displayed on the scoreboard"?

**Comment by VelocityRa** [comment]
I'm gonna have a go at this, where do we want spectators placed?

Here's the scoreboard as of now:
![image](https://cloud.githubusercontent.com/assets/6632271/20725181/a8b84802-b679-11e6-8a13-feb208ac513b.png)

I was thinking about listing them on the bottom horizontally? I can make the background taller if need be.

**Comment by feikname** [comment]
just out of curiosity. What happens if there are more players than OpenSpades can display? is there a scrollbar?

**Comment by VelocityRa** [comment]
That height accomodates the max number of players that can be in a team, so no scrollbar necessary.

**Comment by VelocityRa** [comment]
It displays them like so:

![image](https://cloud.githubusercontent.com/assets/6632271/20726362/eb1e00e8-b67d-11e6-86e9-62c5e78dd3f5.png)

**Comment by feikname** [comment]
Ah yeah. I forgot that. Thanks!

**Comment by feikname** [comment]
I like your idea of displaying horizontally. Reminds me of [Team fortress 2 Scoreboard](https://wiki.teamfortress.com/wiki/Scoreboard/pt-br)

**Comment by VelocityRa** [comment]
## Current progress
(they display green team's players for debugging)

![image](https://cloud.githubusercontent.com/assets/6632271/20729692/cabe10d2-b68b-11e6-9152-426635285a54.png)
(using the server's color)


![image](https://cloud.githubusercontent.com/assets/6632271/20729814/52643f5c-b68c-11e6-8e18-7e1c6538842a.png)
(using yellow)

As you can see they align to the center, it's more visually appealing IMO.
Thoughts?
@yvt

**Comment by VelocityRa** [comment]
Here's another one, I improved the center aligning:

![image](https://cloud.githubusercontent.com/assets/6632271/20730440/c62ab73e-b68e-11e6-9f75-a0c3db52dfa3.png)

Currently nothing is done about players cliipping off the sides screen, if there's lots of them.

**Comment by Kurtoid** [comment]
That looks beautiful!

**Comment by Kurtoid** [comment]
Why are a lot of the spectators on playing teams at the same time?

**Comment by VelocityRa** [comment]
Thanks!
I said why in my first post, I display green team's players as spectators for debugging.

**Comment by Kurtoid** [comment]
Whoops. Sorry.

**Comment by VelocityRa** [comment]
@yvt Given [this](https://github.com/yvt/openspades/blob/master/Sources/Client/World.h#L109), I'm not sure what color the spectator text is supposed to have. Does the server send any color (which is stored in `teams[2]`? Or should we hardcode one?

I've cleaned up the code and done some refactoring, I'm waiting on you to commit and push to my branch for you to check it out, if you like the result.

**Comment by feikname** [comment]
@VelocityRa I think the yellow "Spectators" on your last picture looks really great! I vote for keeping in that color

**Comment by feikname** [comment]
Also, It's rare to have a lot of spectators. I think they can go indefinetely to the horizontal and then this gets fixed in 0.1.1

**Comment by yvt** [comment]
That looks great!

Here are some comments:
- Player IDs of spectators needn't be colored. The color is meant for distinguishing each player on the minimap, but spectators aren't shown there.
- I suggest adding a dark background so the player names are readable on white background

**Comment by VelocityRa** [comment]
Thanks! I'll finish this when I get back.
I agree about the background. I'll either extend the black bg already present, only if there are spectators, or create a new one so that a border is visible. I'll probably go for the first method and stick with it if it looks good.

**Comment by feikname** [comment]
@VelocityRa I also suggest adding a `cg_scoreboard_showSpectators` variable for enabling or disabling this feature for now.

**Comment by VelocityRa** [comment]
@feikname Not sure if that should be an option (does it need to)? I'd have to check for it every frame. It's nothing perf wise, but if we can avoid it, it's also less code to write and maintain.
It's better if it's enabled by default in the next release (candidate) too, I'll know sooner if there are any bugs in it :)

## Progress
![image](https://cloud.githubusercontent.com/assets/6632271/20763911/b5948cc8-b734-11e6-8023-907b7042548a.png)

Does this look ok?
Names are white, ids are grey-ish.

**Comment by feikname** [comment]
@VelocityRa oh ok. You're right.

**Comment by feikname** [comment]
Fixed in #466.
