### ISSUE TITLE
Ability to copy text and open urls from the Chat Log GUI

### ISSUE THREAD

**Issue by 100best** [yvt/openspades#417]
I think it would be nice to be able to copy text and make URLs clickable in the Chat Log GUI.

**Comment by feikname** [comment]
**Note**: The workaround for now is to open the game using a terminal window (Command Prompt on Windows) and copy the chat logs from there.

**Comment by Tapmemer** [comment]
There are logs storend in %appdata%/opensperden (.openspades also i think)

**Comment by 100best** [comment]
For me it is stored in ~/.local/share/openspades.

**Comment by Tapmemer** [comment]
For some reason ctrl+c and ctrl+v crash the game (?)

**Comment by feikname** [comment]
@Tapmemer inside the Chat Box? which version?

**Comment by Tapmemer** [comment]
Inside chat box, version 0.0.12B(i know it doesnt help but i dont know the update version)

**Comment by feikname** [comment]
@Tapmemer That's weird, mine works fine. For how long have you been having this problem? 

On a side note, I will add the Snapshots page to Wiki when I get some free time. So people can test if their issue still exists in the latest development version.

**Comment by Tapmemer** [comment]
it happens over every release of openspades

**Comment by feikname** [comment]
@Tapmemer Have faith, now development is active again :)

**Comment by VelocityRa** [comment]
How is this going to get implemented?

**Comment by noway421** [comment]
ability to click urls is somewhat feasible: underscore the piece on hover. get those pieces by parsing using regexes

**Comment by feikname** [comment]
Processing the string before rendering it seems the best option.

Maybe implementing it like Minecraft did would be a good idea, when the user clicks, prompt with 3 options:
 * Copy to clibpboard
 * Open in default browser
 * Cancel

Also, we should only allow http and https to be clicked, for obvious reasons.

**Comment by feikname** [comment]
Perhaps we could make URL's clickable only in a next version too. 

Implementing only the copy-and-paste would already help a lot of users, and allow them to paste the URL in their browser, which seems not so bad.
