### ISSUE TITLE
Squad system improvements

### ISSUE THREAD

**Issue by Vitaspy** [yvt/openspades#421]
The native squad system for open spades is very basic, allowing for squad mates to spawn by you when you die. I'm wondering if there will be a system in the future that is more visual, allowing me to see my squaddies more easily in the game. A simple name in green over their heads would help a lot, I always tend to loose my friends in the midst of battle.

Thanks, love the work you lot put in to this game!

**Comment by Kurtoid** [comment]
The squad system is not implemented by the client at all. Squads only work
on servers with the plugin.

**Comment by feikname** [comment]
@Vitaspy thanks for the suggestion!

This can only be done realiably with a server-side modification, which is planned for the next-gen project. Next-gen development is abandoned for now, so I am closing this issue until it gets back.

Your idea will remain here and be implemented after the next-gen protocol development returns.
