### ISSUE TITLE
[META] Issues need better/more tags.

### ISSUE THREAD

**Issue by VelocityRa** [yvt/openspades#425]
Looking at the Issue tracker, labeled Issues are few and far between.
@yvt I'm willing to categorize them myself, if given the appropriate permissions.

Labeled:

- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Page 4

**Comment by yvt** [comment]
@VelocityRa Thanks for the offer, I just sent a collaboration invitation to you.

**Comment by VelocityRa** [comment]
Cool, I'll get on it when I get back.

**Comment by feikname** [comment]
How about a `discussion` tag?

**Comment by VelocityRa** [comment]
For Issues we'll make *just* for discussion? Because relevant discussion happens in each of our many open Issues already.

**Comment by VelocityRa** [comment]
Not opposed to this btw, if you have something specific in mind do it.

**Comment by feikname** [comment]
I am not very sure either,  but I think they'd be nice for discussion issues only, like what to do on next-gen or "Should we add X feature"

**Comment by VelocityRa** [comment]
Aand we're done here.
Down to 100 issues, nice!
