### ISSUE TITLE
Getting an error on launch with OpenGL

### ISSUE THREAD

**Issue by Bruceforte** [yvt/openspades#426]
My computer is more than strong enough to run this piece of software, judging by how my previous, slower computer was able to run it fine.
![error](https://cloud.githubusercontent.com/assets/23192229/19891834/2a712fc4-a042-11e6-970d-a1ddda1d7a8a.png)

**Comment by feikname** [comment]
Which version are you using, 0.0.12b?

**Comment by Bruceforte** [comment]
I am using 0.0.12b, yes.

**Comment by Danogot516** [comment]
What drivers are you using.I use AMD's Crimson Drivers and got this error for six months, but then I reverted to the old Catalyst Drivers and it worked fine.Try reinstalling or updating your drivers as a whole if that doesn't work.

**Comment by VelocityRa** [comment]
This is probably easily fixable by renaming the filter function, but I don't have a dev env set up so I can't test it.

**Comment by Danogot516** [comment]
So what do we do?

**Comment by yvt** [comment]
Download [the latest version of `Lens.fs`](https://github.com/yvt/openspades/blob/master/Resources/Shaders/PostFilters/Lens.fs) and save it as `Resources/Shaders/PostFilters/Lens.fs` and everything should be fine.

**Comment by Phyllostachys** [comment]
There is also a filter function in PostFilters\CameraBlur.fs:30 but I don't know enough about openspades yet to know if that matters.

**Comment by VelocityRa** [comment]
It doesn't seem to be used anywhere.

**Comment by Phyllostachys** [comment]
Oh! Duh, didn't even think to check if it is actually used in the shader.

**Comment by yvt** [comment]
It’s still an invalid identifier even if it isn’t actually used anywhere. I’ll push a fix soon.

**Comment by VelocityRa** [comment]
Cool, so this should be closed, right?

**Comment by Danogot516** [comment]
I guess so.Bruceforte just needs to download it again and it should work.If it does he should close the thread.

**Comment by iamgreaser** [comment]
Should point this out:

`uniform sampler2D texture;`

`texture` is a reserved keyword in GLSL version 1.30 (GL 3.0) and above. Of course, as there is no `#version` directive, this defaults to 1.10 and thus it's completely fine, unless the people responsible for making your driver completely suck arse and decide that no `#version` directive means use the latest version you can. For example, if they're AMD.

nVidia also completely suck arse but I think they have a workaround for that kind of case.

**Comment by 10se1ucgo** [comment]
It's NVIDIA now boys, The Way It's Meant to be Played(TM). 

side note: ily greaser fam

**Comment by iamgreaser** [comment]
By "the way it's meant to be played", do you mean "the driver works around all our shitty broken slow standards-violating code"?

**Comment by VelocityRa** [comment]
Closing this and opening a new issue for `uniform sampler2D texture;`.
