### ISSUE TITLE
CMake warning: Policy CMP0054 is not set

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#443]
```
CMake Warning (dev) at CMakeLists.txt:71 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by VelocityRa** [comment]
Should I push this to upstream?

**Comment by yvt** [comment]
Yeah

**Comment by feikname** [comment]
@yvt Can I get push access too? I am envious of @VelocityRa powers <.<

Ok, the real reason is because it's easier to submit translation updates instead of opening a pull request for every little change.

**Comment by yvt** [comment]
@feikname Sent you a collaborator invitation. If you ever want to make other kinds of changes, make sure to ask me before pushing it or consider opening a pull request so they can be reviewed before being merged.
