### ISSUE TITLE
open spades fatal error

### ISSUE THREAD

**Issue by fatcatattack** [yvt/openspades#444]
hi last night sum 1 was talking about commands and fog and said try /r_ something for a fog effect so i did didn't like it and turned it off so me being my curious self started typing /r_ then a letter to see what other commands there where to try and boost fps well what happened is i typed /r_i or o and chose 1 that i thing changed graphics it was set to 1 so i tried 2 and 3 they did nothing so i tried 0 to turn it off and that's when my game crashed and hasn't worked since  i've tried deleting all files folder info etc about every version of spades i had including iceball and redownloaded dr dank spades(the version i was using when it happened) i also tried downloading orignal 0.0.12 version and the launcher from build and shoot but nothing worked and all put out the same error so i checked my programs and found nothing there. my thinking was after i delete everything and downloaded a fresh copy of dr danks spades that it would work but no dice so now idk what to do so any help would be appreciated thanks.Fatcatattack ;D 

here's what the terminal was doing while it loaded the game and crashed:

ompiled GLSL program 'Shaders/OptimizedVoxelModel.fs' in 0.475ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/OptimizedVoxelModel.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/OptimizedVoxelModel.vs' in 0.394ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.159ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/OptimizedVoxelModel.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/OptimizedVoxelModel.program' in 5.954ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/OptimizedVoxelModelDynamicLit.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/OptimizedVoxelModelDynamicLit.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/OptimizedVoxelModelDynamicLit.fs' in 0.325ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/OptimizedVoxelModelDynamicLit.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/OptimizedVoxelModelDynamicLit.vs' in 0.321ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.157ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/OptimizedVoxelModelDynamicLit.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/OptimizedVoxelModelDynamicLit.program' in 4.321ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/OptimizedVoxelModelShadowMap.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/OptimizedVoxelModelShadowMap.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/OptimizedVoxelModelShadowMap.fs' in 0.129ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/OptimizedVoxelModelShadowMap.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/OptimizedVoxelModelShadowMap.vs' in 0.231ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.161ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/OptimizedVoxelModelShadowMap.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/OptimizedVoxelModelShadowMap.program' in 1.604ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/Water2.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Water2.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Water2.fs' in 1.459ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Water2.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Water2.vs' in 0.570ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.155ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/Water2.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/Water2.program' in 10.761ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/CameraBlur.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/CameraBlur.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/CameraBlur.fs' in 0.521ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/CameraBlur.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/CameraBlur.vs' in 0.222ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/CameraBlur.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/CameraBlur.program' in 3.351ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/PassThroughConstAlpha.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/PassThroughConstAlpha.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/PassThroughConstAlpha.fs' in 0.168ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/PassThrough.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/PassThrough.vs' in 0.167ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/PassThroughConstAlpha.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/PassThroughConstAlpha.program' in 1.169ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/LensDust.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/LensDust.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/LensDust.fs' in 0.594ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/LensDust.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/LensDust.vs' in 0.251ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/LensDust.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/LensDust.program' in 2.279ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/Lens.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/Lens.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/Lens.fs' in 1.061ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/Lens.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/Lens.vs' in 0.404ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/Lens.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/Lens.program' in 3.280ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/Gauss1D.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/Gauss1D.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/Gauss1D.fs' in 0.323ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/Gauss1D.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/Gauss1D.vs' in 0.295ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/Gauss1D.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/Gauss1D.program' in 1.960ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/LensFlare/Scanner.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/LensFlare/Scanner.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/LensFlare/Scanner.fs' in 0.249ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/LensFlare/Scanner.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/LensFlare/Scanner.vs' in 0.221ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/LensFlare/Scanner.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/LensFlare/Scanner.program' in 1.493ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/LensFlare/Draw.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/LensFlare/Draw.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/LensFlare/Draw.fs' in 0.246ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/LensFlare/Draw.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/LensFlare/Draw.vs' in 0.203ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/LensFlare/Draw.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/LensFlare/Draw.program' in 1.340ms
libpng warning: iCCP: known incorrect sRGB profile
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/PostFilters/FXAA.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/FXAA.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/FXAA.fs' in 0.856ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/PostFilters/FXAA.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/PostFilters/FXAA.vs' in 0.157ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/PostFilters/FXAA.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/PostFilters/FXAA.program' in 3.142ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:214] GLRenderer initialized
2016/11/16 15:30:08 [..\..\Sources\ScriptBindings\ScriptManager.cpp:45] System function (1, 1) : ERR  : Identifier 'MainScreenUI' is not a data type

2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:308] New map loaded; freeing old renderers...
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:323] Creating new renderers...
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:325] Creating Terrain Shadow Map Renderer
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:327] Creating TerrainRenderer
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/BasicBlockTextures.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/BasicBlockTextures.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/BasicBlockTextures.fs' in 0.371ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/BasicBlockTextures.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/BasicBlockTextures.vs' in 0.350ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.168ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/BasicBlockTextures.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/BasicBlockTextures.program' in 5.424ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:88] Loading GLSL program 'Shaders/BasicBlockOutlines.program'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/BasicBlockOutlines.fs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/BasicBlockOutlines.fs' in 0.182ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/BasicBlockOutlines.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/BasicBlockOutlines.vs' in 0.197ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Fog.vs'
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Fog.vs' in 0.161ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgram.cpp:70] Messages for linking program 'Shaders/BasicBlockOutlines.program':
No errors.

2016/11/16 15:30:08 [..\..\Sources\Draw\GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/BasicBlockOutlines.program' in 2.113ms
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:329] Creating Minimap Renderer
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:331] Creating Water Renderer
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:340] Radiosity is disabled
2016/11/16 15:30:08 [..\..\Sources\Draw\GLRenderer.cpp:345] Created
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
WARNING: uniform 'eyeOrigin' not found
WARNING: uniform 'eyeFront' not found
WARNING: uniform 'minLod' not found
WARNING: uniform 'fogDistance' not found
WARNING: uniform 'viewSpaceLight' not found
WARNING: uniform 'detailTexture' not found
2016/11/16 15:30:10 [..\..\Sources\Core\ConcurrentDispatch.cpp:294] Creating 4 dispatch thread(s)
2016/11/16 15:30:10 [..\..\Sources\Draw\GLFramebufferManager.cpp:697] New GLColorBuffer requested (w = 1024, h = 640, ifmt = 0x0068)
2016/11/16 15:30:10 [..\..\Sources\Gui\Runner.cpp:54] [!] Unhandled exception in SDLRunner:
Caught an exception from the application @ [/Gui/MainScreen.as:143,4] void spades::MainScreenUI::RunFrame(float)
at ..\..\Sources\ScriptBindings\ScriptManager.cpp:361
?ExecuteChecked@ScriptContextUtils@spades@@QAEXXZ at ..\..\Sources\ScriptBindings\ScriptManager.cpp:338
?ExecuteChecked@ScriptContextHandle@spades@@QAEXXZ at ..\..\Sources\ScriptBindings\ScriptManager.cpp:277
?RunFrame@MainScreen@gui@spades@@UAEXM@Z at ..\..\Sources\Gui\MainScreen.cpp:234
?Run@SDLRunner@gui@spades@@QAEXHH@Z at ..\..\Sources\Gui\SDLRunner.cpp:414
?Run@Runner@gui@spades@@QAEXXZ at ..\..\Sources\Gui\Runner.cpp:75
?RunProtected@Runner@gui@spades@@QAEXXZ at ..\..\Sources\Gui\Runner.cpp:48
_SDL_main at ..\..\Sources\Gui\Main.cpp:373

and the error window: a serious error caused openspades to stop working.

Caught an exception from the application @ [/gui/mainscreen.as:143,4] void spades::mainscreen::runframe(float)

see systemmessages.log for more details.

**Comment by yvt** [comment]
See the wiki for the way to reset settings: [Config-Variables](https://github.com/yvt/openspades/wiki/Config-Variables)

**Comment by VelocityRa** [comment]
@fatcatattack If your problem is fixed please close the Issue or tell us, so that we will.

**Comment by fatcatattack** [comment]
I can't do it the /VARIABLE_NAME VALUE way because i can't even open spades to change any thing all i get is the loading screen then the error.When the wiki says Startup Configuration Window's "Advanced" i'm not exactly sure what that is i looked at the system configuration app but couldn't find an advanced option or an openspades file i'm running windows 10 if that helps.

**Comment by VelocityRa** [comment]
Click the link again and look at the top. That's the solution to your problem, not the **Variables** category.
It simply tells you to delete the config file.

**Comment by fatcatattack** [comment]
where would the config file be?

**Comment by fatcatattack** [comment]
I looked at the releases page and saw that if you hit space the config window will pop up so i did that and it works. Is there anything i could do with that to help?

**Comment by fatcatattack** [comment]
Ok it seems to be fixed i changed it to run off software instead of opengl and now it works thanks for the help.
