### ISSUE TITLE
Oh, oh ohhhhh, it better

### ISSUE THREAD

**Issue by YoSSUu** [yvt/openspades#446]
Oh, oh, oauhhhhhhhhhhhhhhh! 0.1.0 BETTER BE RELEASED THIS YEAR, OR THIS MONTH
ONE CANNOT SIMPLY PRESS REFRESH ONCE
F5 F5 F5 F5 F5 F5 F5...

**Comment by YoSSUu** [comment]
I will camp here..

**Comment by VelocityRa** [comment]
I wouldn't expect it November.

**Comment by YoSSUu** [comment]
Ok thanks, but I can't wait for it.
