### ISSUE TITLE
include font-unicode.pak for default option & TTF to osfont?

### ISSUE THREAD

**Issue by kmsiapps** [yvt/openspades#449]
![Uploading 제목 없음.png…]()
Korean translation needs font-unicode.pak in the Resource folder, but it is not included for default - it needs to be moved from Official Mods folder - causing the issue that every font says □□□□□. I think it would be better if it is in the Resource folder for default,

Also, it would be nice if there's easier option to make osfont. There's BDFtoOSFont, but It's hard to use it for noobs like me - from finding bdf file to compiling it. Maybe we can convert TTF or OTF to OSFont if it is possible.

**Comment by yvt** [comment]
`font-unifont.pak` will be installed by default in the next release. 

Also, you might want to take a look at #484 😉
