### ISSUE TITLE
Is `Sources/Externals/readme.txt` outdated?

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#451]
There is a mention to 2 files which are not present:
 * `fluid.exe`
* `out.txt`

I compiled OpenSpades just fine without them, so I suppose the mention to them is outdated, is this right?

**Comment by yvt** [comment]
Yeah, neither of them are no longer required as OpenSpades has switched from FLTK.

**Comment by feikname** [comment]
Ok, I will submit a pull request to fix this soon.
