### ISSUE TITLE
Improve Random Number Generation

### ISSUE THREAD

**Issue by VelocityRa** [yvt/openspades#452]
Using `rand()` calls with the modulo operator to limit the range results in terrible quality of generated values. And this is all beside stupid limitations like it usually being 16-bit limited (forcing us to call it more times when needed).
I also didn't find an `srand` call anywhere in the code (so, `srand(1)` is implied), which would suggest that the seed is always the same? Even if that isn't the case, a better and modern alternative exists and should be used instead.
There are some places where better quality randomness could be advantageous, so I'm gonna do it if @yvt is ok with this.
I plan to use C++'s `random` library with the Mersenne twister implementation, seeded by `random_device` (which generates true entropy/randomness).

**Comment by yvt** [comment]
Agreed.
