### ISSUE TITLE
Depth of Field issue: screen is completely black and covers the entire screen unless ADS

### ISSUE THREAD

**Issue by VelocityRa** [yvt/openspades#453]
In the current master, I get this:
![image](https://cloud.githubusercontent.com/assets/6632271/20465244/b1b4bb44-af61-11e6-97a5-7118e9d3cc85.png)

And when I look through the scope, I see the start of the black getting a few meters ahead of me, like so:
![image](https://cloud.githubusercontent.com/assets/6632271/20465254/e1928602-af61-11e6-9313-b5f576e7404f.png)
![image](https://cloud.githubusercontent.com/assets/6632271/20465261/f6d5b660-af61-11e6-880f-028996aef881.png)

As you can see it's completely black.

Server select:
![image](https://cloud.githubusercontent.com/assets/6632271/20465279/3a032986-af62-11e6-8e91-1af89049fe1d.png)

Another thing I noticed is, the black slightly fades away when certain effects are applied on to the screen, like when I'm being shot.

Since a few commits ago I didn't have that problem. @yvt Could it be one of your recent commits that caused this?

**Comment by feikname** [comment]
What settings are you using? I am not having this problem.

**Comment by VelocityRa** [comment]
Tested it in default settings and the problem went away.
Narrowed it down to **Depth of Field** causing the issue.

**Comment by VelocityRa** [comment]
So, *only* the parts that are be affected by the DoF (and some other effects) are rendered correctly, which is weird.

**Comment by theunknownxy** [comment]
You could try to use git bisect to narrow down the commit.

**Comment by VelocityRa** [comment]
Yup I'm doing that

**Comment by VelocityRa** [comment]
Shit I can't reproduce the issue now. I tried my previous config too and it doesn't happen.
Well, I suppose that's good... I'm gonna close this now.

Edit: Seems like the issue was caused by some old local modifications, because it appeared when I did `git stash pop`.
