### ISSUE TITLE
What the prefix for each advanced settings means?

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#454]
This is kind of trivia, but I am really curious and want to add this to the [Wiki](https://github.com/yvt/openspades/wiki/Config-Variables).

My guesses are
 * r: renderer
 * s: sound
 * core: core (duh)

Have no idea what **cg** means

@yvt ?

**Comment by VelocityRa** [comment]
**C**ommand-line ar**g**uments?

Since the cg_ values are `cf_autoConnect`, cg_printHelp` and `cg_printVersion`.

**Comment by feikname** [comment]
Nice, @VelocityRa 

I think you're right, never realized. Thanks!

**Comment by feikname** [comment]
Reopening because there is also cg_bloog, cg_Minimap_* (weirdly in upper case), cg_fov and a lot of others. So I thinks its not command-line args.

**Comment by VelocityRa** [comment]
Ah ok. Not sure then. Miscellaneous settings is my guess, since they are so varied.

**Comment by yvt** [comment]
The naming scheme and the concept of config variables originate from [Q3:A](https://github.com/id-Software/Quake-III-Arena/blob/dbe4ddb10315479fc00086f08e25d968b4b43c49/code/cgame/cg_main.c#L151). So `cg` stands for "client game" and config names starting with `cg_` are usually related to the client-side game logic, while some of them are incorrectly labelled.

**Comment by Tapmemer** [comment]
The cl_ stands for client?

**Comment by yvt** [comment]
Yeah, that's right.

**Comment by feikname** [comment]
Added to [Wiki](https://github.com/yvt/openspades/wiki/Config-Variables).
