### ISSUE TITLE
New portal with server list for OpenSpades

### ISSUE THREAD

**Issue by kuzyn1** [yvt/openspades#459]
Hey!
I want to start a new portal (with my friend) along with server list but only for Open Spades not AoS anymore (I want to run a few servers too).  So I've got few questions:
- Do you agree? (yvt) I'm asking because I want to add ads to the site.
- Where I can change the address of ingame server list? (currently is buildandshoot list?)
- In general, do you support the idea?

**Comment by feikname** [comment]
The ingame server list address can be changed via `cl_serverListUrl` config variable.

The default value is `http://services.buildandshoot.com/serverlist.json`, but you can change to your own url.

The master server list format is very simple JSON and can easily be reverse-engineered, but I am almost sure there is no specification to it. So you'd have to take a peek.

**Comment by kuzyn1** [comment]
@feikname 

Thanks for help with serverlist.

-  I want to separate AoS and OS. The idea is to promote only Open Spades.
- Unfair? Why? I can promise you that I don't want to hmmn steal(?) old players and enthusiasts. I want to expand and promote OS to a new level, to build a new and great community. Also, I want to spend some money on marketing, that's why I wrote about ads on the new site.
- I'm not into programming so I can't help you with it :(

**Comment by feikname** [comment]
@kuzyn1 thinking well, it really doesn't make it unfair. The reason that I mentioned was because I misread your thread, sorry.

For some reason, god only knows why, I tought you asked for a separate server list for OpenSpades-only servers, **inside the game**.

----
Regarding the portal, **you can** create it and run ads on it independent of @yvt 's approval. Some programming and networking knowledge would sure make things a lot easier for you, but maybe you can do it alone with some effort (and money for hosting, of course). Please note you can't violate OpenSpades license, so you should read and understand it first.

In case you're curious those would be the steps
 1. Creating your pysnip/psyspades servers
 2. Making sure only OpenSpades can join them (check the client - pysnip/psyspades)
 3 Creating your own master server list for them
 4. Create the portal
 5. Provide instructions on how to change `cl_serverListUrl` in your portal

Please note I still think this is a bad idea:
 * Many play Ace of Spades (classic) because it's the only thing their PC can run, so OpenSpades is out of question for them. (I can tell from experience, it wont work on older PCs)
 * Many don't even pay atention to the server browser and the forums, I doubt a substantial amount would even realize your portal exists.
 * There are a lot of empty servers already, getting yours to have players is hard

Hope that helps!

**Comment by kuzyn1** [comment]
@feikname 
Thanks for all tips. About cons:

- That's why I want to separate OpenSpades from Ace of Spades.
- Maybe current players don't pay attention, but I want to build a new community with totally new players. 
- But it's still mainly about AoS.

I will leave this issue open for some time, maybe someone wants to reply.

**Comment by 100best** [comment]
I think we should work on making OpenSpades [[1] 100% Free Software](https://www.gnu.org/philosophy/free-sw.html) including (website, master server, server, client, etc). [[2]](https://www.gnu.org/proprietary/)

**Comment by feikname** [comment]
@kuzyn1 I would also advise waiting for [OpenSpades 0.1.0 release](https://trello.com/c/3CHho5gi) before you start to run the servers, because it could cause a greater impression on first-time players with its new features.

**Comment by kuzyn1** [comment]
@100best 
I didn't say that I want money for this. I will just place ads on the portal to gain some money for server hosting (and maybe donations). Everything will remain free.
@feikname 
It will take sometime to prepare everything, maybe 0.1.0 will be online faster than my portal ;D

**Comment by 100best** [comment]
@kuzyn1 The term "Free Software" is not speaking about price but instead of freedom (ex: libre not gratis!).

**Comment by kuzyn1** [comment]
@100best 
So? What's your point?

**Comment by noway421** [comment]
@kyzyn1 that's more of a 'on a related note'

**Comment by VelocityRa** [comment]
@kuzyn1 I'm curious as to how you would reach those "_completely fresh players that didn't know AoS_".
Portals/forums aren't as popular as they used to and on top of that, they're typically used by people that are not only already invested in the subject (already players of OS in this case), but are so more so than average.

I'm all in favour of this if it's gonna get the next-gen protocol train going again, but I'm not sure if a portal is a good approach. Truth is, what is needed first for the next-gen protocol to happen is actual **development**. A new serverlist for OS would be of no use without a shiny new protocol and client to go with it. Thus, IMHO, this is what we should rather be focusing on.

**Comment by kuzyn1** [comment]
@VelocityRa 
What are you talking about? In my country we've got a lot of portals/forums about games and these are places where I want to get some "fresh players" ;)
I think that you all don't understand what I want to do.

I want to create a new portal focused only on OpenSpades. I will also run some servers and get some new players to build a new community around OS. Maybe in the future we will find some great programmers who can contribute to the OS, but for now as I said the goal is to get new players this OS and have fun playing on populated servers.

**Comment by VelocityRa** [comment]
Ah so, expose OS to forums about gaming/games in general? That makes more sense. And I only said that forums aren't as popular they used to, I know they are not dead by any strech.

So I can definitely see the point of having an OS forum.

---
My other main point still stands, however. Especially if you're talking about creating a seperate, OS only serverlist _from the get go_. If we're gonna try and get new players, may as well wait until we have a better protocol. You want a reason for that? Most will simply not try again if they don't like it the first time. If we're going to direct efforts towards this, we have to make it count.

Another reason? This community has been alive for quite a few years now; most _potential_ players already know about it and have stopped playing. Related forums are nearly dead. **What those players want is _new features_, not new servers.** Like others mentioned, the playerbase is dying already. Given on what I said above, I have doubts about how many people you can gather on a _server_, nevermind a _serverlist_.

I appreciate what you're trying to do here and I have the same goals as you do, but doing this _now_ would have no effect, let's focus on the content first. Creating a community won't be as hard if we have something better than the alternatives (protocol-wise) to show for it :)

**Comment by poVoq** [comment]
Is the source-code for the buildanshoot master-server available somewhere?
