### ISSUE TITLE
OpenSpades crashes if `core_locale` is invalid

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#468]
Version: 0.1.0 (development)

Steps to reproduce:
 * Edit `SPConfig.cfg` to have an invalid `core_locale` (one that can't be found or does not exist)
 * Launch OpenSpades
 * It crashes right after loading the splash screen.

Expected behaviour: 
 * Silently ignore the error and load the default strings. OR
 * Show the error and ask to change `core_locale` to an valid one.

Files and logs:
`SPConfig.cfg`, `SystemMessages.log` and a link to the Crash Dump can be found inside [this Gist](https://gist.github.com/feikname/df3d4217f6cc73e800c771bf0348baac).

**Comment by theunknownxy** [comment]
I can't reproduce it on my system. What kind of "invalid" 'core_locale' did you use? Also a backtrace could be useful.

**Comment by feikname** [comment]
I used an inexistent one. I will try to reproduce and provide a backtrace tomorrow.

**Comment by feikname** [comment]
Okay, edited.

**Comment by VelocityRa** [comment]
Here's a callstack (you'll still probably want to repro it yourself if you want to fix it):
![image](https://cloud.githubusercontent.com/assets/6632271/20859377/09a5c33a-b966-11e6-801c-1106194c75dc.png)

I changed the `core_locale` to `pc_cp`, restarted the client, crash occured (read access violation).

**Comment by VelocityRa** [comment]
The bug is [here](https://github.com/VelocityRa/openspades/blob/b75f0c15a0f0490eae508b3e7515fb24fee5ad24/Sources/Core/Strings.cpp#L1188-L1189), I think it's trying to print a string that's not null-terminated:
![image](https://cloud.githubusercontent.com/assets/6632271/20859457/af66a38c-b968-11e6-8dc2-42ce73b44f2e.png)

**Comment by yvt** [comment]
This was the actual cause of the issue:

```diff
 					SPLog("Catalog file for the locale '%s' was not found. (domain='%s')",
-					      domainName.c_str());
+					      currentLocaleRegion.c_str(), domainName.c_str());
```

**Comment by VelocityRa** [comment]
Yup saw that. I'd swear that I checked `domainName` and it was "openspades"...
