### ISSUE TITLE
OpenSpades/Core/CpuID.cpp error while compiling in VS 2017

### ISSUE THREAD

**Issue by Coreveth** [yvt/openspades#473]
I'm getting __cpuid error on line 14 in "OpenSpades/Core/CpuID.cpp" and I have no clue how to fix it, this started happening just after I got VS 2017 and new release of CMake which supports VS 2017 compilers, does anyone know how to fix this?
OpenSpades/Core/CpuID.cpp
http://i.imgur.com/o4kU21A.png

**Comment by feikname** [comment]
VS 2017 is not supported yet. 

Did you compile the External sources for VS2017 or grabbed them from one of the packs included in `Sources/Externals/readme.txt`?

**Comment by Coreveth** [comment]
I grabbed the resources from the readme file, would that make any difference?

**Comment by feikname** [comment]
The external sources are compiled for specific versions of Visual Studio, but I don't think that's your issue.

VS2017 is saying `__cpuid` is not defined, so perhaps it's a missing header, try adding the `<intrin.h>` header. I noticed it's not included.

**Comment by Coreveth** [comment]
That fixed the issue although I'm still getting C3861 "'__cpuid': identifier not found" on line 14

**Comment by feikname** [comment]
Thanks you for reporting this problem! 

I will open a pull request to fix this so the next person trying to compile won't have problems.

**Comment by feikname** [comment]
Fixed in #480
