### ISSUE TITLE
Setting language as "system default" crashes OpenSpades in Windows 10

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#476]
**Version:** 0.1.0 _(development)_
**Operating System:** Windows 10

**Steps to reproduce:**
 * Launch OpenSpades with startup window enable (`cl_startupWindow: 1`)
 * Go to "general" tab
 * Set language as "System Default"
 * Crashes

**Expected behaviour:**
 * Don't display the option for Windows systems, as it seems to be not supported; OR
 * Deal with the error and display it to the user

**Crash dump:**
https://www.dropbox.com/s/cbjj2behh0kasvs/OpenSpadesCrash29057218.dmp?dl=0

**SystemMessages.log:**
I didn't include it because it does not contain any useful information for this issue.

**Additional information:**
 * My environment is Windows 10 with English as default language.

**Comment by yvt** [comment]
<img width="787" alt="screen shot 2016-12-06 at 4 34 19" src="https://cloud.githubusercontent.com/assets/5253988/20899314/469a9e42-bb6d-11e6-9b85-aab85555ac08.png">

According to the debugger message, this might have been caused by a calling convention mismatch.

**Comment by theunknownxy** [comment]
What about declaring GetUserDefaultLocaleName as [__stdcall](https://msdn.microsoft.com/en-us/library/zxk0tw93(v=VS.100).aspx)?
