### ISSUE TITLE
Mouse spinning around under a Wayland session

### ISSUE THREAD

**Issue by 100best** [yvt/openspades#478]
Like in other fps games (ex: Minetest) this bug also effects OpenSpades, this bug causes the mouse to keep spinning around under a Wayland session meaning having to use Xorg for playing OpenSpades.

**Comment by theunknownxy** [comment]
OpenSpades can't do anything to fix this. The support for mouse grabbing in Wayland is really new and you probably have to compile SDL2 from the [trunk](https://hg.libsdl.org/SDL/rev/ee83e0b4a36f) and need to use a recent wayland version.

**Comment by VelocityRa** [comment]
>OpenSpades can't do anything to fix this.
