### ISSUE TITLE
"Browse Config Folder" gives error instead of opening nautilus (Files)

### ISSUE THREAD

**Issue by 100best** [yvt/openspades#482]
I would think that nautilus (Files) should be opened but instead it gives this error,
`An unknown error has occured while opening the config directory.`
also it should be spelled **occurred** instead of **occured**.

**Comment by yvt** [comment]
@100best Can you provide the log output?

**Comment by 100best** [comment]
`sh: xdg-open: command not found`
`2016/12/07 19:41:39 [ShellApi.cpp:95] xdg-open failed with the exit code 127.`
I installed `xdg-utils` and now it works sorry.

**Comment by feikname** [comment]
I am adding the 'docs' tag because it should be mentioned somewhere that the package 'xdg-utils' is required for this feature to work.
