### ISSUE TITLE
Add option to turn off smoke

### ISSUE THREAD

**Issue by YoSSUu** [yvt/openspades#489]
Can you have an option to turn off the smoke, my laptop's a potato.

**Comment by feikname** [comment]
@YoSSUu If you haven't already, go to the *Startup Window*, set `cg_reduceSmoke` as `1` under the *"Advanced"* tab. Altough it won't remove the smoke, it will probably make things run a bit smoother.

**Comment by yvt** [comment]
Also note that `cg_reduceSmoke` will be [removed](https://github.com/yvt/openspades/commit/5e3b41b8ed54ec4fcf0a7418e405beb5764b5454) in the next version ([0.1.0](https://github.com/yvt/openspades/issues/404)) in favor of `cg_particles`, which provides the same functionality but also introduces an option to remove particle effects entirely. It'll be accessible through the preference dialog.
