### ISSUE TITLE
CMAKE: Freetype Path Not Foudn

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [yvt/openspades#495]
Hello, As the title says when I try to create the solution file Cmake informs me that the Path of Freetype (Includes and Libs) does not exist in the Wiki. Nothing is mentioned: could anyone help me?

**Comment by feikname** [comment]
@xXxToxicBlueDustxXx which operating system are you on?

**Comment by xXxToxicBlueDustxXx** [comment]
This PC is Windows 8.1 Pro With Latest Update

When Cloning the Repository Follow the Step by Step Guide Up to where it reaches the "Generate Solution" part That's where I have the problem

**Comment by feikname** [comment]
I am working on a solution right now, freetype2 can be made working by downloading [this pack](http://gnuwin32.sourceforge.net/downlinks/freetype-lib-zip.php) ([source](http://gnuwin32.sourceforge.net/packages/freetype.htm)).

I will search on how to include opuslib right now.

**Comment by yvt** [comment]
The library download link on the wiki seems outdated. You might want to try [that from the latest version of `readme.txt`](https://github.com/yvt/openspades/blob/master/Sources/Externals/readme.txt). After extracting it, you have to delete the CMake cache (File → Delete Cache) before generating the solution again.

**Comment by feikname** [comment]
I was using the outdated VS-Externals, silly me. :P

**Comment by feikname** [comment]
[Wiki[(https://github.com/yvt/openspades/wiki/Building#visual-studio-2015) updated!

**Comment by feikname** [comment]
@xXxToxicBlueDustxXx did you get it to work?

**Comment by xXxToxicBlueDustxXx** [comment]
Yes, Thanks :D
