### ISSUE TITLE
Notofont doesn't seem to be applied on "Spectator" string at scoreboard

### ISSUE THREAD

**Issue by kmsiapps** [yvt/openspades#507]
![shot0000](https://cloud.githubusercontent.com/assets/23615360/21482687/ac110e20-cbba-11e6-965c-793ffd5fb685.jpg)
Yellow text saying "관전자"(means Spectator in Korean) is still with default unicode font, even though I downloaded Notofont. Maybe it would be a bug ;)

**Comment by VelocityRa** [comment]
That's the case because I use the same font that BLUE/GREEN uses above.
It's intended behaviour, so that its font is consistent one used for the teams' titles.

@yvt Do you think that *if* `client->fontManager->GetGuiFont()` is not the default font, we should use that, else fall back to the present one (`client->fontManager->GetSquareDesignFont()`)?

**Comment by VelocityRa** [comment]
@yvt Feedback on this? ^

**Comment by VelocityRa** [comment]
@yvt Yeah that sounds good. I'll get on it.
Where should that check happen though? Can the font be chanced at any point in the game (so I'll need to check every frame), or can I check it before that?

**Comment by yvt** [comment]
@VelocityRa Checking it every frame would be simpler (and is unlikely to break because of future changes), but it's also okay to check it in advance, for example, in the constructor.

**Comment by VelocityRa** [comment]
Apparently I need to compile a font to use it? @kmsiapps can you send me your font so that I can test my fix?

**Comment by kmsiapps** [comment]
@VelocityRa I used default notofont.pak, which is downloadable in Openspades distribute page.
Thanks for the fix :)

**Comment by VelocityRa** [comment]
Without the fix:
![image](https://cloud.githubusercontent.com/assets/6632271/21619474/8326dfbe-d1f8-11e6-942a-0fe707ef4ba1.png)

With fix:
![image](https://cloud.githubusercontent.com/assets/6632271/21619487/8d1b888a-d1f8-11e6-9b72-8fa871078661.png)

I'll push it later.

**Comment by VelocityRa** [comment]
Without fix:
![image](https://cloud.githubusercontent.com/assets/6632271/21619573/f4ef4d02-d1f8-11e6-83cf-52baafcdd472.png)

With fix:
![image](https://cloud.githubusercontent.com/assets/6632271/21619575/f72bedb4-d1f8-11e6-96ff-15acac97d83f.png)

I'll push it later.

Edit: This is from `GetLargeFont`.
![image](https://cloud.githubusercontent.com/assets/6632271/21619600/153c4966-d1f9-11e6-87c3-3d0a62903e89.png)
We don't want that, Notofont isn't applied here right?

**Comment by yvt** [comment]
@VelocityRa Every font except `GetSquareDesignFont` uses the same set of font files. It looks like custom fonts aren't loaded at all.

**Comment by VelocityRa** [comment]
You're right, I got the font to work now:
![image](https://cloud.githubusercontent.com/assets/6632271/21642845/b88ff9fc-d28d-11e6-81d7-4a2f0127e3b2.png)
Opening a PR just in case.

**Comment by VelocityRa** [comment]
Solved with aforementioned PR.
