### ISSUE TITLE
Add debug timing information to show up on screen.

### ISSUE THREAD

**Issue by roboman2444** [yvt/openspades#514]
It would be nice if the debug timing could be drawn on the screen, instead of only in stdout.
Might also be nice to add the option to do it the average of a few frames too, so it doesn't spam.

**Comment by feikname** [comment]
I recommend the Avg. of every second, if its not implemented already

**Comment by noway421** [comment]
If it's debug info of renderer, this is possible to do in xorgs DRI on Linux, for what it's worth. using some option I can't recall

**Comment by noway421** [comment]
>GALLIUM_HUD - draws various information on the screen, like framerate, cpu load, driver statistics, performance counters, etc. Set GALLIUM_HUD=help and run e.g. glxgears for more info

Hope that at least somewhat related

**Comment by VelocityRa** [comment]
@noway421 Unfortunately that's Linux only and only for open-source drivers.
