### ISSUE TITLE
How to add dutch translations?

### ISSUE THREAD

**Issue by Tapmemer** [yvt/openspades#519]
can these be added?

if you explain me how i could add because google translator is a bit off for my language.

**Comment by feikname** [comment]
@Tapmemer There's a simple guide I made some time ago in the [Translation](https://github.com/yvt/openspades/wiki/Translation) page of the Wiki.

**Comment by feikname** [comment]
You will have to download *Git* if you don't have it already.<br> I also recommend reading [this quick tutorial](https://guides.github.com/activities/hello-world/) about *Git*.

 [Fork](https://help.github.com/articles/fork-a-repo/) this repository and then [clone](https://help.github.com/articles/cloning-a-repository/) it in your computer. Then:

1. Open `Resources/Locales/de/openspades.po` with Poedit
2. Click `Catalog` → `Update from POT File` (upper menu)
3. Select `Resources/Locales/pot/openspades.pot` as the *POT File*
4. Click `View` →`Untranslated entries first`
5. Start translating right away ;)

After that, open an terminal in the folder where you cloned your fork of OpenSpades and type the following
```
git add Resources/Locales/de/openspades.po
git commit -m "Update Deutsch translation"
git push
```
This adds your new translations to Git's *Staging Area*, then adds a message for the changes, and then finally submit those changes to your online fork.

After that, you will have to *open a Pull Request*.
1. Navigate to your online fork inside GitHub
2. Click the button saying *Open a pull request*
3. Wait for us to merge your pull request inside the mainstream repository (this one)

**Comment by Tapmemer** [comment]
Poedit? Where am i supposed to get that

**Comment by feikname** [comment]
@Tapmemer [Here](https://poedit.net/)

**Comment by Tapmemer** [comment]
Can i just edit the .po file without poedit and then use the git magic?

**Comment by feikname** [comment]
@Tapmemer Yes, as long as you edit without damaging the file syntax it should be ok.

**Comment by feikname** [comment]
@Tapmemer Ok, you can edit now.

**Comment by Tapmemer** [comment]
im editing and i came across Eject Brass. please explain more about it and ill translate further.

**Comment by feikname** [comment]
@Tapmemer eject brass is an option to display bullet capsules being ejected from the weapon, like this:

![image](https://cloud.githubusercontent.com/assets/4926869/21618720/7e3e0e70-d1d3-11e6-937b-d197283cc70e.png)
([source image](http://smg.photobucket.com/user/RolexBenz190E/media/DSC_0048.jpg.html))

**Comment by Tapmemer** [comment]
i cannot save using poedit. it says Invalid control string

**Comment by Tapmemer** [comment]
ty btw

**Comment by feikname** [comment]
@Tapmemer can you please send a printscreen of the error?

**Comment by Tapmemer** [comment]
i dont think you can make a screenshot on a raspberry pi

**Comment by Tapmemer** [comment]
it errors with this:
Antialias:Enables a technique to improve the appearance of high-contrast edges.\n
\n
MSAA: Performs antialiasing by generating an intermediate high-resolution image. Looks best, but doesn't cope with some settings.\n
\n

translated:
Antialias: Maakt een techniek om het uiterlijk van hoge contrast randen te verbeteren \ n.\ nMSAA: Voert antialiasing door een afbeelding tussenliggende hoge resolutie te genereren.\ N\ nFXAA: Voert antialiasing door het gladstrijken van artefacten als een post-proces | Uit | MSAA 2x | 4x | FXAA.

**Comment by Tapmemer** [comment]
pi@RaspPi:~/openspades $ git commit -m "Update dutch translations"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <pi@RaspPi>) not allowed

**Comment by feikname** [comment]
@Tapmemer lol, I thought Dutch was the same as Deutsch, sorry.
