### ISSUE TITLE
Toggle fullscreen

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#531]
Most games released recently provide a functionality to switch back and forth between fullscreen mode and window mode anytime. It'd be great to have support for this in OpenSpades.

Possibly related to #417, because opening a browser cannot be done reliably in full screen mode.

SDL 2.0 provides a function named [`SDL_SetWindowFullscreen`](https://wiki.libsdl.org/SDL_SetWindowFullscreen), but I'm not sure whether toggling full screen mode is as easy as calling this function. For example, when you're switching to full screen mode, it's possible that the video card doesn't support the current resolution. Unfortunately, SDL's documentation doesn't mention about what happens in this case. Also note that the current code doesn't support a dynamic change of resolution, and doing so would require a massive amount of rewriting.

**Comment by VelocityRa** [comment]
>I'm not sure whether toggling full screen mode is as easy as calling this function. For example, when you're switching to full screen mode, it's possible that the video card doesn't support the current resolution.

If the target resolution isn't supported, it seems like [the resolution is restored](https://github.com/spurious/SDL-mirror/blob/master/src/video/SDL_video.c#L1303-L1309). This is in `SDL_UpdateFullscreenMode`, which gets called in `SDL_SetWindowFullscreen` (basically a wrapper for it).
Still, we won't know for sure untill we try.

>Also note that the current code doesn't support a dynamic change of resolution, and doing so would require a massive amount of rewriting.

So, we don't support that. Just support the switching between fullsreen and windowed.
