### ISSUE TITLE
Strange network protocol issue or something else

### ISSUE THREAD

**Issue by roadapathy** [yvt/openspades#536]
This was an odd error that appeared some months, or maybe a year ago. I'm not sure whether it happens on every server. I thought it was a bug in the specific mod of the server, or that it was just the server, but I don't honestly know-sorry! I update the game pretty often and I have the latest version most of the time. Sorry that I don't have more information. It happens about 90% of the time when switching maps.

![screenshot_2016-12-25_21-30-27](https://cloud.githubusercontent.com/assets/6241235/21751948/9af49aca-d59d-11e6-844d-d21068062e2b.png)

**Comment by feikname** [comment]
@roadapathy Thanks for the bug report! The issue was already reported [here](https://github.com/yvt/openspades/issues/66), so I am marking this one as duplicate. This might be finally fixed in the next version.
