### ISSUE TITLE
OpenSpades Fatal Error

### ISSUE THREAD

**Issue by CarbonCookies** [yvt/openspades#537]
![oserror](https://cloud.githubusercontent.com/assets/24988211/21752404/1fabfd9a-d5cf-11e6-99bb-58ff4cd034fc.png)

**Comment by feikname** [comment]
@CarbonCookies could you please tell me which version are you using?

Also, please publish your SystemMessages.log here so we can get more details.<br>Its localted in `%APPDATA%\OpenSpades\Resources`

**Comment by CarbonCookies** [comment]
http://pastebin.com/KnanXEvj
it's a pretty long file, but the game doesn't even load the startup setup menu
as far as i know,  it's 0.1.0 (the .zip name is "OpenSpades-0.1.0-Windows")

**Comment by feikname** [comment]
I could be wrong, but seems like the program is your avaiable memory.

Try to close all programs and try to run OpenSpades. 

Also, how much memoryavaiable do you have? The minimum recommended is at least 1GB of RAM.

**Comment by CarbonCookies** [comment]
Ok, closing all programs seemed to fix it.
I have 2gb ram, but the problem might be my processor, celeron (dont judge)
anyway, thanks for the help

**Comment by feikname** [comment]
@CarbonCookies No problem 😆 

Feel free to open a new issue if any other problem arrives.
