### ISSUE TITLE
How can I Help? My skills in the comment

### ISSUE THREAD

**Issue by elzeron** [yvt/openspades#540]
Hello! I'm new to the open source community. In fact I've never made a project available in github. Anyway I want to help with this awesome open source game. If AoS wasn't good enough, being open sourced (by scratch) is awesome.

 I don't know  where to begin, or how to help, so I'm  making me available for any project/help needed. 

I'm not very skilled at c++, although I've touched it sometimes, I have good (Not excellent) python skills, and other scripting languages which are not quite mainstream. Also good (not excellent either) Linux system administration skills. Well, I dont know if it's useful but I've also made serveral web-based projects with python, php, javascript, angular, etc

So if there's anything I can be useful I'd be glad to help

Cheers

**Comment by VelocityRa** [comment]
Hello and welcome to OpenSpades!

We welcome new contributors. You could join our piqueserver Slack team (Ace Of Spades/OpenSpades server-related project), but there's an #openspades channel in there. This is mostly for real-time chatting/discussion and doesn't have much traffic, we mostly use GitHub for everything (and [Trello](https://trello.com/c/B1TjYRX0/3-welcome)).

Your first step is to get your development environment set up (being able to compile the current OpenSpades upstream).
What I would recommend then is simply jumping in to the Issue tracker and finding something simple to solve. There's an easy-fix label you could use to filter, but there are potentially other easy issues for new contributors too.

Cheers!

**Comment by elzeron** [comment]
Great! I've already compiled the source on a Debian 8 to be able to play. I'll check the Issue tracker and try to find anything on my noobie-level. If i have any questions regarding to the use of github and it's pull system, could I make them in here?

Regards Emiliano

**Comment by VelocityRa** [comment]
Yup sure, you can.

**Comment by feikname** [comment]
I would also recommend reading the [GitHub workflow guide](https://guides.github.com/introduction/flow/) if you haven't already, it helped me a lot when I first started with GitHub.
