### ISSUE TITLE
OS's SMG recoil seems different from 0.75b's when crouched

### ISSUE THREAD

**Issue by kmsiapps** [yvt/openspades#551]
I conducted some experiments comparing OS's smg recoil and 0.75b's.
I crouched and shot SMG on the block at the same disatnce, but destroyed block's height seems different.

![os](https://cloud.githubusercontent.com/assets/23615360/21962299/d0f0ac86-db65-11e6-92d2-7c0d31049d41.PNG)
// Openspades

![0 75b](https://cloud.githubusercontent.com/assets/23615360/21962300/d0f0d40e-db65-11e6-92e2-ac617f0f77f9.PNG)
//0.75B

![comparison](https://cloud.githubusercontent.com/assets/23615360/21962301/d0f14628-db65-11e6-8546-e177f4f77f99.PNG)
// Comparison (L-OS, R-0.75B)
// OS reached 4-height blocks, but 0.75B only reached 2-height blocks

**Comment by kmsiapps** [comment]
Recorded videos here
[Videos.zip](https://github.com/yvt/openspades/files/706583/Videos.zip)

**Comment by yvt** [comment]
Thank you for the measurement result! So it appears that SMG's recoil is halved (precisely, reduced by 52%, according to [my precise measurement on that recording](https://cloud.githubusercontent.com/assets/5253988/22790272/f85be7be-ef28-11e6-9a69-0219400a6243.png)) if you are crouching. Do you think the same apply for other weapons?

**Comment by kmsiapps** [comment]
@yvt I'll test them tommorrow ;)

**Comment by kmsiapps** [comment]
@yvt 
When standing, OS's recoil seems identical to 0.75's (Rifle and Shotgun, SMG not tested) while it's quite different when crouching. It seems OS doesn't reduce recoil when crouched, cause standing-recoil looks same with crouching-recoil on both weapons.

[Comparison.zip](https://github.com/yvt/openspades/files/765556/Comparison.zip)
(Can be bit inaccurate because of slightly different initial mouse location)

**Comment by yvt** [comment]
@kmsiapps Thank you for the further investigation. I'll push the fix soon.
