### ISSUE TITLE
OS submitted to a couple of websites, is it official?

### ISSUE THREAD

**Issue by kmsiapps** [yvt/openspades#556]
I don't know how to report it, so I post here:

http://gamejolt.com/games/openspades/46984
http://www.indiedb.com/games/openspades
It seems someone submitted OS there as if he created it..

Is it official submit by yvt? If not, is it allowed?

**Comment by feikname** [comment]
@yvt

**Comment by noway421** [comment]
OS has been on these web sites for over a year at this point.

**Comment by VelocityRa** [comment]
@noway421 How does this change anything? @kmsiapps could still be right about them posing as the game's creators. We won't know until @yvt answers.

**Comment by yvt** [comment]
None of them are official.

It appears that the owner of the first one is receiving some ad revenue from it. I don't know about the second one. Both ones are already reported.

On the bright side, they generated some publicity on OpenSpades and also made it appear more active than actually it was on its hiatus. They even made a devlog!

p.s. [This Twitter account](https://twitter.com/openspades) isn't official either.

**Comment by kmsiapps** [comment]
@yvt Thanks for the kind response ;)
