### ISSUE TITLE
Is anyone else having issues with the 1920x1080 resolution settings?

### ISSUE THREAD

**Issue by Rentario** [yvt/openspades#563]
So I have been having a problem with Open Spades 1920x1080 res. Its not fitting my screen properly like its not the right size or something when it is. I have not had this problem with any other game so can someone please help me out?

**Comment by Rootmars** [comment]
Is 1920x1080 your native resolution? 1920x1080 works for me.

If that doesn't work, try windowed for now.

**Comment by Rentario** [comment]
It is my native res, I checked my system specs and what not and when I tried to do windowed mode still didn't fit.

**Comment by yvt** [comment]
Do you have DPI scaling enabled? If that's the case, you might be able to work around this issue by following [these instructions](https://github.com/yvt/openspades/wiki/Common-Issues#screen-is-off-center).

**Comment by Rentario** [comment]
Thank you so much yvt its fixed now thanks to you.
