### ISSUE TITLE
Light reflection with bright fog color

### ISSUE THREAD

**Issue by ordealx** [yvt/openspades#565]
When i join a server with very bright (or white) fog, the light reflection effect become very visible to the point that it looked like my monitor is dirty. I find it a bit distracting, didnt have this problem with 0.0.12b.

![reflection](https://cloud.githubusercontent.com/assets/24881395/22422814/bd3881c0-e6ee-11e6-9c9c-2e50cda555f4.jpg)

**Comment by yvt** [comment]
It's called [bloom](http://monstervine.com/wp-content/uploads/2011/10/Battlefield-3-Screenshot-Bloom.jpg) [effect](http://imgur.com/MS8lCTx), or "Lens Scattering Filter" in OpenSpades. If you don't like it, it can be disabled by unchecking Post-Process → Lens Scattering Filter in the startup config window.
