### ISSUE TITLE
Firing SMG Kills Frames

### ISSUE THREAD

**Issue by Vaasah** [yvt/openspades#568]
I can run OpenSpades on max settings and get ~180fps on average. When I shoot the rifle or shotgun everything is fine. But if I shoot the SMG my frames drop to around 5fps after a few bullets. Help!?

**Comment by feikname** [comment]
This is mentioned in our [Common Issues](https://github.com/yvt/openspades/wiki/Common-Issues) page.

Basically, disable the *Hit Detection Debugger*. If that doesn't work, then also disable the camera blur.

**Comment by Vaasah** [comment]
Thanks!

**Comment by feikname** [comment]
@Vaasah No problem :D
