### ISSUE TITLE
Topic suggestions

### ISSUE THREAD

**Issue by noway** [yvt/openspades#569]
Probably will be the general (hopefully not ongoing) issue about topic suggestions.

(quick ref: [the carnage](https://github.com/blog/2309-introducing-topics))

I suggest to add the topic `ace-of-spades`.

**Comment by yvt** [comment]
Okay, added `ace-of-spades`.

**Comment by noway** [comment]
`multiplayer`
`online`

**Comment by yvt** [comment]
Great

**Comment by noway** [comment]
- [internet](https://github.com/search?q=topic%3Ainternet)
- [linux](https://github.com/search?q=topic%3Alinux)
- [windows](https://github.com/search?q=topic%3Awindows)
- [macos](https://github.com/search?q=topic%3Amacos)
- [multi-platform](https://github.com/search?q=topic%3Amulti-platform)
- [cross-platform](https://github.com/search?q=topic%3Across-platform)
- [cross-platform-game](https://github.com/search?q=topic%3Across-platform-game)
- [multiplayer-game](https://github.com/search?q=topic%3Amultiplayer-game)
- [cmake](https://github.com/search?q=topic%3Acmake)
- [visual-studio](https://github.com/search?q=topic%3Avisual-studio)
- [xcode](https://github.com/search?q=topic%3Axcode)
- [sdl2](https://github.com/search?q=topic%3Asdl2)
- [realtime-games](https://github.com/search?q=topic%3Arealtime-games)
- [realtime](https://github.com/search?q=topic%3Arealtime)
- [action-game](https://github.com/search?q=topic%3Aaction-game)
- [game-engine](https://github.com/search?q=topic%3Agame-engine)
- [renderer](https://github.com/search?q=topic%3Arenderer)
- [graphics](https://github.com/search?q=topic%3Agraphics)
- [network](https://github.com/search?q=topic%3Anetwork)

**Comment by yvt** [comment]
lol

<img width="580" alt="screen shot 2017-02-26 at 17 21 12" src="https://cloud.githubusercontent.com/assets/5253988/23338221/00f01d10-fc48-11e6-8cac-0aef7de29ca8.png">
