### ISSUE TITLE
Merge various forks

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#573]
I noticed browsing aloha.pk that several people have made forks/changes to openspades, but are aparently not familiar enough with git to have these changes merged back into OpenSpades.

We should find these forks and see if there is any merit to merging their changes

one example: https://github.com/Chameleonhider/noleafclover
another one: http://aloha.pk/index.php?topic=8558.0

**Comment by noway** [comment]
they might not have particularly worthy changes though.. so really this is case-by-case specific.
