### ISSUE TITLE
peer-to-peer?

### ISSUE THREAD

**Issue by Tapmemer** [yvt/openspades#578]
can this be planned for a server feature? if we create a peer-to-peer server at bns.com we could use that server to directly connect into somebodys game by sending an link invite or some thing. if openspades comes on steam we could use steams p-2-p server to join eachoter with steam invites. no need for port forwarding just set the server into peer to peer mode and everybody can join (with peer to peer serverlist? click and you go from normal to p2p server list and click on normal to normal). would be nice. peer to peer works great in the game Garry's mod and i never experienced errors with connection.

**Comment by NotAFile** [comment]
- Openspades is just a client. The server part is currently being developed at http://github.com/piqueserver/piqueserver
 - Adding p2p would be very complicated, I presume what you mean are locally hosted games. You can start your own server instance locally and invite your friends to play no problem, there just is no fancy menu options for it. Sauerkraut offers a "custom game" option at sauerkraut.bplaced.net.

**Comment by feikname** [comment]
@Tapmemer OpenSpades very probably is not  coming to Steam (due to copyright and licensing issues)

**Comment by noway** [comment]
Bundling piqueserver with OpenSpades is a good idea though, so that server can be created with a simple GUI dialog box like that happens with CS1.6/CSS/Mullt Theft Auto

**Comment by feikname** [comment]
@Tapmemer 

I see no reasons or benefits of implementing this.

 * We already have server software that can be easily downloaded and run, be it to play in a private party or just as a public server, such as *[PySnip](https://github.com/NateShoffner/PySnip)*, *[piqueserver](https://github.com/piqueserver/piqueserver)* and *[pyspades](https://github.com/infogulch/pyspades)*. There's no real need or any added benefit building a new peer-to-peer version of AoS protocol
 * Port forwarding although troublesome, is pretty easy and fast to do for anyone who did it at least one time before and has a decent router interface
 * There's no way of knowing your current server URI inside game in OpenSpades, which I see as a problem. But if we fix this, than you could just copy-and-paste it to your friend using any communication software you wish (such as WhatsApp web, Discord, etc)
 * The creation of a new protocol (and by consequence, a lot of modifications to OpenSpades) is a lot of work for uncertain benefits,
