### ISSUE TITLE
Masterlist doesnt show on Vista

### ISSUE THREAD

**Issue by Gemynal** [yvt/openspades#579]
http://prntscr.com/echf74

**Comment by NotAFile** [comment]
This seems to be a font rendering issue, as the list is fetched just fine... interesting.

Is this the precompiled version, or did you build it yourself? Logs should be interesting too, since it seems to not load most of the GUI

**Comment by yvt** [comment]
See [this wiki article](https://github.com/yvt/openspades/wiki/User-Resource-Directory) for how to find out the location of the log file. Please use a code snippet sharing service like [GitHub Gist](https://gist.github.com) or [Pastebin](http://pastebin.com) to post it, and refrain from pasting the contents of it directly.

**Comment by Gemynal** [comment]
<script src="https://gist.github.com/Gemynal/c63197328139537ebb8d8b090de3b2e1.js"></script>

**Comment by Gemynal** [comment]
https://gist.github.com/Gemynal/c63197328139537ebb8d8b090de3b2e1

**Comment by yvt** [comment]
Not only texts but also other elements like button backgrounds and borders are disappearing. Checksums of pak files match those of the official package.

It seems like another ATI/AMD driver issue... Can you update the video driver and see if it fixes the problem? 

Related: #113

**Comment by feikname** [comment]
Also, could you please tell us what's your graphics card and your current driver version (the one that's causing the problem)?

This way, the *wiki* can be updated to have this problem mentioned in the [Common Issues](https://github.com/yvt/openspades/wiki/Common-Issues) page for future people who also have this problem.

**Comment by roadapathy** [comment]
Burn Vista. Burn it with fire. Wouldn't Linux run much faster than Vista- AND run Windows apps with Wine-Staging?

**Comment by Gemynal** [comment]
@yvt @feikname I will do as soon as possible, lets say in 2 weeks. How can I see the driver version please?

@roadapathy this is my dad laptop man, I won't do any modification on it without his permission and I don't think he would be okay lol

**Comment by feikname** [comment]
@Gemynal Do you still have interest in solving this issue? If no reply is given in 1 week, I will close this.
