### ISSUE TITLE
Compilation fails at 100%

### ISSUE THREAD

**Issue by ssriram** [yvt/openspades#580]
Compiling openspades [v0.1.0] on my laptop [elementary OS 0.4 Loki (64-bit)] [Dual-Core Intel® Core™2 Duo CPU     P8800  @ 2.66GHz] [Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)]

Compilation fails at 100%

> [100%] Linking CXX executable ../bin/openspades
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSDL2_image.so: undefined reference to `TIFFReadRGBAImage@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSDL2_image.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSDL2_image.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSDL2_image.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSDL2_image.so: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
Sources/CMakeFiles/OpenSpades.dir/build.make:5748: recipe for target 'bin/openspades' failed
make[2]: *** [bin/openspades] Error 1
CMakeFiles/Makefile2:224: recipe for target 'Sources/CMakeFiles/OpenSpades.dir/all' failed
make[1]: *** [Sources/CMakeFiles/OpenSpades.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I see its an issue with linking. Is there a way to overcome this?

**Comment by VelocityRa** [comment]
Update your SDL2

**Comment by yvt** [comment]
Installing libtiff4 by using a command like `sudo apt-get install libtiff4-dev` might fix this (according to [this](https://github.com/BVLC/caffe/issues/1559)).

**Comment by roadapathy** [comment]
That should fix it OR if you didn't compile SDL2_Image with the right options like I did, you'll get this error. SDL2_image holds a lot of the JPEG, PNG, TIFF sort of features that Openspades seems to depend on.

OR, if you compiled it yourself but cmake isn't finding it for whatever reason, same error.

**Comment by ssriram** [comment]
Looks like both SDL and libtiff are installed by default. May be a different version is required?

> $ sudo apt list --installed | egrep "sdl|tiff"
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libsdl-image1.2/xenial,now 1.2.12-5build2 amd64 [installed,automatic]
> libsdl1.2debian/xenial,now 1.2.15+dfsg1-3 amd64 [installed,automatic]
> libsdl2-2.0-0/xenial,now 2.0.4+dfsg1-2ubuntu2 amd64 [installed,automatic]
> libsdl2-dev/xenial,now 2.0.4+dfsg1-2ubuntu2 amd64 [installed]
> libsdl2-image-2.0-0/xenial,now 2.0.1+dfsg-2 amd64 [installed,automatic]
> libsdl2-image-dev/xenial,now 2.0.1+dfsg-2 amd64 [installed]
> libtiff5/xenial,now 4.0.6-1 amd64 [installed]
> libtiff5-dev/xenial,now 4.0.6-1 amd64 [installed]
> libtiffxx5/xenial,now 4.0.6-1 amd64 [installed,automatic]

**Comment by feikname** [comment]
I remember successfully compiling OpenSpades on elementary OS 0.4 some time ago without any need for external downloads, so perhaps it's a missing `apt` dependency.

Please try to run this command and rebuild OpenSpades:

```bash
sudo apt-get install pkg-config libglew-dev libcurl3-openssl-dev libsdl2-dev libsdl2-image-dev libalut-dev xdg-utils libfreetype6-dev libopus-dev libopusfile-dev libjpeg-dev libxinerama-dev libxft-dev
```
Don't forget to `sudo rm -rf /usr/local/share/games/openspades` before doing the `sudo make install` step.

If that still doesn't solve your poblem, read the text below:

Ubuntu [completely dropped libtiff4 support 3 years ago](http://packages.ubuntu.com/search?keywords=libtiff4) in favor of libtiff5 and is now only available using [this .deb package](http://old-releases.ubuntu.com/ubuntu/pool/universe/t/tiff3/libtiff4_3.9.7-2ubuntu1_amd64.deb), as mentioned [here](http://askubuntu.com/questions/449571/dependency-is-not-satisfiable-libtiff4-when-trying-to-install-lightworks-on-ubu). Please try to install this package (using `dpkg`,`gdebi` or any similar tool) and rebuild OpenSpades (again).

**Comment by roadapathy** [comment]
You need the .dev files of SDL2, I believe. If you're compiling Openspades, you need .dev of almost everything- SDL2-2xxxx.dev, SDL2_Image.dev.

**Comment by roadapathy** [comment]
libsdl2-dev libsdl2-image-dev

**Comment by yvt** [comment]
Any update on this?

**Comment by feikname** [comment]
There have been no updated on this issue for 5 months, so I will close it.

@ssriram if the issue still persists, please reopen this issue.
