### ISSUE TITLE
Saturation with certain fog colors

### ISSUE THREAD

**Issue by 1AmYF** [yvt/openspades#584]
Just saw this on Twitter, looks pretty cool somehow but not sure it was intended ;D
https://twitter.com/T0M_smg_noob/status/835719019835502592

I reproduced it for comparison with the previous version, the fog color on that map is RGB(0, 148, 255), similar happens with some other colors too.

**Version 0.1.1:**
![os-0 1 1](https://cloud.githubusercontent.com/assets/25709784/23341330/79daebb8-fc45-11e6-8a1c-9454647bd4a7.jpg)

**Version 0.1.0:**
![os-0 1 0](https://cloud.githubusercontent.com/assets/25709784/23341325/5a9ec7ce-fc45-11e6-8a1b-7a4bb60991c3.jpg)

**Comment by yvt** [comment]
This is an unintended behavior and is caused by a defect in the equation that boosts the ambient lighting when the fog color is too dark. I hadn't thought someone would actually choose such a vivid color.
