### ISSUE TITLE
Gun placement and size

### ISSUE THREAD

**Issue by YoSSUu** [yvt/openspades#591]
The hand and the items are too big, and sometimes gets in the way. So, can you make it smaller and move it to the bottom-right like aos?
http://i.imgur.com/VwNoxlD.png

http://i.imgur.com/2sSxiiu.png

**Comment by IBPX** [comment]
I agree. At least, there should be an option to have it take up less space. It could also handle it the way a small handful of games do, by allowing you to adjust the gun's opacity.
