### ISSUE TITLE
Grenade and Spade Smooth Animation

### ISSUE THREAD

**Issue by YoSSUu** [yvt/openspades#592]
The spade and grenade needs a smoother animation like the guns.

**Comment by yvt** [comment]
@YoSSUu I'm afraid that "smoother" sounds too general to me. Can you elaborate some more, please?

**Comment by YoSSUu** [comment]
smoother running animation*

**Comment by Tapmemer** [comment]
i think @YoSSUu means linearly interpolated animations

**Comment by yvt** [comment]
@Tapmemer They're already at least linearly interpolated. I think @YoSSUu means *more* smoother animation that guns already have.
