### ISSUE TITLE
my crosshair isnt in the middle of the screen and my character hand isnt in the right spot its more to the right and kind of out of the screen

### ISSUE THREAD

**Issue by TwistJustice** [yvt/openspades#593]

**Comment by yvt** [comment]
Can you [provide](https://github.com/yvt/openspades/wiki/Problem-Reporting) one or more screenshots, logs, and the version of OpenSpades that you are using?

**Comment by Tapmemer** [comment]
i think he fucked with the fov. i suggest typing /cg_fov 90 while ingame

**Comment by yvt** [comment]
I don't think `cg_fov` is relevant to this since the crosshair is rendered as a 2D image. [This wiki article](https://github.com/yvt/openspades/wiki/Common-Issues#screen-is-off-center) might help.

**Comment by yvt** [comment]
Any updates?

**Comment by feikname** [comment]
@TwistJustice Due to the lack of updates on this, I will close this report.

If you encounter this problem again, feel free to reopen this issue and be sure to give us all the [relevant information](https://github.com/yvt/openspades/wiki/Problem-Reporting).
