### ISSUE TITLE
Remove Hands Option

### ISSUE THREAD

**Issue by YoSSUu** [yvt/openspades#598]
Self-explanatory.

**Comment by damienflament** [comment]
Sorry, but I can't find this option you're talking about.

**Comment by IBPX** [comment]
I think they mean add an option which disables seeing your hands.

@YoSSUu Does that include hiding the gun too?

**Comment by YoSSUu** [comment]
No, I want to hide the hands, not the gun.

**Comment by yvt** [comment]
Hiding the hands while not hiding the gun means some weird animation in which the gun reloads by itself. I don't suppose you intend this kind of behavior, do you?

**Comment by YoSSUu** [comment]
Hmm, maybe you can remove the reload animation like aos?
If you can't, It's fine.

**Comment by Tapmemer** [comment]
some people like their smgs to reload magicly by themselfs

**Comment by yvt** [comment]
While it's technically feasible, I'm rejecting this due to artistic decision. It's still possible to remove hands by editing skin scripts (please see [Example: 2D Aim Down Sight 2](https://github.com/yvt/openspades/wiki/Example%3A-2D-Aim-Down-Sight-2)).
