### ISSUE TITLE
invalid initialization of non-const reference of type ‘spades::SettingSet&’

### ISSUE THREAD

**Issue by furryowl** [yvt/openspades#599]
[ 44%] Building CXX object Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o
/home/furryowl/openspades/Sources/Core/SettingSet.cpp: In constructor ‘spades::SettingSet::ItemHandle::ItemHandle(spades::SettingSet&, const string&, spades::SettingSet::ItemFlags)’:
/home/furryowl/openspades/Sources/Core/SettingSet.cpp:25:68: error: invalid initialization of non-const reference of type ‘spades::SettingSet&’ from an rvalue of type ‘<brace-enclosed initializer list>’
      : set{set}, handle{name, nullptr}, flags{flags}, modified{true} {
                                                                    ^
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o] Error 1
make[1]: *** [Sources/CMakeFiles/OpenSpades.dir/all] Error 2
make: *** [all] Error 2

**Comment by feikname** [comment]
Hello @furryowl could you please specify which OpenSpades version are you trying to compile and what platform are you on?

**Comment by furryowl** [comment]
Linux Mint 17.3 Rosa Cinnamon 64-bit
OpenSpades version latest
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
GNU Make 3.81
pkg-config Version: 0.26-1ubuntu4
libglew-dev Version: 1.10.0-3
libcurl4-openssl-dev Version: 7.35.0-1ubuntu2
libsdl2-dev Version: 2.0.2+dfsg1-3ubuntu1
libsdl2-image-dev Version: 2.0.0+dfsg-3build2
libalut-dev Version: 1.1.0-3ubuntu1
xdg-utils Version: 1.1.0~rc1-2ubuntu7-1linuxmint1
libfreetype6-dev Version: 2.5.2-1ubuntu2.5
libopus-dev Version: 1.1-0ubuntu1.2
libopusfile-dev Version: 0.5-1
when i try to compile i see many warnings and 
[ 44%] Building CXX object Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o
/home/furryowl/openspades/Sources/Core/SettingSet.cpp: In constructor ‘spades::SettingSet::ItemHandle::ItemHandle(spades::SettingSet&, const string&, spades::SettingSet::ItemFlags)’:
/home/furryowl/openspades/Sources/Core/SettingSet.cpp:25:68: error: invalid initialization of non-const reference of type ‘spades::SettingSet&’ from an rvalue of type ‘<brace-enclosed initializer list>’
      : set{set}, handle{name, nullptr}, flags{flags}, modified{true} {
                                                                    ^
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o] Error 1
make[1]: *** [Sources/CMakeFiles/OpenSpades.dir/all] Error 2
make: *** [all] Error 2

**Comment by furryowl** [comment]
second try
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/furryowl/openspades/openspades.mk
[  1%] Packing assets
~/openspades/Resources ~/openspades/openspades.mk/Resources
~/openspades/openspades.mk/Resources
[  1%] Built target OpenSpades_Resources
[  1%] Downloading non-GPL assets
BASEURL ************ https://github.com/yvt/openspades-paks/releases/download/r33/OpenSpadesDevPackage-r33.zip
[  1%] Built target OpenSpades_Resources_DevPaks
[  2%] Process unix stuff
[  2%] Built target OpenSpades_Unix
[ 13%] Built target Angelscript
[ 17%] Built target Angelscript_addons
[ 18%] Building CXX object Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o
/home/furryowl/openspades/Sources/Core/SettingSet.cpp: In constructor ‘spades::SettingSet::ItemHandle::ItemHandle(spades::SettingSet&, const string&, spades::SettingSet::ItemFlags)’:
/home/furryowl/openspades/Sources/Core/SettingSet.cpp:25:68: error: invalid initialization of non-const reference of type ‘spades::SettingSet&’ from an rvalue of type ‘<brace-enclosed initializer list>’
      : set{set}, handle{name, nullptr}, flags{flags}, modified{true} {
                                                                    ^
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o] Error 1
make[1]: *** [Sources/CMakeFiles/OpenSpades.dir/all] Error 2
make: *** [all] Error 2

**Comment by yvt** [comment]
Please update GCC to version 4.9 or later and try again. GCC 4.8 and earlier is NOT supported since its standard conformance level is too low to build OpenSpades.

**Comment by furryowl** [comment]
thank
