### ISSUE TITLE
Scripting API

### ISSUE THREAD

**Issue by dany-on-demand** [yvt/openspades#60]
Here's an idea, I can't imagine how would that work in C++, but maybe, just maybe, we could use SPADE_REGISTER_FUNCTION() to auto-generate an API for AngelScript/Squirrel/whatever?

As in, SPADE_REGISTER_FUNCTION() would call a onCall_FunctionName and handle_FunctionName() after it would finish.

ie.

sometype Player::GrenadeThrow(){
    SPADE_REGISTER_FUNCTION();
    /\* do stuff */
}

...

script file:

class Player:World { 
sometype onCall_GrenadeThrow()
{
   //return false; //would cancel the action
   //return velocity *= 2; //modify something
   return ...; //don't do anything
}

sometype handle_GrenadeThrow()
{
     if (World.ServerPlugins.Contains("Teleport")
         {
                Sound.PlaySound(Server.Fetch("zap.wav"));
          }
   return ...; //don't do anything
}
}

**Comment by NotAFile** [comment]
I'm not sure what this would actually do... Giving mods to much power is dangerous because it might lead to players creating advantages for themselves.

**Comment by theunknownxy** [comment]
From the perspective of a server operator the client is untrusted territory anyway, albeit giving scripts more freedom makes it certainly easier to cheat. And remember that OS is open source... Anyone can just download the source code and modify it.
And server-side scripts are in my opinion really messy. Running untrusted scripts (At least I don't really trust the ace of spades servers) dramatically increases the attack surface of the client.
