### ISSUE TITLE
Crash on ctrl+v on Windows

### ISSUE THREAD

**Issue by teodor6140** [yvt/openspades#603]
When i try to paste in chat the game just closes, no error message

Win 7 64 bit
0.1.1c

**Comment by feikname** [comment]
Confirmed on Windows 10 64-bit too.

**Comment by NotAFile** [comment]
Not confirmed on Debian Sid 64-bit

**Comment by MaddyMax0r** [comment]
Confirmed on Windows 7 32-bit

**Comment by iVAN2002** [comment]
Confirmed on Windows 8.1 64-bit.

**Comment by IhateTrains** [comment]
Confirmed on Windows 10 64-bit build 16257.

**Comment by feikname** [comment]
Might be related to what @tapmemer reported in #417.

> For some reason ctrl+c and ctrl+v crash the game (?)
> it happens over every release of openspades

**Comment by feikname** [comment]
For the sake of complete information, this bug was introduced in 0.1.1 and also affects 0.1.1c.

**Comment by feikname** [comment]
Does not affect me in latest master.

**Comment by yvt** [comment]
(hopping) It worked, it worked!
