### ISSUE TITLE
"Black sun" in the sky

### ISSUE THREAD

**Issue by DaProjectionist** [yvt/openspades#607]
OpenSpades 0.1.1 MSVC 19.0.24215.1

Appears that developers are into occult stuff now.

It shows up when I step into a large volumetric shadow and look up.

![screenshot-1493079021](https://cloud.githubusercontent.com/assets/27982111/25363905/facd1f5e-2966-11e7-8bdb-b16f18bd7df7.png)

Nvidia GTX560 on Windows 10.

My config file:
http://paste2.org/zFnE7VPL

**Comment by feikname** [comment]
Related (perhaps duplicate?): #447

**Comment by DaProjectionist** [comment]
Yes, it's the same. My apologies for creating a duplicate.
