### ISSUE TITLE
Grenade sound

### ISSUE THREAD

**Issue by DaProjectionist** [yvt/openspades#608]
This is a subjective complaint.

While the new gun sounds in 0.1.1. MSVC 19.0.24215.1 are kind of tolerable, the grenade sounds like crude farts recorded with 8 dollar mic. The old one was nice and deep and showed how great is the game's sound design depending on the distance, if you're on the ground or in a tunnel etc.

Please consider changing it back.

**Comment by yvt** [comment]
Thank you for your feedback!

If you have more comments or thoughts on the sound design, feel free to add on this.
