### ISSUE TITLE
Right click color picker

### ISSUE THREAD

**Issue by DaProjectionist** [yvt/openspades#610]
If I recall correctly in the original AceOfSpades the player was able to quickly pick up color of the nearby block by pointing at it and clicking the right mouse button. It would be nice if this convenient feature was implemented in OpenSpades.

**Comment by kmsiapps** [comment]
Already, You can capture the color with key <E(default)>.

**Comment by yvt** [comment]
By default the right mouse button and "e" are bound to "create a line of blocks" and "capture the color" respectively, but you can rebind them in the Setup window if you want to. 
<img width="803" alt="screen shot 2017-04-28 at 15 29 07" src="https://cloud.githubusercontent.com/assets/5253988/25516835/97449c00-2c27-11e7-828a-01bc77eb608b.png">
