### ISSUE TITLE
I can't figure out how to extract and run the openspades game file on Raspbian

### ISSUE THREAD

**Issue by PENGUANO** [yvt/openspades#615]
I was trying to play openspades on my Raspberry Pi 3b and it is saying that i cannot extract the file because it is a 7za file. I have downloaded Xarchiver and still nothing. Much appriciated. I love this game. :)

**Comment by yvt** [comment]
Getting OpenSpades working on Raspberry Pi might be... well, [pretty hard](https://github.com/yvt/openspades/issues/416). 

Binaries for Raspberry Pi are not provided, so you have to build it from source. Start by following [these instructions](https://github.com/yvt/openspades/blob/master/README.md#building-and-installing-from-source).

**Comment by PENGUANO** [comment]
@yvt that sounds pretty good. I appreciate your help with that. I've been trying to get my head around putting this stuff together but when I get to trying to creating the "opendpades.mk" directory in the open spades repo and to compile "mkdir openspades.mk
cd openspades.mk
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && make" I get a little stumped. It says that it it doesn't know what to do with "cmake".

**Comment by yvt** [comment]
@PENGUANO You need to install the `cmake` package first.

**Comment by PENGUANO** [comment]
Oh ok. So after that, that's basically it right? You install it and run it

**Comment by PENGUANO** [comment]
@yvt ^^^

**Comment by yvt** [comment]
@PENGUANO If it didn't output any errors, that's it.

**Comment by PENGUANO** [comment]
@yvt alright I'll get on that. Thanks for the help. It's a really cool game I think it will get on the map soon with the new update
