### ISSUE TITLE
Fedora cmake doesn't see glew.

### ISSUE THREAD

**Issue by Le0nX** [yvt/openspades#616]
I've installed glew. I've even compiled it from sources and reinstalled. It is in my include path. But i still get :
'''CMake Error at CMakeLists.txt:32 (message):
  GLEW not found, please install it and make sure CMake can find it (add it
  to the PATH)'''

**Comment by yvt** [comment]
Can you delete `CMakeCache.txt`, run `cmake` again and see if works?

**Comment by Le0nX** [comment]
openAL was the problem. Close.
