### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by Ludde856x** [yvt/openspades#617]
So I wanted to try building the game to test stuff so I got a error it said this 
The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "D:/downloads/openspades-0.1.1c/openspades-0.1.1c/OpenSpades.msvc/CMakeFiles/CMakeOutput.log".
See also "D:/downloads/openspades-0.1.1c/openspades-0.1.1c/OpenSpades.msvc/CMakeFiles/CMakeError.log".

The error log looked like this
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
Det går inte att hitta filen

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
Det går inte att hitta filen

Det går inte att hitta filen means it cant find the file

**Comment by devnexen** [comment]
**"The C compiler identification is unknown
The CXX compiler identification is unknown"**

**Comment by Ludde856x** [comment]
how do i fix it then

**Comment by feikname** [comment]
@Ludde856x Do you have Visual Studio 2015 installed? CMake should be able to find it.

**Comment by Ludde856x** [comment]
Yes I do have it installed

**Comment by feikname** [comment]
@Ludde856x Please try to clear the CMake cache and re-set the compiler as Visual Studio 2015 (make sure it's not the 64-bit one).

Although I think it's unlikely, the issue might be that you;re trying from the `D:\` drive, can you try from the `C:\` drive if the above solutions doesn't works too, please?

**Comment by Ludde856x** [comment]
Well that fixed some stuff but now i have this error
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/Name censored for security reasons/Desktop/mod/openspades-0.1.1c/openspades-0.1.1c/OpenSpades.msvc/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_85b89.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25123.0

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 2017-05-20 22:09:40.

Project "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_85b89.dir\Debug\".

  Creating directory "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_85b89.dir\Debug\cmTC_85b89.tlog\".

InitializeBuildStatus:

  Creating "cmTC_85b89.dir\Debug\cmTC_85b89.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_85b89.dir\Debug\\" /Fd"cmTC_85b89.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_85b89.dir\Debug\\" /Fd"cmTC_85b89.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  

  CheckIncludeFile.c

C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj]

Done Building Project "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.47

**Comment by Ludde856x** [comment]
@feikname 
I got longer this time now it looks like this 


Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/Name censored for security reasons/Desktop/mod/openspades-0.1.1c/openspades-0.1.1c/OpenSpades.msvc/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_85b89.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25123.0

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-05-20 22:09:40.

Project "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" on node 1 (default targets).

PrepareForBuild:

Creating directory "cmTC_85b89.dir\Debug".

Creating directory "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\Debug".

Creating directory "cmTC_85b89.dir\Debug\cmTC_85b89.tlog".

InitializeBuildStatus:

Creating "cmTC_85b89.dir\Debug\cmTC_85b89.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR="Debug"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_85b89.dir\Debug\" /Fd"cmTC_85b89.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x86

Copyright (C) Microsoft Corporation. All rights reserved.

cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR="Debug"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_85b89.dir\Debug\" /Fd"cmTC_85b89.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

CheckIncludeFile.c

C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj]

Done Building Project "C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj" (default target) (1) ->

(ClCompile target) ->

C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Name censored for security reasons\Desktop\mod\openspades-0.1.1c\openspades-0.1.1c\OpenSpades.msvc\CMakeFiles\CMakeTmp\cmTC_85b89.vcxproj]

0 Warning(s)

1 Error(s)

Time Elapsed 00:00:00.47

**Comment by Ludde856x** [comment]
I have fixed the issue i used the wrong externals thing thank you for helping me
