### ISSUE TITLE
Can't build in CMake

### ISSUE THREAD

**Issue by ParaYT** [yvt/openspades#618]
When I try to build in CMake this is what comes up:

The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

Configuring incomplete, errors occurred!
See also "C:/openspades-0.1.1c/Build/CMakeFiles/CMakeOutput.log".
See also "C:/openspades-0.1.1c/Build/CMakeFiles/CMakeError.log".

I have tried redownloading the source, moving files to diffrent drives but nothing works.....

**Comment by feikname** [comment]
Do you have Visual Studio 2015 installed? If you don't, then please install it. (and restart your computer, just to be sure CMake can detect it)

After that, open the CMake gui again and do the following:
 * Menu toolbar → `File` → `Delete cache`
 * Keep the source and build directories the same as before
 * Press the `configure` button
 * Select the compiler as Visual Studio 14 (2015)
   * **MAKE SURE IT'S NOT THE 64-BIT ONE**
 * Press the `generate` button 
 * Open `C:\openspaded-0.1.1c\Build\OpenSpades.sln` in Visual Studio 2015
 * Do the usual steps of compilation for VS (select the build type and compile)

This [wiki page](https://github.com/yvt/openspades/wiki/Building) might be helpful too.

Please reply here if the issue persists or if it was solved.

**Comment by yvt** [comment]
@ParaYT Any updates?

**Comment by feikname** [comment]
@ParaYT Due to lack of updates, I will close this issue.

Feel free to reopen it if you still have trouble with building openspades.
