### ISSUE TITLE
Build failure with Xcode : opus_multistream.h file not found

### ISSUE THREAD

**Issue by pierrelng** [yvt/openspades#621]
When I try to build with Xcode by following all the steps in README.md, this is what I get :

```
In file included from /openspades-0.1.1c/Sources/Core/OpusAudioStream.cpp:24:
Sources/Externals/include/opusfile.h:110:11: fatal error: 'opus_multistream.h' file not found
# include <opus_multistream.h>
          ^
```
A snippet from opusfile.h where the concerned `include` (line 110) is located :
```
...
# if defined(__cplusplus)
extern "C" {
# endif

# include <stdarg.h>
# include <stdio.h>
# include <ogg/ogg.h>
# include <opus_multistream.h>

/**@cond PRIVATE*/
...
```

**Comment by yvt** [comment]
Sorry, missed out that those files are required to use `libopusfile`. Downloading them from [here](https://github.com/xiph/opus/tree/master/include) and putting them into  `Externals/include` should solve the problem.

**Comment by pierrelng** [comment]
It did, thanks !

**Comment by NotAFile** [comment]
(where) Should this be put into the docs?

**Comment by pierrelng** [comment]
Two options :
- add the same instruction given here in `README.md` in the MacOS part.
- or add the required [files](https://github.com/xiph/opus/tree/master/include) directly in the `OpenSpades-Externals-Darwin-1.zip`, which is a pre-compiled zip file that you need to download anyway if you follow the instructions (download link at the end of this [readme.txt](https://github.com/yvt/openspades/blob/master/Sources/Externals/readme.txt)), containing all the C++ headers that go in the `Externals/include` folder.
