### ISSUE TITLE
Font don't have Polish characterts

### ISSUE THREAD

**Issue by Drenek** [yvt/openspades#628]
The font in games with many languages should be Unicode.

**Comment by feikname** [comment]
@Drenek Polish displays just fine on my Windows 10 with 0.1.1c version.

You can try to download [NoteFonts.pak](https://github.com/yvt/openspades/releases/download/v0.1.1b/NotoFonts.pak) and copy it to your [User Resource Directory]. After that, restart OpenSpades and it should work.

OpenSpades (latest version, at least) is bundled with `font-unifont.pak` and should be able to display polish characters by default. Could please specify the method of installation and platform you are on?

**Comment by feikname** [comment]
@drenek Any updates?

**Comment by feikname** [comment]
@drenek This issue has not received any updates for 2 months, so I will close it.

If the issue still persists, please reopen this thread.
