### ISSUE TITLE
updated reflex sight example?

### ISSUE THREAD

**Issue by KapitanUkraina** [yvt/openspades#641]
Could we get updates reflex sight example? https://github.com/yvt/openspades/wiki/Example:-Reflex-Sight-3 everything seems to be broken on actuall version, all of my old weapons are not working constantly crashing game. Can we get it? i tried everything but it keeps crashing.

**Comment by feikname** [comment]
Related: #632

**Comment by yvt** [comment]
Closing this as duplicate. 

This is clearly my oversight. Please see #632 for the work-around (untested, though).
