### ISSUE TITLE
Game doesn't run. (0xc0000005)

### ISSUE THREAD

**Issue by Jappu** [yvt/openspades#666]
The game doesn't seem to run on my computer, it gives me this error "The application was unable to start (0xc0000005).
Windows 7 Professional, 64-bit.

**Comment by yvt** [comment]
It looks like you are trying to open `OpenSpades.exe` directly from the ZIP archive.

You have to extract *all* files first. After that, try opening it again.

**Comment by Jappu** [comment]
I extracted all the files, still gives me the same error.

**Comment by yvt** [comment]
In that case, unfortunately, that error message is too generic to diagnose and the problem you've encountered seems quite rare. Here are the things you can try:

- Make sure your operating system is up-to-date by using Windows Update.
- Try updating or disabling anti-malware software (if any)

**Comment by Jappu** [comment]
Sorry for the month long reply, I got the game working by downloading the KB299926 update that was included in the releases page.
Case closed.
