### ISSUE TITLE
I'm thinking about making a PPA for this client, but it's going to be my first PPA and I don't know if I have to ask the author so...

### ISSUE THREAD

**Issue by fantoro** [yvt/openspades#670]
So are you (@yvt) ok with it? I think that I will probably able to update it fast since building isn't that hard once you have all the dependencies.

**Comment by NotAFile** [comment]
Hi. You don't need to ask for permission. The license of OpenSpades allows you to use and distribute OpenSpades as long as you make modifications to the source code available! But it would be nice if you made a new issue once you get the PPA working, so YVT can release an official PPA or link to yours perhaps.

**Comment by fantoro** [comment]
@NotAFile Ok thanks, I'm right now learning how to do it lol, I"ll open an issue once it'll be up and running :)

**Comment by fantoro** [comment]
Well, I thought that I will be able to do it but I just can't :P
