### ISSUE TITLE
PPA's ready!

### ISSUE THREAD

**Issue by fantoro** [yvt/openspades#672]
Hey so a while ago I made an issue about me making a PPA for this game, and it's ready.
https://launchpad.net/~fantoro/+archive/ubuntu/openspades/

Please report any issues if you found any.

(btw, I'm building for other releases right now)

EDIT: I just noticed that I should've named the version in another way (I should add the Ubuntu release name so that the packages won't conflict), I'm gonna remove the xenial package for a short time.

EDIT2: Fixed, I'm uploading the packages now

**Comment by teodor6140** [comment]
works good

**Comment by feikname** [comment]
I added the labels so I won't forget to include the PPA in the docs :)
