### ISSUE TITLE
Have seconday fire cycle through the player list backwards in sepctator mode.

### ISSUE THREAD

**Issue by Rootmars** [yvt/openspades#678]
Whenever I'm trying to cycle through the players in spectator mode, most of the time I miss the player I want to spectate because I clicked too rapidly. Since we can currently only traverse the player list forwards, I have to cycle through the player list all over again. I think that secondary fire should cycle through the player list backwards (just like what it does now in deathcam mode), while space should cycle through camera modes.

**Comment by NotAFile** [comment]
This was recommended before, but it wasn't possible due to left-click going into free camera mode. Now that this code is refactored, it is probably a lot easier to make changes. One possibility would be making space cycle through the views. (free, orbit, first-person)
