### ISSUE TITLE
Server ping in serverlist

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#685]
Servers respond to the "HELLO" string with "HI", this can be used to get the Ping of a server.

**Comment by yvt** [comment]
Is it already implemented on the server? If so, can you point me to the documentation?

**Comment by feikname** [comment]
@yvt It's not exactly docs, but: https://github.com/piqueserver/piqueserver/blob/eb6ef5acf14bde3d5f554881a929f5361cc2eacc/piqueserver/server.py#L570-574

**Comment by yvt** [comment]
@feikname Thanks, I see how it works now:

    echo -n HELLO | nc -u IPADDR PORT
    HI

**Comment by NotAFile** [comment]
As far as I can tell, this was implemented back when the master server was first added.

**Comment by yvt** [comment]
Implemented in the `v0.2.0` branch.
