### ISSUE TITLE
Other players do not appear to reload

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#690]
I am unsure if this ever worked, but currently the reload animations and sounds are not visible for other players.

**Comment by yvt** [comment]
Animations: No, it has never worked. Third-person models do not have reload animations.

Sounds: Probably a regression caused by 0389540cd07a3ebeb62a51f55e129a647a9d101e. I’ll give it a look.

**Comment by NotAFile** [comment]
They are not visible even in first-person mode though. Seeing your buddies reload would be great too though, but that's a separate issue.
