### ISSUE TITLE
Players dead on server connect appear alive

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#696]

**Comment by yvt** [comment]
AKAIK the protocol doesn’t define a way to tell whether each player is dead or alive at connection time. It can be circumvented on the server side by sending `KillAction` for every dead player though.

**Comment by NotAFile** [comment]
Well, it worked before, hmm.

**Comment by xtreme8000** [comment]
I agree with @yvt, this is not the fault of openspades.

**Comment by yvt** [comment]
I tested it right now and it didn't work even in the original client. Is there any specific line in piqueserver/pyspades that sends the dead/alive status of each player at connection time?

<img width="400" alt="screen shot 2017-12-30 at 1 35 21" src="https://user-images.githubusercontent.com/5253988/34442147-954ad188-ed03-11e7-9af5-b2a0997c5895.png">

**Comment by NotAFile** [comment]
Huh, interesting. You'd think It would have been noticed before if it had never worked. I found no reference to treating any packets special during connect in the server code.

**Comment by yvt** [comment]
I thought the same thing. Can this be closed then?

**Comment by NotAFile** [comment]
I'll checkout an older release and see if this still applies and if yes close it and reopen it on pique
