### ISSUE TITLE
Error building last release 0.1.1c

### ISSUE THREAD

**Issue by CitoplasmaX** [yvt/openspades#697]
[ 46%] Building CXX object Sources/CMakeFiles/OpenSpades.dir/Core/DynamicMemoryStream.cpp.o
[ 46%] Building CXX object Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o
/home/echedey/Descargas/openspades-0.1.1c/Sources/Core/SettingSet.cpp: In constructor ‘spades::SettingSet::ItemHandle::ItemHandle(spades::SettingSet&, const string&, spades::SettingSet::ItemFlags)’:
/home/echedey/Descargas/openspades-0.1.1c/Sources/Core/SettingSet.cpp:25:68: error: invalid initialization of non-const reference of type ‘spades::SettingSet&’ from an rvalue of type ‘<brace-enclosed initializer list>’
      : set{set}, handle{name, nullptr}, flags{flags}, modified{true} {
                                                                    ^
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/Core/SettingSet.cpp.o] Error 1
make[1]: *** [Sources/CMakeFiles/OpenSpades.dir/all] Error 2
make: *** [all] Error 2

**Comment by NotAFile** [comment]
what exact commit are you on?

**Comment by CitoplasmaX** [comment]
Nothing, i saw that i was using GCC 4.8.5, sorry.

**Comment by yvt** [comment]
Duplicate of #599. This is [a known issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025) of an old version of GCC. Please upgrade to GCC 4.9 or later and try again.

**Comment by CitoplasmaX** [comment]
GCC 4.9 is not setted by default on Ubuntu Trusty even if you have installed it.

**Comment by CitoplasmaX** [comment]
4.8.5 is setted by default.
