### ISSUE TITLE
Openspades launchpad on trusty requires libglew1.13

### ISSUE THREAD

**Issue by CitoplasmaX** [yvt/openspades#698]
libglew1.13 only was distributed on Ubuntu Xenial, Ubuntu Trusty has libglew1.10. Openspades on trusty version requires libglew1.13.

https://launchpad.net/~fantoro/+archive/ubuntu/openspades
https://packages.ubuntu.com/search?suite=trusty&searchon=names&keywords=libglew
https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=libglew

**Comment by yvt** [comment]
@fantoro?

**Comment by CitoplasmaX** [comment]
Yeah, but are you not building this with he/she?

**Comment by CitoplasmaX** [comment]
You have some references about his launchpad repository on your Readme then, i think this.

**Comment by feikname** [comment]
We should probably mention that the PPA is not an official mean (much like the AUR package) in `README/md, I guess.

**Comment by feikname** [comment]
@CitoplasmaX what version of Ubuntu are you using?

**Comment by CitoplasmaX** [comment]
Ubuntu Trusty...

**Comment by fantoro** [comment]
Hey, sorry for not responding. My PPA is a complete mess and I cannot fix anything there, I'm closing it, I recommend you to use the snap package or build it yourself.

**Comment by CitoplasmaX** [comment]
I can not install snap due to this...
![captura de pantalla de 2018-01-01 15 35 12](https://user-images.githubusercontent.com/30677099/34468836-6c60cdf6-ef09-11e7-994f-da6762c3b21a.png)
![captura de pantalla de 2018-01-01 15 35 14](https://user-images.githubusercontent.com/30677099/34468837-6c9beda0-ef09-11e7-9bac-243483ce69b8.png)

**Comment by CitoplasmaX** [comment]
I am using snap (a general purpose gene finding program suitable for both eukaryotic
and prokaryotic genomes), linux-lowlatency and upstart instead systemd.

**Comment by feikname** [comment]
As OpenSpades has no ppa anymore, I will close this as `wontfix`.
