### ISSUE TITLE
Problems running openspade from launchpad Ubuntu Trusty build

### ISSUE THREAD

**Issue by CitoplasmaX** [yvt/openspades#699]
I have installed libglew1.13 from Xenial repositories but i get this when i run this game.

echedey@echedey-500-500ns:~$ openspades
./openspades-bin: relocation error: ./openspades-bin: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by feikname** [comment]
Since the ppa is no longer available, I will close it as `wontfix`.
