### ISSUE TITLE
Can't Update to latest version on Ubuntu 14.04

### ISSUE THREAD

**Issue by BarnabyWoodrow** [yvt/openspades#702]
![error](https://user-images.githubusercontent.com/31696077/34480906-0c495854-efa7-11e7-95ca-79e9cfbae1f2.png)

I get this error when I click learn more on the startup screen, could anyone tell me how to update?
I am using a snap install.

**Comment by NotAFile** [comment]
Damn snap causing nothing but issues :P 

This wouldn't have happened with flatpak!!!11!11111!!!

On a more serious note, this is not reproducible on Fedora Linux compiling from source.

**Comment by yvt** [comment]
Although the Snapcraft version shares the same update feed with other distribution channel, the latest version is actually not available on Snapcraft yet. (Opened a separate issue for this: #703) For now, you need to build it from the source code to obtain the latest version.
 
Still, this error indicates a bug in the code to display the error message, which will be tracked by #704.
