### ISSUE TITLE
in 0.1.1c, you can move camera around your corpse. Not in 0.1.2?

### ISSUE THREAD

**Issue by pielover88888** [yvt/openspades#717]
Wondering why this is - as it was closer to how Classic worked in 0.1.1c than it is in 0.1.2

if you died, and viewed your corpse from above, you could move the mouse to orbit the camera.. but that's gone now? which is huge disadvantage in modes such as Arena to spot enemies for your teammates compared to classic or 0.1.1c.

**Comment by NotAFile** [comment]
Yes, this is a bug.

It is not always locked, just sometimes. My first theory was it only gets stuck when you are in first person mode, but then I remember it happening in third person mode too.
