### ISSUE TITLE
Error while compiling a shader

### ISSUE THREAD

**Issue by zortv** [yvt/openspades#718]
Help me :(
[https://imgur.com/a/HipYM](url)

**Comment by feikname** [comment]
Please upload your `SystemMessages.log` (located in `%APPDATA%\OpenSpades\Resources`) somewhere and send us the link to it so we can know more about the error.

Also, which version of OpenSpades are you attempting to use?

pt-br:
<details>
Por favor faça upload do arquivo `%APPDATA%\OpenSpades\Resources\SystemMessages.log` em algum lugar e publique o link aqui. Assim, teremos mais informação em como te ajudar.

Além disso, que versão do OpenSpades você está tentando usar?
</details>

**Comment by feikname** [comment]
@zortv Do you still have interest in trying to solve this issue? If no reply is given in 1 week, I will close this.
