### ISSUE TITLE
Crouching reduces recoil even if you're not touching the ground (jump/fall/etc)

### ISSUE THREAD

**Issue by pielover88888** [yvt/openspades#719]
This allows for jump shots to be done with less recoil, simply by pressing ctrl mid-air, and this behavior is unlike Classic 0.75.

In AoS Classic 0.75, mid-air recoil is unchanged by crouching, and is also more than standing recoil (Openspades uses standing recoil when mid-air, it seems?)

**Comment by BR-** [comment]
https://github.com/BR-/openspades/commit/e48a2273b94f8ed4b5616210ef41634da49cfb75
https://github.com/BR-/openspades/commit/d7da684263de01e85a902ac465733d4629309a40
Here's the algorithm and values the old 0.75 client uses for recoil. Haven't checked it against 0.76.

**Comment by yvt** [comment]
Fixed by #766
