### ISSUE TITLE
Game crashes, unknown error.

### ISSUE THREAD

**Issue by BarnabyWoodrow** [yvt/openspades#721]
I get this when launching the game.
![screenshot from 2018-02-02 15 10 43](https://user-images.githubusercontent.com/31696077/35740599-31210dd6-082d-11e8-93a3-5d588330006d.png)

**Comment by lieff** [comment]
Looks like both regex fails on this file:
```
		std::regex wavRegex {".*\\.wav", std::regex::icase};
		std::regex opusRegex {".*\\.(?:opus|ogg)", std::regex::icase};
```
But I have no idea why this happens on your system. May be you have mess in /usr/include from different gcc versions.

**Comment by feikname** [comment]
Probably dupe of #665

**Comment by yvt** [comment]
Closing this as a duplicate of #665.
