### ISSUE TITLE
CMAKE_CONFIGURATION_TYPES Error in CMAKE

### ISSUE THREAD

**Issue by r7vmc** [yvt/openspades#725]
I have this error when trying to generate with CMAKE
![capture](https://user-images.githubusercontent.com/30477547/36156351-cd05d1e2-10e7-11e8-8671-d6a604776081.PNG)

**Comment by yvt** [comment]
Can’t see the error message from that screenshot. Can you copy and paste it here? I think it is displayed in the log pane (the bottom part of the window) but is scrolled out.

**Comment by r7vmc** [comment]
@yvt the full log

electing Windows SDK version  to target Windows 10.0.16299.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified



Configuring incomplete, errors occurred!
See also "C:/Users/azooz/Desktop/openspades-0.1.2/openspades.msvc/CMakeFiles/CMakeOutput.log".

**Comment by r7vmc** [comment]
@feikname I have Visual Studio Community 17

And the generator in CMake is Visual Studio 15

**Comment by yvt** [comment]
@r7vmc Then set the generator to Visual Studio 15 (2017). It needs to match the version of compiler that is actually installed.

**Comment by NotAFile** [comment]
Offtopic, but why exactly does it not build on newer VS versions and is it possible to fix that?

**Comment by r7vmc** [comment]
@yvt ok I will try and I will be back

**Comment by r7vmc** [comment]
@yvt still not working but I will install BuildTools and select MSBuild.exe manually

**Comment by r7vmc** [comment]
so after installing MSBuild i got this bug :(

```Selecting Windows SDK version  to target Windows 10.0.16299.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0

    Copyright (C) Microsoft Corporation. All rights reserved.

    

    Build started 2/14/2018 4:25:41 PM.

    Project "C:\Users\azooz\Desktop\openspades-0.1.2\openspades.msvc\CMakeFiles\3.10.2\VCTargetsPath.vcxproj" on node 1 (default targets).

    C:\Users\azooz\Desktop\openspades-0.1.2\openspades.msvc\CMakeFiles\3.10.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    Done Building Project "C:\Users\azooz\Desktop\openspades-0.1.2\openspades.msvc\CMakeFiles\3.10.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    

    Build FAILED.

    

    "C:\Users\azooz\Desktop\openspades-0.1.2\openspades.msvc\CMakeFiles\3.10.2\VCTargetsPath.vcxproj" (default target) (1) ->

      C:\Users\azooz\Desktop\openspades-0.1.2\openspades.msvc\CMakeFiles\3.10.2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    

        0 Warning(s)

        1 Error(s)

    

    Time Elapsed 00:00:00.17

    

  Exit code: 1



Configuring incomplete, errors occurred!
See also "C:/Users/azooz/Desktop/openspades-0.1.2/openspades.msvc/CMakeFiles/CMakeOutput.log".```

**Comment by r7vmc** [comment]
and this is Build Tools 2015 btw i wasnt able to install 2017

**Comment by yvt** [comment]
@NotAFile It does, actually. In fact, 0.1.2 was built using VS2017. 

@r7vmc Usually MSBuild is installed to `Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\MSBuild.exe` automatically when you install Visual Studio. Did you enable the C++ language support while installing it?

**Comment by r7vmc** [comment]
@yvt i think it's not working cuz i didnt enable C++ with Visual Studio

**Comment by yvt** [comment]
@r7vmc So, did it work after enabling C++?

**Comment by feikname** [comment]
Closing this due to lack of feedback for more than 3 months. Please reopen if you still have the issue.
