### ISSUE TITLE
New update available bug?

### ISSUE THREAD

**Issue by Leprecorn** [yvt/openspades#730]
Just compiled Openspades 0.1.2, yet still getting the update announcement telling me to update to 0.1.2
![screenshot_2018-03-04_12-26-37](https://user-images.githubusercontent.com/35517584/36945627-2de3060e-1fa9-11e8-8fa8-dcb7c9a1fd19.jpg)

**Comment by yvt** [comment]
Perhaps it’s loading a stale `PackageInfo.json` from a previous installation. Have you run `make install`?

**Comment by Leprecorn** [comment]
Ah, that seems to have fixed it. Thanks
