### ISSUE TITLE
Can't spectate dead players in latest release.

### ISSUE THREAD

**Issue by BarnabyWoodrow** [yvt/openspades#733]
In the latest openspades release, you cant spectate dead player, which you could in the last release. It is a disadvantage on modes like arena, when some people can enemy's coming but some can't.

**Comment by NotAFile** [comment]
Yes, it was added on purpose. You can change it. The setting is called /cg_skipDead[...] I don't remember the rest.

**Comment by BarnabyWoodrow** [comment]
Where is the config file? @NotAFile

**Comment by feikname** [comment]
@BarnabyWoodrow The instructions for updating config variables can be found [here](https://github.com/yvt/openspades/wiki/Config-Variables#how-to-update-config-variables)

**Comment by BarnabyWoodrow** [comment]
Close this now
