### ISSUE TITLE
OpenSpades does not want to launch

### ISSUE THREAD

**Issue by 3nt17y** [yvt/openspades#736]
Upon trying to launch the executable file, I keep getting the message that something went horribly wrong.
This is the download link of the .dmp file - https://filebin.net/nc0r0rimoau01ce4
I will provide you with any additional information that may be required in order for you to be able to help me with this issue.

Thank you for all your effort in advance.

**Comment by NotAFile** [comment]
Hey, the following would be helpful:

 - platform (OS, distro, version)
 - method of installation
 - hardware (CPU and GPU)

**Comment by feikname** [comment]
@3nt17y Could you also check if it works when launching with software renderer instead of OpenGL?

**Comment by NotAFile** [comment]
@feikname to me it sounds like it doesn't even get to the launcher/settings screen

**Comment by yvt** [comment]
@3nt17y Can you provide the log file? It can be found in [the config directory](https://github.com/yvt/openspades/wiki/User-Resource-Directory).

Also, please update the video driver to the latest version! 
(AMD’s debug symbol server doesn’t provide `.dll`s for extremely old drivers, and without them core dumps are practically useless.)

**Comment by 3nt17y** [comment]
@NotAFile 

- Windows 7 Professional
- Downloaded from https://github.com/yvt/openspades/releases/download/v0.1.2/OpenSpades-0.1.2-Windows.zip and simply extracted from the zip file
- Intel Core 2, 2.4 GHz
   ATI Radeon HD 4350

**Comment by 3nt17y** [comment]
@yvt 

[SystemMessages.log](https://github.com/yvt/openspades/files/1874823/SystemMessages.log)

The video driver is up to the latest version available.

**Comment by feikname** [comment]
@3nt17y Hey, sorry for the late response!

I will try to take a look at what could possibly have gone wrong with your OpenSpades launch 😕.

**Comment by feikname** [comment]
(closed due to lack of further info, please reopen or create a new issue if you still have interest in attempting to solve this problem)
