### ISSUE TITLE
Portable OpenSpades?

### ISSUE THREAD

**Issue by shnbwmn** [yvt/openspades#738]
The Windows dist saves config files to _AppData_. For portability (between computers) it would need to be saved to the **program folder**. Would it be possible to add this as an option? Maybe a `-portable` parameter or an ingame setting asking where to put config files.

Currently I use [yaP](https://rolandtoth.hu/yaP/) but native portability would be great.

Thanks!

**Comment by yvt** [comment]
You mean... [the portable mode that was secretly added in OpenSpades 0.1.1c](https://github.com/yvt/openspades/wiki/Directories#portable-mode-since-011c-windows-only)?

**Comment by shnbwmn** [comment]
Oh. Didn't see that one 👍 💯

**Comment by feikname** [comment]
Closing due to the requested enhancement being already available 😉
