### ISSUE TITLE
Consider using Vcpkg for managing the external dependencies on Windows and macOS builds

### ISSUE THREAD

**Issue by yvt** [yvt/openspades#739]
https://github.com/Microsoft/vcpkg

**Pros:**

- Developers no longer have to trust the pre-compiled package maintainer (= me!) not to put malicious things in the pre-compiled opaque binary blob
- Developers (including me) will automatically have an access to the latest version of dependent libraries
    - Pre-compiled libraries are built manually and aren't updated for quite a long time.

**Cons:**

- Developers have to trust Microsoft and the ecosystem
- Extra step for installing vcpkg

**Comment by NotAFile** [comment]
Linux support is now available, it seems.

**Comment by theunknownxy** [comment]
Sadly vcpkg only seems to know about the latest version of a package. I guess if something has a breaking change in a release, this would break the build. But compared to the painful mess of compiling the dependencies on Windows, it's probably a small problem.

**Comment by SeekingMeaning** [comment]
If, theoretically, I managed to hack together some sort of "support" for Vcpkg with BetterSpades (theoretically), what additional things would I (theoretically) need to do to do the same for OpenSpades? At a glance, it looks like the only shared dependency between the two projects is GLEW and the ones specific to OpenS being curl, SDL2, and zlib.

**Comment by yvt** [comment]
It seems that the recommended way to lock packages is to lock the version of vcpkg, e.g., by [adding] vcpkg as a Git submodule.

[adding]: https://github.com/lukka/CppBuildTasks/blob/master/README.md#use-vcpkg-as-a-submodule-of-your-git-repository
