### ISSUE TITLE
Cannot vote kick if user has a hashtag in front of their name.

### ISSUE THREAD

**Issue by lweob** [yvt/openspades#740]
I've seen a few examples of this happening. Basically, you cannot vote-kick a user if their name has a hashtag in front of it (e.g. "#Deuce"). I've seen 2 examples today of users using this bug to their advantage and aimbotting. Please fix this.

**Comment by NotAFile** [comment]
This is not an OpenSpades issue, it is a server issue.

You can try convince the server operators to install a script that blocks these usernames, or use piqueserver, which does not have this bug.

**Comment by lweob** [comment]
oh, my bad i thought /votekick was a default OpenSpades command

cheers!

**Comment by NotAFile** [comment]
Commands (with some exceptions) are all handled by the server.

**Comment by feikname** [comment]
> oh, my bad i thought /votekick was a default OpenSpades command

No problems 😉. 

Closing it as invalid.
