### ISSUE TITLE
Terrible performance after launch

### ISSUE THREAD

**Issue by marsmoon** [yvt/openspades#742]
OS: Debian
OpenSpades: 0.1.2 and master

I get 5-10 fps shortly after launch (also in the menu) and after every map change on the server. It becomes playable a few minutes after loading and playing on a map and later improves even more. During that period of bad performance, the ping reported by the game is very high too, but maybe that's another bug. This happens on low, medium and high settings.

**Comment by feikname** [comment]
Just out of the curiosity, do you have an older computer? I used to have similar problems with 2007-era ones.

**Comment by marsmoon** [comment]
No, I can run the game on highest settings with 40-60 fps, but shortly after map load it's around 5 fps.

**Comment by yvt** [comment]
@marsmoon Does that still happen with **Global Illumination** turned off?

I had experienced similar symptoms on dusty old machine with the oldest generation of AMD APU (on which OS runs faster than AoS because CPU is potato), which I reported as #34.

If this issue is identical with #34, the result of `r_debugTiming 1` + `r_debugTimingGPUTime 0` should indicate that a large portion of CPU time is spent on **Radiosity**.

**Comment by yvt** [comment]
@marsmoon Also, can you please post information about your GPU and installed driver?

**Comment by marsmoon** [comment]
Disabling global illumination fixes it. I'm using Radeon R7 250x with a free driver that comes with Debian.

**Comment by yvt** [comment]
> a free driver that comes with Debian

That leaves ambiguity; AFAIK there are at least four drivers capable of driving R7 250X (GCN 1st gen. or SI; Southern Islands):
1. Gallium3D-based “radeonsi”
2. AMD “AMDGPU" (support for SI is experimental)
3. AMD “AMDGPU PRO” (closed-source binary blob that plugs into AMDGPU)
4. AMD Catalyst “fglrx” (closed-source)

If I remember correctly, “my dusty old machine” runs on the Gallium3D-based “radeon” driver. It’s based on Gallium3D, which means that, despite having a fundamentally different GPU architecture, it shares some parts of its code with the first driver that I mentioned in the above list.

Probably “radeonsi” is the default choice for driving SI cards in many Linux distributions and so is the case with your Debian machine. Based on this assumption and my observations, the best guess would be that [the `glTexSubImage3D` calls](https://github.com/yvt/openspades/search?q=texsubimage3d&unscoped_q=texsubimage3d) in the global illumination implementation are hitting an unoptimized code path in the shared part of the Gallium3D drivers.

**Comment by marsmoon** [comment]
It's simply called "radeon", so it might be the first one. It's free, but requires non free firmware. I've tried AMDGPU a year ago, but it didn't work with my card. fglrx was abandoned by AMD and is not supported anymore (doesn't work with recent xorg I think).

There are some information here: https://wiki.debian.org/AtiHowTo

**Comment by feikname** [comment]
> Disabling global illumination fixes it. I'm using Radeon R7 250x with a free driver that comes with Debian.

As this problem is out of OpenSpades scope to fix and the workaround has been found, I will now close this issue.
