### ISSUE TITLE
Hotkey to view the chatlog

### ISSUE THREAD

**Issue by marsmoon** [yvt/openspades#744]
The chat area is very small and it's very easy to miss messages. There should be a hotkey that a user could hold to see a bigger chatlog. I propose key H or U as the default. Pressing esc and clicking a UI button is too distracting and takes too much time.

Also mentioned in: https://github.com/yvt/openspades/issues/544#issuecomment-272709088

**Comment by BR-** [comment]
Here's something:
https://github.com/BR-/openspades/commit/4911e94ae4151dd1f5602c8651d0adea7a072adb
https://github.com/BR-/openspades/commit/238c20cccd5475f917242c4219ae19a6ee986143

I'd like to add another hotkey to expand the ingame chat window, to see another 10 lines or so back without needing to stop playing to open the UI.

**Comment by feikname** [comment]
Hey @BR- would you mind opening a pull request for adding your hotkey modifications to OpenSpades? 👍
