### ISSUE TITLE
Where are network players stored in the source code?

### ISSUE THREAD

**Issue by tomlister** [yvt/openspades#745]
Where are network players stored in the source code?

Thanks

**Comment by NotAFile** [comment]
"how do I haxx OS pls I don't want to actually put in the effort though"?

If you want to develop on OS, you probably want to check out the developers section of the buildandshoot.com discord, github issues are not really a good format for this.

**Comment by tomlister** [comment]
Jeez you're an asshole. I has just asking how/where network players are stored. Really helpful buddy.

**Comment by tomlister** [comment]
Can you at least tell me where network players are rendered.

**Comment by godwhoa** [comment]
Can be closed now. (See BnS discord.)
