### ISSUE TITLE
Error running 'sudo cmake install' on ubuntu 18.04

### ISSUE THREAD

**Issue by BarnabyWoodrow** [yvt/openspades#749]
I get this error: 

-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/share/doc/openspades/AUTHORS
-- Up-to-date: /usr/local/share/doc/openspades/LICENSE
-- Up-to-date: /usr/local/share/doc/openspades/README.md
-- Up-to-date: /usr/local/share/menu/openspades
-- Installing: /usr/local/share/man/man6/openspades.6.gz
-- Installing: /usr/local/share/doc/openspades/changelog.gz
-- Up-to-date: /usr/local/share/doc/openspades/copyright
CMake Error at cmake_install.cmake:65 (file):
  file INSTALL cannot find
  "/home/barney/openspades/openspades.mk/Resources/pak000-Nonfree.pak".

Makefile:107: recipe for target 'install' failed
make: *** [install] Error 1

Any ideas?

**Comment by feikname** [comment]
The nonfree pak somehow didn't get downloaded during your `make`, it seems.

**Comment by feikname** [comment]
Also, the easiest way IHMO is to rebuild again.

From the root of the openspades git clone, run:
```sh
rm -rf openspades.mk
mkdir openspades.mk
cd openspades.mk
cmake ..
make
sudo make install
```

It should work without any problems, just did it in a VM right now.

Also, please note that the instructions say `sudo make install`, not `sudo cmake install` (make, not cmake). I don't know much about OpenSpades build system, but there might be a significant difference.

**Comment by BarnabyWoodrow** [comment]
Thanks, this solved it.
