### ISSUE TITLE
Error while linking a program 'Shaders/BasicBlockDepthOnly.program'

### ISSUE THREAD

**Issue by damienflament** [yvt/openspades#750]
Hi !

I just downloaded OpenSpades 0.1.2 for Windows. The launcher shows up fine. As this computer is quite old, I put all graphical configuration options to "Low", disable Antialiasing and other graphical improvements.

Using software rendering, it works.

But when starting the game using OpenGL rendering, it fails showing a error message:

     A serious error caused OpenSpades to stop working:
     Error while linking a program 'Shaders/BasicBlockDepthOnly.program'

### BackTrace from SystemMessages.log

    Error while linking a program 'Shaders/BasicBlockDepthOnly.program':
    
    
    at C:\Users\tcpp\Documents\Projects\openspades\Sources\Draw\GLProgram.cpp:67
    ?Link@GLProgram@draw@spades@@QAEXXZ at C:\Users\tcpp\Documents\Projects\openspades\Sources\Draw\GLProgram.cpp:51
    ?CreateProgram@GLProgramManager@draw@spades@@AAEPAVGLProgram@23@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z at C:\Users\tcpp\Documents\Projects\openspades\Sources\Draw\GLProgramManager.cpp:85
    ?RegisterProgram@GLProgramManager@draw@spades@@QAEPAVGLProgram@23@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z at C:\Users\tcpp\Documents\Projects\openspades\Sources\Draw\GLProgramManager.cpp:57
    ?DoInit@MainScreen@gui@spades@@AAEXXZ at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\MainScreen.cpp:273
    ?RunFrame@MainScreen@gui@spades@@UAEXM@Z at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\MainScreen.cpp:232
    ?Run@SDLRunner@gui@spades@@QAEXHH@Z at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\SDLRunner.cpp:403
    ?Run@Runner@gui@spades@@QAEXXZ at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\Runner.cpp:70
    ?RunProtected@Runner@gui@spades@@QAEXXZ at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\Runner.cpp:42
    _SDL_main at C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\Main.cpp:312

See complete [SystemMessages.log](https://gist.github.com/damienflament/ab5ef01ea555bb1634f23d66df2b676d).

### System Info

    OpenGL-capable graphics accelerator is available.
    Vendor: Intel
    Name: Mobile Intel(R) 4 Series Express Chipset Family
    Version: 2.1.0 - Build 8.15.10.1892
    GLSL Version: 1.20  - Intel Build 8.15.10.1892

    GL_ARB_framebuffer_sRGB is NOT SUPPORTED
      r_srgb is disabled.
    GL_EXT_framebuffer_blit is NOT SUPPORTED
      r_blitFramebuffer is disabled.
    GL_EXT_texture_array is NOT SUPPORTED
      Water 2 is disabled.
    Max Texture Size: 4096
    Max 3D Texture Size: 128
      Global Illumination is disabled (512 required)
    Max Combined Texture Image Units: 16
    Max Vertex Texture Image Units: 16
    Max Varying Components: 41

    Your video card supports all required OpenGL extensions/features.

### Environment

OS: Windows 7 Family Premium, build 7601, x64 architecture

**Comment by damienflament** [comment]
Mayne is it due to some missing libraries or bad libraries versions ?

Which are the requirements on Windows (usually I play on Linux).

**Comment by yvt** [comment]
Looks like a duplicate of #741. It’s a video driver’s bug that causes compilation failure with no-op shaders.

Please see [my comment](https://github.com/yvt/openspades/issues/741#issuecomment-392104500) that includes a temporary work-around for this issue.

**Comment by feikname** [comment]
@damienflament Could you please check if the aforementioned workaround fixes your probem?

**Comment by damienflament** [comment]
Yes. It works. I got other issues but the game launches
.
As said by @yvt, it seems to be a video driver bug, because some graphic issues appends with AoS too. But it's not my computer so I will not investigate further.

Tanks.
