### ISSUE TITLE
Error when trying to build OpenSpades

### ISSUE THREAD

**Issue by memexd123** [yvt/openspades#751]
I was trying to build OpenSpades and got this error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
cd "D:\openspades\openspades-0.1.2\openspades.msvc\Resources"
if %errorlevel% neq 0 goto :cmEnd
D:
if %errorlevel% neq 0 goto :cmEnd
powershell -ExecutionPolicy Bypass "D:/openspades/openspades-0.1.2/Resources/mkpak.ps1" "D:/openspades/openspades-0.1.2/openspades.msvc/bin/MinSizeRel/Resources"
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	OpenSpades_Resources	C:\Program Files\visualstudio2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133

**Comment by feikname** [comment]
Honestly I have no idea what's going wrong with your build. I recommend you try to do a clean one (bby deleting OpenSpades.msvc contents and re-generating them.

If you still have this problem after doing that, please reopen this issue 😉
