### ISSUE TITLE
Cannot votekick players with a name beginning in "#"

### ISSUE THREAD

**Issue by SyntaxIGE** [yvt/openspades#757]
I'm sure this is brought up before but it is a serious problem. The game is unplayable without this being fixed.

**Comment by NotAFile** [comment]
This is not an OpenSpades issue. This is a server issue. Piqueserver (which is pyspades compatible) has had this fixed for a while, however many server owners don't upgrade or install the workaround for pyspades.

**Comment by yvt** [comment]
As @NotAFile said, this issue falls outside the scope of OpenSpades. I’m closing this.

(Also, if I remember correctly, you can votekick players by their ID, for example, by `/votekick #23`. Or, are there any servers where this usage is not supported?)
