### ISSUE TITLE
Game does not want to load

### ISSUE THREAD

**Issue by GXRebellion** [yvt/openspades#760]
The game will open just fine, and i can select a server to join but before it can load, i'll here a gun shot and then the game crashes. I can give any other information if necessary.

**Comment by yvt** [comment]
Take look at [the "How do I report problems?” section of this page](https://github.com/yvt/openspades/wiki/Problem-Reporting#how-do-i-report-problems):

> * Your `SystemMessages.log` file, present in the [User Resource Directory](https://github.com/yvt/openspades/wiki/User-Resource-Directory)
> * Your operating system (e.g.: *Windows 10*, *Mac OS X 10.9*, *GNU/Linux Ubuntu 16.04*)
> * Your OpenSpades version
> * In case  its a *renderer* related issue, your graphics card.
> * And if your OpenSpades crashed, the Crash Dump of it.

A crash dump is generated or not generated, depending on the cause of the crash. If a crash dump is generated, you should see a message saying like “something went terribly wrong, please send the crash dump”.

Pro tip: Use a service like [GitHub Gist](https://gist.github.com) or [Pastebin.com](https://pastebin.com) when posting a large text file like `SystemMessages.log`.

**Comment by feikname** [comment]
@GXRebellion Could you update this issue with more info as specified above please?

**Comment by feikname** [comment]
(closed due to lack of further info, please reopen or create a new issue if you still have interest in attempting to solve this problem)
