### ISSUE TITLE
"Version 0.1.2 is available! (You currently have 0.1.1c)"

### ISSUE THREAD

**Issue by superpowers04** [yvt/openspades#765]
I just installed the game and its asking to be upgraded I installed from snap PLS HELP, Im on "Ubuntu 18.04 LTS (Bionic Beaver)"

**Comment by feikname** [comment]
It seems @yvt forgot to update the snap version from 0.1.1c to 0.1.2, so you'll have to wait a bit until that happens.

**Comment by feikname** [comment]
Related: #703

**Comment by popey** [comment]
As I still had access to the openspades snap in the store, I have built an updated snap and published it (after testing). Hope that's okay. :) . I am happy to continue publishing updated snaps there to take the load off you guys. 

If you `snap install openspades` now, you'll get 0.1.3.
https://snapcraft.io/openspades

**Comment by popey** [comment]
This issue can probably be closed now. :)
