### ISSUE TITLE
Particles severely hamper performance in Software Rendering Mode

### ISSUE THREAD

**Issue by blehmeh98** [yvt/openspades#773]
It's cool that this game has software rendering mode as an option. I just got this game running on a VERY old linux laptop for fun by enabling it (whereas the openGL mode would crash on startup because the Intel GMA in this thing lacks support entirely for lots of Open GL features). Here's the specs of the laptop:

- It's a 2007 Intel Macbook running Lubuntu 16.04
- It's got a Core 2 duo processor
- It's got some Intel GMA integrated graphics card (note that modern laptops come with an intel card from the 1000's series or greater. GMA is old as dirt. It's so old that the card doesn't even support some Open GL functions at all that many games make use of. For example, Half Life 2 (alongside any other source engine based game) crashes on launch
- I think it has 2 gb of ram
- It has a native screen resolution of 1200 by 800 pixels
- I ran it in software mode with 4 times scaling down, and it ran at a very choppy but still playable framerate. I also had to disable EAX in the audio options.

 I noticed one problem with the software rendering mode, and that's the particles. Normally, they're kinda fine when viewed from far away. However, if you dig a block right in front of you, the pixels are huge and cause your game to choke, at least on my computer. Granted, this machine is an edge case and is probably strictly the oldest laptop you would want to even try to run this game on, but please give an option to disable particles entirely, especially in software mode. Blocks not leaving behind particles when dug will look ugly, yes, but I would prefer it over the game kinda freezing.

**Comment by blehmeh98** [comment]
I'm an idiot who didn't check the settings menu.

**Comment by feikname** [comment]
Glad you found a solution!

Please don't hesitate to ask any more questions (granted you try to find a setting for them first lol).
