### ISSUE TITLE
Build from master loses fps in comparison to 0.1.2

### ISSUE THREAD

**Issue by jdmota** [yvt/openspades#786]
After I built the lastest master version of OS, I noticed a fps drop from 160 to like 60, in comparison to 0.1.2

After making various builds, I found out that the problem started on commit https://github.com/yvt/openspades/commit/5ec968ecf5b7726cff73f636f313d239322aac68

All the builds were done in Windows 10 using Visual Studio Code 15 2017, with the same configurations and game settings.

**Comment by jdmota** [comment]
Wait. I guess the problem is that vsync is now enabled, since before it did not work. Disabling it in game settings fixes the problem.

**Comment by xtreme8000** [comment]
`SDL_GL_SetSwapInterval` handles vsync, which should explain the drop to 60fps
