### ISSUE TITLE
Teammates Trap Players in Babel

### ISSUE THREAD

**Issue by 0verk1ll** [yvt/openspades#794]
In Babel games, a teammate can build blocks around you to trap you. Since blocks placed by your own team cannot be destroyed in part of the map, the only way to be free is to die. The only ways to die are to hope that an enemy comes along to kill you or throw a grenade at your feet.
Is there a way to prevent teammates from placing blocks around you? They trap you just to be annoying.

**Comment by feikname** [comment]
Closing in favor of piqueserver/piqueserver#421
