### ISSUE TITLE
Players Can Increase Health, Grenades, and Blocks Arbitrarily

### ISSUE THREAD

**Issue by 0verk1ll** [yvt/openspades#795]
By editing **Player.cpp**, players can arbitrarily increase their health, grenade count, and block count.

```
/* default health 100 */
health = 500;
/* default grenades 3*/
grenades = 500;
/* default blockStocks 50 */
blockStocks = 500;
```

I made the above changes and recompiled openspades.

The servers I tested on could detect the change to health and acted as if I only had 100 health.

The servers I tested on allowed me to place 55 blocks, but no more. I should only be allowed to place 50 blocks.

All but one server I tested on allowed me to use as many grenades as I wanted.

Is there a way to prevent people from cheating like this? I also posted this issue to [piqueserver](https://github.com/piqueserver/piqueserver/issues/422).

**Comment by NotAFile** [comment]
This is also not a client issue.

**Comment by BR-** [comment]
You can't get more health than the server gives you.
The extra 5 blocks is a little bit of leeway in case your client gets out of sync somehow. We could remove it, but I don't think people are likely to hack for five blocks, and removing it might make laggy players confused that they can't place their last few blocks.
You can't actually throw more than three grenades. To you, it will look like you are throwing them, but they will not do damage or destroy blocks, and nobody else can see them.
