### ISSUE TITLE
Japanese IME and Korean Input do not work on Windows

### ISSUE THREAD

**Issue by MuffinTastic** [yvt/openspades#802]
Tested on Windows 8.1 and in a Windows 10 VM. Strangely enough, (Simplified) Chinese IME works.

I am not quite familiar enough with Korean input to say what should generally happen, but none of the input makes it through.

Expected functionality for JP IME would be:
Type the romanized text, and while you're typing, the text changes to its hiragana equivalent (or otherwise depending on IME mode) in real time, appearing with an underline beneath it. Arrow keys Up/Down or [Shift+]Tab allow you to choose suggestions for the whole of the text, or if you press space, you can change individual parts of the text into the IME's suggestions via Left/Right, and Up/Down or [Shift+]Tab. After you hit Enter, the underlined text is inputted into the field and the underline goes away.

What actually happens is... nothing. The IME doesn't work, the game just eats all of the input, even the ASCII characters. Typing as though the IME were working doesn't work.

Seeing as the IME doesn't work, I'm unsure as to whether or not there are UI elements displaying the IME's suggestions. If not, that's another thing to look into.

Typing the text in another program and pasting it into OpenSpades does _work_, but this is obviously not ideal.

**Comment by MuffinTastic** [comment]
Yeah, that works, on both 8.1 & 10

**Comment by feikname** [comment]
@yvt is the SDL2.dll bundled in latest OpenSpades version enough to close this issue?

**Comment by yvt** [comment]
@feikname Can’t test it right now, but I don’t think so. I’ll close the issue when the external library package is updated to include the latest version of `SDL2.dll`.

**Comment by Conticop** [comment]
Seems like updating SDL2 would fix 3/4 (or even more) different issues at once lmao.
