### ISSUE TITLE
firing smg make some lag 

### ISSUE THREAD

**Issue by sarahkawaii69** [yvt/openspades#808]
screenshot per shot is disabled all is disabled but the lag continues,my pc supports but the lag is only problem here

**Comment by feikname** [comment]
Is this version 0.1.3? Could you please post your PC specs,

**Comment by NotAFile** [comment]
Doesn't sound like a bug to me. Sounds more like some feature is turned on that the computer can't handle.

**Comment by feikname** [comment]
Closing this due to lack of author's feedback and likeliness of being an user error.
