### ISSUE TITLE
Packet ID 60 breaks map loading

### ISSUE THREAD

**Issue by teodor6140** [yvt/openspades#826]
When piqueserver sends a ProtocolExtensionInfo packet with id 60 while the map is being loaded, I get stuck at the team selection screen and an error is printed to stdout.
`Map decoder returned error. Maybe we will get more data...`
Adding `reader.GetType() != 60 &&` after NetClient.cpp L611 fixes the problem.

**Comment by NotAFile** [comment]
This would be fixed by https://github.com/yvt/openspades/pull/825
