### ISSUE TITLE
Can't compile on Ubuntu

### ISSUE THREAD

**Issue by R3B3LCAUSE** [yvt/openspades#83]
I followed all the install instructions exactly into the terminal but when i got to "mkdir openspades.mk && cd openspades.mk && cmake .. && make OpenSpades" it said that Cmake wasn't installed. I installed Cmake and tried to continue with the instructions but I can't do "cd openspades.mk && cmake .. && make OpenSpades" or 
"sudo make install" and I don't know how to start over. Your compiling instructions need to take into account that not everyone knows what cmake is or has it installed. MAKE IT MORE NOOB FRIENDLY

**Comment by avoidr** [comment]
I had the same error message as @FMagarik:
`GLEW not found, please install it and make sure CMake can find it (add it
to the PATH)`

I did what @noway suggested:
>For GLEW, try searching for paths that are described in https://github.com/yvt/openspades/blob/master/cmake/FindGLEW2.cmake

There *was* `/usr/include/GL/glew.h`.

What did fix my problem was installing freealut-devel¹.
Those are the files provided by this package:
```
/usr/bin/freealut-config
/usr/lib/pkgconfig/freealut.pc
/usr/lib/libalut.a
/usr/include/AL/alut.h
```

So it seems that CMake is giving a misleading message. Is this a CMake cfg problem? Is this a CMake problem? Perhaps you can fix this.

¹ That's the package name on VoidLinux.
