### ISSUE TITLE
Button rendering broken

### ISSUE THREAD

**Issue by mschlumpp** [yvt/openspades#849]
The button rendering seems to be broken on the newest flatpak runtime (flathub/jp.yvt.OpenSpades#2). Might be related to an updated software component.
When a button is hovered or pressed, only the upper right edge will be affected by the color change. The following image shows this effect when the button is pressed.
![image](https://user-images.githubusercontent.com/900903/65529833-27f27400-def7-11e9-8873-5eaec833de45.png)
This seems to affect almost all buttons with an "edge" (except the buttons in the limbo screen) on both SW/GL.

**Comment by kdeleteme** [comment]
This bug is weird. I recently hopped to Fedora 32 and the bug seems to have fixed itself. Prior to that, I was on ArchLinux (Gnome Shell 3.36) and was able to reproduce this bug.

**Comment by kdeleteme** [comment]
@mschlumpp I sent a [pull request](https://github.com/flathub/jp.yvt.OpenSpades/pull/5) on the flathub version, updating imagemagick and the freedesktop runtime. Can you try it and see if that fixes the issue? On my end, button rendering seems to be fine on Fedora Workstation 32.

**Comment by mschlumpp** [comment]
Yeah, the runtime update fixed the flatpak version and the bug also disappeared in a normal build on my Linux distribution. 
I guess it will always be a mystery which library caused this issue.
