### ISSUE TITLE
Question: Graphics API

### ISSUE THREAD

**Issue by hardBSDk** [yvt/openspades#850]
Hi, I'm a lover of OpenSpades since 2015 (version 0.0.12 the old school).

I thanks @yvt by made this Ace Of Spades "implementation" possible and made me fall in love by this Creative FPS because of his fun and relaxing.

My question is: when the Vulkan API would be implemented? Today, this API is highly mature and bring lots of performance and development improvements, the driver potential can be more explored and is easy to port.

Maybe the plan of yvt is to turn the game lightweight as possible by supporting legacy technologies such as OpenGL, but why not support the both APIs? the codepath can be complex or something else?
OpenSpades render supports lots of heavy effects and simulations that could drain a low-end computer, but if Vulkan were implemented? this framedrop could be cut by optimization and driver resource efficiency.

what you devs think?

Vulkan port could become live after 0.2.0 branch bump and Modernize PR?

**Comment by yvt** [comment]
Due to a change in the development environment, I'm now more willing to develop a Vulkan backend, but I wonder if there's a way to emulate some subset of Vulkan on OpenGL since we definitely want to continue supporting older hardware, but we don't have a bandwidth to develop and/or maintain more than one backend.

**Comment by hardBSDk** [comment]
> Due to a change in my development environment, I'm now more willing to develop a Vulkan backend, but I wonder if there's a way to emulate some subset of Vulkan on OpenGL since we definitely want to continue supporting older hardware, but we don't have a bandwidth to develop and/or maintain more than one backend.

I can imagine, I am grateful for your response.
