### ISSUE TITLE
Slow game for the first few minutes

### ISSUE THREAD

**Issue by 10010101001** [yvt/openspades#851]
When I join a server, the game runs extremely slowly at about 3-4 fps. After a few minutes on the server, the performance improves to 60 fps.

**Comment by Clogal** [comment]
This happens to me when i enable Global Illumination : 
https://github.com/yvt/openspades/wiki/Ambient-occlusion

You could try turning it off on Startup Screen.

**Comment by feikname** [comment]
Would you mind telling us your GPU and what GPU driver are you using?

**Comment by 10010101001** [comment]
Intel graphics 500, and disabling global illumination worked

**Comment by feikname** [comment]
@Clogal Could you tell us your GPU too? I will add to the Known Issues page later.

**Comment by Clogal** [comment]
Sure, ATI Radeon HD 5450

**Comment by feikname** [comment]
I'll close this now. For reference note to myself here's the list of other previous issues about this:
 * ~~#34~~ (wontfix)
   * ~~#742~~
   * ~~#851~~ (this one)
