### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pcktm** [yvt/openspades#852]
I'm trying to build OpenSpades on Windows, using Visual Studio 2017, following the compilation guide exactly and I'm getting two errors:
![image](https://user-images.githubusercontent.com/13273420/65976851-1b2ecc80-e471-11e9-8e4e-2cec418b736b.png)

**Comment by NotAFile** [comment]
It's going to be kind of hard to know what these error messages mean when they are in a different language

**Comment by pcktm** [comment]
Okay, so I fixed it by pretty much removing the whole culprit:

```cpp
~Handle() {
  if (ptr)
    ptr->Release();
}
```
and that did the job, everything compiled and works just fine.

**Comment by yvt** [comment]
> ```c++
> ~Handle() {
>   if (ptr)
>     ptr->Release();
> }
> ```

That'll lead to a massive memory leak. I suppose the error message is about `FontManager` being an incomplete type? Adding `#include <Client/FontManager.h>` to an appropriate source file (the one that caused `Handle<FontManager>::~Handle` to be instantiated) should fix the issue, but you have to use the Output window to see the full trace.

**Comment by yvt** [comment]
Sorry, it was `<Client/Fonts.h>`. Fixed in 33d920a5408be7876be3bc7ce6b3ff463dfa3d07
