### ISSUE TITLE
Grenade Sound

### ISSUE THREAD

**Issue by Kallemies** [yvt/openspades#860]
Hi, I recently updated from 0.0.12b to 0.1.3.

I noticed the grenade sound had changed.

Is there any way I can change the sound back to how it was in 0.0.12b?

I tried to copy the sound files of 0.0.12b to 0.1.3, but the same grenade sound is still there.

**Comment by yvt** [comment]
The audio format was changed from WAV to Opus in #493. This change is hard-coded for most sound files, so they need to be converted to Opus using a transcoding tool like ffmpeg to be used in 0.1.x.
