### ISSUE TITLE
First person bullet tracers

### ISSUE THREAD

**Issue by dwnpr** [yvt/openspades#866]
Bullet tracers not shown coming out of own weapon but coming out of other players weapons
Original ace of spades had them

**Comment by yvt** [comment]
They are not displayed by design for aesthetic reasons.

**Comment by feikname** [comment]
Could a setting be added for those who like it?

**Comment by pielover88888** [comment]
a long while back, I modded my openspades to do this. the issue that openspades has that Classic didn't have, is it's rendered much more smoothly as an animation along the set path, and not as voxels.

Combine this with high framerates, and the path beginning exactly where the camera is, and the shotgun will *completely* block your view for a couple frames. If it were set as an option, it'd have to be changed to not render tracers from your own player until they're a decent distance away.

**Comment by JohnDowson** [comment]
The solution would be to render them not from camera origin but from gun barrel.

**Comment by yvt** [comment]
I'm working on it in my personal branch. It turned out to be pretty cool, though they are mostly obstructed by the default ironsights.
