### ISSUE TITLE
Crash on server browser mouse hover

### ISSUE THREAD

**Issue by TheMikirog** [yvt/openspades#867]
When the game is launched and I hover my mouse to any of the servers in the server browser, the game crashes. Sometimes it happens, sometimes it doesn't and I don't know why.

I've got a crash dump though.
[OpenSpadesCrash181244296.zip](https://github.com/yvt/openspades/files/3853995/OpenSpadesCrash181244296.zip)

**Comment by yvt** [comment]
The crash seems to have been caused by the OpenAL driver (OpenAL Soft). Can you try switching the audio renderer to YSR?
<img width="527" alt="Screen Shot 2019-11-16 at 18 05 42" src="https://user-images.githubusercontent.com/5253988/68990874-bc47da00-089b-11ea-9708-6e5d037dd5bf.png">

**Comment by TheMikirog** [comment]
Tried switching to it and it worked, but I dunno if it's because of that.
My game worked in OpenAL at one point, so now I have no idea.
Anyway the game works, so that's that.
