### ISSUE TITLE
Invalid argument: im in GLRenderer.cpp:498

### ISSUE THREAD

**Issue by evorios** [yvt/openspades#87]
Sometimes last release crashs with error:
2013/11/01 20:41:38 [MainWindowHandler.cpp:108] Unhandled exception in SDLRunner:
[/Users/tcpp/Programs/MiscPrograms/openspades/Sources/Draw/GLRenderer.cpp:498] Invalid argument: im
Collected backtrace:
void spades::client::Client::DrawScene() at Client.cpp:1843
void spades::client::Client::RunFrame(float) at Client.cpp:435
virtual void spades::gui::SDLRunner::Run() at SDLRunner.cpp:220
static void MainWindow::StartGame(const spades::ServerAddress&) at MainWindowHandler.cpp:89
void MainWindow::QuickConnectPressed() at MainWindowHandler.cpp:138
int main(int, char**) at Main.cpp:98

**Comment by VelocityRa** [comment]
I presume this is now fixed.
