### ISSUE TITLE
Camera selects a random death player when ragdolls are disabled

### ISSUE THREAD

**Issue by Oxlot** [yvt/openspades#879]
_I'm not sure if it's caused by the death body position_ or _by turning off ragdolls with_ `/cg_ragdolls 0`, _or just by something server side_ but the camera teleports many blocks further from where you got killed selecting the nearest dead body.

[video.zip](https://github.com/yvt/openspades/files/4202235/video.zip)

**Comment by NotAFile** [comment]
why do you keep creating issues and then closing without an explanation
