### ISSUE TITLE
Coop build mode

### ISSUE THREAD

**Issue by dany-on-demand** [yvt/openspades#89]
Something for the future, it would be nice to have a cooperative build mode, both server and client side. Inspired by Cube 2 a little. I imagine you'd be able to see where other players are about to place blocks, you'd be able to build prefabs, of course immediate build and destroy and unlimited blocks, and an option to immediately hit back into the game so that you can test the map.

There might be a problem with scripts on the server side though. This whole "mode" thing would either have to be hacked in, or the server would need a minor refactoring.

**Comment by feikname** [comment]
Leaving this closed while next-gen protocol development is paused.
