### ISSUE TITLE
Call function

### ISSUE THREAD

**Issue by ferbadams** [yvt/openspades#912]
Hello!
How do I call a function of C ++ code in code written in AngelScript? What are its limitations? Is there any special way to return values?

**Comment by yvt** [comment]
As for the binding interface provided by AngelScript, please refer to the documentation included with [AngelScript 2.31.1 SDK](http://www.angelcode.com/angelscript/downloads.html).

As for how it's used in OpenSpades, please see [`Sources/ScriptBindings`](https://github.com/yvt/openspades/tree/master/Sources/ScriptBindings).

**Comment by yvt** [comment]
Closing the issue since the original question has been answered.
