### ISSUE TITLE
Branch Modernize: SPAssertion failed: m.IsSolid(x, y, z)

### ISSUE THREAD

**Issue by sudodouuuuuu** [yvt/openspades#918]
Ran application, normal start, can connect, but unable to engage in-game after throwing this:
SPAssertion failed: m.IsSolid(x, y, z)
at /Users/././openspades-patch-modernize/Sources/Client/GameMapWrapper.cpp:158
void spades::client::GameMapWrapper::AddBlock(int, int, int, uint32_t) at GameMapWrapper.cpp:105
void spades::client::World::Advance(float) at World.cpp:62
void spades::client::Client::UpdateWorld(float) at Client_Update.cpp:165
virtual void spades::client::Client::RunFrame(float) at Client.cpp:373
virtual void spades::gui::MainScreen::RunFrame(float) at MainScreen.cpp:240
virtual void spades::gui::ConsoleScreen::RunFrame(float) at ConsoleScreen.cpp:180
void spades::gui::SDLRunner::Run(int, int) at SDLRunner.cpp:428
void spades::gui::Runner::Run() at Runner.cpp:70
void spades::gui::Runner::RunProtected() at Runner.cpp:42
int main(int, char **) at Main.cpp:320

Built on Xcode with:
macOS 10.15.7
Intel Iris Pro Graphics 6200 1536 MB

**Comment by sudodouuuuuu** [comment]
I should add this is also consistent.

**Comment by sudodouuuuuu** [comment]
Oh you know what, maybe I should go look at the "How to report issues first."

**Comment by feikname** [comment]
@sudodouuuuuu Thanks for the report.

> Built on Xcode with:
macOS 10.15.7
Intel Iris Pro Graphics 6200 1536 MB

Was this built on latest commit?

**Comment by yvt** [comment]
Confirmed. This can only happen in debug builds.

**Comment by yvt** [comment]
Thank you - this would have been overlooked if no one had tried debug builds (the build instructions recommend against this). Also we clearly need a better testing infrastructure and always-on assertions.
