### ISSUE TITLE
Compiled game is slower than original

### ISSUE THREAD

**Issue by XfedeX** [yvt/openspades#920]
OS: Windows 10

I just compiled the game, but it was much slower than the game downloaded from RELEASES.
So i added PGO optimization, but it is still slower than the original game.
Any help? How to compile faster?

**Comment by NotAFile** [comment]
This needs more. How are you compiling openspades. What is your compiler. What cmake compilation options are you using.

**Comment by XfedeX** [comment]
Fixed! Just changed from PGO optimization to LTCG (https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-160)
