### ISSUE TITLE
CG_SMP : What is it?

### ISSUE THREAD

**Issue by XfedeX** [yvt/openspades#922]
I've seen this option in Openspades, and I don't know what is it.
On [https://sites.google.com/a/yvt.jp/openspades/manual](url) it says:
_"cg_smp enables multi-threaded renderer implementation by setting 1.
    FPS might be improved on multi-core system.
    Mouse/Keyboard control tends to be lagged due to the scheduling of the operating system."_
So, it uses multiple CPU cores for culling before rendering?
Or what?

**Comment by yvt** [comment]
`cg_smp` moves GPU command generation to a separate thread. It really doesn't improve FPS because modern CPUs are sufficiently fast. (On the other hand, multi-socketed Pentium 4 machines might benefit from this option.)

This option was removed in version 0.1.3.
