### ISSUE TITLE
High resolution scaling problems (only see upper left corner)

### ISSUE THREAD

**Issue by RustyLovecraft** [yvt/openspades#927]
When I play in 1680x1050 and higher, the bottom and the right side of the screen are cut off.  Higher resolutions (namely 1080p) have the same issue; lower resolutions like mostly have no issues. I get a "zoomed-in" view of the upper left corner, so I can't see some UI and HUD items.

The issue persists in fullscreen and windowed mode. In fullscreen, there is no way to see those hidden regions of the screen. In windowed mode, the window size exceeds the size of my display, so I can drag the window to see the right side (but there is no way to see the bottom). I have tested using my laptop display and my external monitor, and the issue is consistent for both.

Interestingly, the Alt+Enter shortcut to toggle fullscreen doesn't work for 1080p either. It tries for a moment but nothing happens. If I uncheck "Fullscreen Mode" in the launcher, and 1080p is selected, the game launches in fullscreen anyway. I can launch the game in windowed mode and freely toggle fullscreen for other (lower) resolutions. Maybe this is a separate issue, but it seems related.

1920x1080 (16:9): fullscreen glitch, windowed impossible
1680x1050 (16:10): fullscreen glitch, windowed glitch
1600x900 (16:9): fullscreen OK, windowed glitch
1440x900 (16:10): fullscreen OK, windowed glitch
1400x1050 (~4:3): fullscreen glitch, windowed glitch
1366x768 (~16:9): fullscreen OK, windowed OK
1360x768 (~16:9): fullscreen OK, windowed OK
1280x1024 (~4:3): fullscreen glitch, windowed glitch
1280x960 (4:3): fullscreen OK, windowed glitch
1280x800 (16:10): fullscreen OK, windowed OK
1280x768 (5:3): fullscreen OK, windowed OK
1280x720 (16:9): fullscreen OK, windowed OK
1280x600 (~21:9): fullscreen OK, windowed OK
1152x864 (4:3): fullscreen OK, windowed glitch
1024x768 (4:3): fullscreen OK, windowed OK
800x600 (4:3): fullscreen OK, windowed OK

By looking at this data we can see that narrow aspect ratios tend to be cut off in windowed mode (the bottom is cut off; sides are visible for these). They are also the only lower resolutions prone to fullscreen display issues. 

My machine is the Alienware m15 laptop. It runs Windows x64 and native 1080p. My OpenSpades version is up to date: 0.1.3 . I can share screenshots of the issue but my Internet connection is refusing to upload them right now. I really don't get why this display issue happens, and I would love to get it figured out.

**Comment by RustyLovecraft** [comment]
1680x1050 fullscreen:
![1680-1050-fullscreen](https://user-images.githubusercontent.com/55685536/102384909-107f2b00-3f82-11eb-88b4-4d308f4550d4.png)

1680x1050 windowed:
![1680-1050-windowed](https://user-images.githubusercontent.com/55685536/102385377-a2873380-3f82-11eb-9849-78141faa07eb.png)

1680x1050 taskbar thumbnail showing obscured regions in black:
![1680-1050-thumbnail-cutoff](https://user-images.githubusercontent.com/55685536/102384973-22f96480-3f82-11eb-94da-2c2d19a673bd.png)

1080p fullscreen:
![1920-1080-fullscreen](https://user-images.githubusercontent.com/55685536/102384980-268ceb80-3f82-11eb-89b4-d7006ea9bf67.png)

**Comment by RustyLovecraft** [comment]
1280x1024 fullscreen and windowed (to demonstrate issues with 4:3 and similarly narrow aspect ratios):

![1280-1024-fullscreen](https://user-images.githubusercontent.com/55685536/102386270-b7b09200-3f83-11eb-8737-0365ae41ed77.png)

![1280-1024-windowed](https://user-images.githubusercontent.com/55685536/102386300-c303bd80-3f83-11eb-9224-ad61bdc81e72.png)

My graphics settings in the launcher:

![gfx](https://user-images.githubusercontent.com/55685536/102386716-49b89a80-3f84-11eb-91de-c82ca0ed05ef.jpg)

**Comment by yvt** [comment]
Can you try replacing `SDL2.dll` with [the latest version (x86)](https://www.libsdl.org/download-2.0.php) and see if it works? The one that comes with OpenSpades 0.1.3 is very old and known to cause various issues.

**Comment by RustyLovecraft** [comment]
Awesome! 1080p works without a hitch now. Maybe the OS 0.1.3 download should be updated with the newer SDL2.dll? Thanks for the help.

My ext. display is actually 1440p. I can't get 1440p to work; I can set the launcher to it, but the game still launches in 1080p. I am rather content with this, though, considering this game is rather old, and it is now a lot easier to shoot baddies from afar!
