### ISSUE TITLE
paly on local network 

### ISSUE THREAD

**Issue by mrdragon110** [yvt/openspades#943]
hello 
i want to play this game on local network... 
but i don't know how ... i search about it but i cant find ... . can u help me to do this ?

**Comment by yvt** [comment]
You need to get a server program to start a LAN game (OpenSpades is not bundled with one). Here are the possible choices:
- **pyspades**: The popular one. I'm not sure where to find the latest version anymore...
- [**piqueserver**](https://github.com/piqueserver/piqueserver): The modernized version of pyspades. If you are on Linux or macOS or can use WSL, I'd definitely recommend this, though some old scripts written for pyspades might not work.
- **`server.exe` included with the vanilla client**: Probably the easiest option, but the functionalities are quite limited. You'll need 32-bit WINE to run on other platforms than Windows.

Cc @NotAFile
