### ISSUE TITLE
Aloha Server was traitor?

### ISSUE THREAD

**Issue by KirioKubu** [yvt/openspades#983]
I had a strange experience today, A player called Aloha.pk Admin came in and started a random voterick and said let's go to the Aloha.pk server, and then kill everyone on the other team, as if he wanted to force everyone to enter aloha because we were being hacked , so i think this guy was sent by the aloha admins.
I suspect that the Aloha.pk Server is cheating, just so everyone just logs into their Server, and when these suspects called Aloha.pk automatically log in, they start a random vote on any player. And this happened on another server and not theirs. Please teach me how to report a Server.
I suspect they are bots or even people.
I just don't know if you guys play Openspades or care about it
![68747470733a2f2f6f70656e7370616465736d656469612e7976742e6a702f6272616e642f4f70656e53706164657342616e6e65722e6a7067](https://user-images.githubusercontent.com/94113735/141290839-2960de39-4086-4b39-82d5-b64a79929d88.jpg)

**Comment by yusufcardinal** [comment]
aloha.pk has nothing to do with any activity outside its servers. While everybody can agree that behavior is prime shitty, there is little yvt or aloha can do about it. You need to contact the administrators of the server where it happened.

**Comment by yusufcardinal** [comment]
Also lol

**Comment by Autist69420** [comment]
sir this is openspades, not aloha.

**Comment by Oxlot** [comment]
sir this is openspades, not aloha.

**Comment by yvt** [comment]
Closing this as it's outside of this issue tracker's scope.
