### ISSUE TITLE
Don't open OpenAl 

### ISSUE THREAD

**Issue by atorresbr** [yvt/openspades#984]
FIX OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
 

1 - $ ps aux | grep pulseaudio

2 - kill all pulseaudio processes

3 - $ rm -rf /.config/pulse/ (force pulseaudio to regenerate config files)

4 - $ pulseaudio --start

5 - sudo reboot

Everything works as expected.

https://askubuntu.com/questions/1114659/ubuntu-18-04-pulseaudio-daemon-startup-failed

**Comment by mckaygerhard** [comment]
> This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> 
> https://www.youtube.com/watch?v=j9XRRP_GDfg

this video only forced to use wayland compistor.. is not related to the specific error

**Comment by atorresbr** [comment]
> > This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> > https://www.youtube.com/watch?v=j9XRRP_GDfg
> 
> this video only forced to use wayland compistor.. is not related to the specific error

But this tutorial fixed the error to my, bro

**Comment by mckaygerhard** [comment]
> > > This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> > > https://www.youtube.com/watch?v=j9XRRP_GDfg
> > 
> > 
> > this video only forced to use wayland compistor.. is not related to the specific error
> 
> But this tutorial fixed the error to my, bro

i repeat that is not a "FIX" is a stupid trick that only works in some cases..

**Comment by atorresbr** [comment]
> > > > This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> > > > https://www.youtube.com/watch?v=j9XRRP_GDfg
> > > 
> > > 
> > > this video only forced to use wayland compistor.. is not related to the specific error
> > 
> > 
> > But this tutorial fixed the error to my, bro
> 
> i repeat that is not a "FIX" is a stupid trick that only works in some cases..

you are using a Ubuntu 21.. ?  -- Please, install and reinstall Pulse Audio and PavuControl  --

FIRST: unINSTALL, and reboot, after, INSTALL and reboot.  This will fix the problem to you.

https://www.maketecheasier.com/fix-no-sound-issue-ubuntu/

**Comment by mckaygerhard** [comment]
> FIRST: unINSTALL, and reboot, after, INSTALL and reboot. This will fix the problem to you.

"reboot to changes take effect" 

 M$ windos XD

**Comment by atorresbr** [comment]
> > > > This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> > > > https://www.youtube.com/watch?v=j9XRRP_GDfg
> > > 
> > > 
> > > this video only forced to use wayland compistor.. is not related to the specific error
> > 
> > 
> > But this tutorial fixed the error to my, bro
> 
> i repeat that is not a "FIX" is a stupid trick that only works in some cases..

FIXED TO ANOTHER TUTORIAL ! 

 FIX OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
 

1 - $ ps aux | grep pulseaudio

2 - kill all pulseaudio processes

3 - $ rm -rf /.config/pulse/ (force pulseaudio to regenerate config files)

4 - $ pulseaudio --start

Everything works as expected.
As mentioned previously, this is not an actual solution but it should get sound going until further troubleshooting happens.

https://askubuntu.com/questions/1114659/ubuntu-18-04-pulseaudio-daemon-startup-failed

**Comment by atorresbr** [comment]
> > This tutorial fix OpenSpades Don't open OpenAl error on ubuntu 21.04 and 21.10
> > https://www.youtube.com/watch?v=j9XRRP_GDfg
> 
> this video only forced to use wayland compistor.. is not related to the specific error

Solved 100% now 


snApps do not work correctly with Wayland, the main ones are: kazam, OBS, and OpenSpades. How to switch to Ubuntu without this BULSHIT ?, just change ON the gear at the bottom right and choose the Ubuntu option without WAYLAND.

Another option to solve the problem: Open the terminal follow theses instructions.

cd ../../
cd etc/gdm3/
sudo nano custom.conf

and uncomment this line WaylandEnable=false

save with ctrl + o and ctrl  x 

sudo rebboot



![Ubuntu Without Wayland ](https://iili.io/hTENql.jpg)
