### ISSUE TITLE
OpenSpades locked to 60fps on Linux

### ISSUE THREAD

**Issue by nonperforming** [yvt/openspades#991]
[SystemMessages.log](https://github.com/yvt/openspades/files/7832849/SystemMessages.log)

Built from commit f532e85e1899e240ff0d61a0bec24f977d457923 (latest commit as of this post) through [AUR](https://aur.archlinux.org/packages/openspades-git/)

I am using Manjaro Linux KDE with my kernel being 5.15.6-xanmod2-MANJARO 
cl_fps is set to 0. I have also tried setting it to 1000 but with no results.

There is no template for bug reports, etc and this is one of my first issues so please tell me if I am doing anything wrong

**Comment by nonperforming** [comment]
I have no idea how to add a label. Can somebody mark this issue as `bug` and `OS-Specific: GNU/Linux`

**Comment by nonperforming** [comment]
Sorry, just found [this](https://github.com/yvt/openspades/wiki/Problem-Reporting#how-do-i-report-problems) [SystemMessages.log](https://github.com/yvt/openspades/files/7832845/SystemMessages.log)

**Comment by yvt** [comment]
V-sync is controlled by `r_vsync`. The possible options are listed [here](https://wiki.libsdl.org/SDL_GL_SetSwapInterval):

> 0 for immediate updates, 1 for updates synchronized with the vertical retrace, -1 for adaptive vsync

**Comment by nonperforming** [comment]
Ah yes, r_vsync was set to 1 and limiting the FPS to refresh rate. :sweat_smile:
